-- Evening Azkar Migration: Match duaandazkar.com exact 31-item sequence
-- Run this in Supabase SQL Editor

-- Step 1: Delete old evening azkar
DELETE FROM azkar_items WHERE category_id = 'evening';

-- Step 2: Insert new 31 evening azkar
INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_1', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

اَلْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِيْنَ ، الرَّحْمٰنِ الرَّحِيْمِ ، مَالِكِ يَوْمِ الدِّيْنِ ، إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِيْنُ ، اِهْدِنَا الصِّرَاطَ الْمُسْتَقِيْمَ ، صِرَاطَ الَّذِيْنَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوْبِ عَلَيْهِمْ وَلَا الضَّالِّيْنَ', 'Bismillahir-Rahmanir-Rahim. Al-hamdu lillahi Rabbil-''alamin. Ar-Rahmanir-Rahim. Maliki yawmid-din. Iyyaka na''budu wa iyyaka nasta''in. Ihdinas-siratal-mustaqim. Siratal-ladhina an''amta ''alayhim, ghayril-maghdubi ''alayhim wa lad-dallin.', 'In the name of Allah, the Most Gracious, the Most Merciful. All praise is due to Allah, Lord of the worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us to the straight path — the path of those upon whom You have bestowed favor, not of those who have evoked Your anger or of those who are astray.', 1, 'evening', 'Al Fateha: The Opening of the Quran', 'Quran 1:1-7', 1, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Allah said: ''I have divided prayer between Myself and My servant into two halves, and My servant shall have what he has asked for.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_2', 'الٓمٓ ، ذٰلِكَ الْكِتَابُ لَا رَيْبَ فِيْهِ هُدًى لِّلْمُتَّقِيْنَ ، الَّذِيْنَ يُؤْمِنُوْنَ بِالْغَيْبِ وَيُقِيْمُوْنَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُوْنَ ، وَالَّذِيْنَ يُؤْمِنُوْنَ بِمَا أُنْزِلَ إِلَيْكَ وَمَا أُنْزِلَ مِنْ قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوْقِنُوْنَ ، أُولٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ وَأُولٰئِكَ هُمُ الْمُفْلِحُوْنَ', 'Alif-Lam-Mim. Dhalikal-kitabu la rayba fih, hudal-lil-muttaqin. Alladhina yu''minuna bil-ghaybi wa yuqimunas-salata wa mimma razaqnahum yunfiqun. Walladhina yu''minuna bima unzila ilayka wa ma unzila min qablik, wa bil-akhirati hum yuqinun. Ula''ika ''ala hudam-mir-Rabbihim wa ula''ika humul-muflihun.', 'Alif, Lam, Mim. This is the Book about which there is no doubt, a guidance for those conscious of Allah — who believe in the unseen, establish prayer, and spend out of what We have provided for them, and who believe in what has been revealed to you and what was revealed before you, and of the Hereafter they are certain. Those are upon guidance from their Lord, and it is those who are the successful.', 1, 'evening', 'Alif Laam Meem: Opening of Al-Baqarah', 'Quran 2:1-5, Ad-Darimi', 2, 'It is reported that the Shaytan will not come near the one who recites the opening verses of Surah Al-Baqarah along with Ayat al-Kursi and the last verses of Al-Baqarah in the evening.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_3', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ ﴿١﴾

اَلْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِيْنَ ﴿٢﴾ الرَّحْمٰنِ الرَّحِيْمِ ﴿٣﴾ مَالِكِ يَوْمِ الدِّيْنِ ﴿٤﴾ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِيْنُ ﴿٥﴾ اِهْدِنَا الصِّرَاطَ الْمُسْتَقِيْمَ ﴿٦﴾ صِرَاطَ الَّذِيْنَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوْبِ عَلَيْهِمْ وَلَا الضَّالِّيْنَ ﴿٧﴾', 'Bismillahir-Rahmanir-Rahim. Al-hamdu lillahi Rabbil-''alamin. Ar-Rahmanir-Rahim. Maliki yawmid-din. Iyyaka na''budu wa iyyaka nasta''in. Ihdinas-siratal-mustaqim. Siratal-ladhina an''amta ''alayhim, ghayril-maghdubi ''alayhim wa lad-dallin.', 'In the name of Allah, the Most Gracious, the Most Merciful. All praise is due to Allah, Lord of the worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us to the straight path — the path of those upon whom You have bestowed favor, not of those who have evoked Your anger or of those who are astray.', 1, 'evening', 'Ayatul Kursi: The Greatest Protection', 'Quran 2:255, Hakim 2064', 3, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Allah said: ''I have divided prayer between Myself and My servant into two halves, and My servant shall have what he has asked for.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_4', 'لَا إِكْرَاهَ فِي الدِّيْنِ ، قَدْ تَبَيَّنَ الرُّشْدُ مِنَ الْغَيِّ ، فَمَنْ يَّكْفُرْ بِالطَّاغُوْتِ وَيُؤْمِنْ بِاللّٰهِ فَقَدِ اسْتَمْسَكَ بِالْعُرْوَةِ الْوُثْقَىٰ لَا انْفِصَامَ لَهَا ، وَاللّٰهُ سَمِيْعٌ عَلِيْمٌ', 'La ikraha fid-din, qad tabayyanar-rushdu minal-ghayy. Faman yakfur bit-taghuti wa yu''min billahi faqadis-tamsaka bil-''urwatil-wuthqa lanfisama laha. Wallahu Sami''un ''Alim.', 'There shall be no compulsion in the religion. The right course has become clear from the wrong. So whoever disbelieves in false deities and believes in Allah has grasped the most trustworthy handhold with no break in it. And Allah is Hearing and Knowing.', 1, 'evening', 'La Ikraha fid-Deen: No Compulsion in Religion', 'Quran 2:256', 4, 'This verse establishes the principle that faith must come from sincere conviction. Reciting it in the evening affirms one''s conscious choice of Islam and trust in Allah''s guidance.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_5', 'اَللّٰهُ وَلِيُّ الَّذِيْنَ آمَنُوْا يُخْرِجُهُمْ مِّنَ الظُّلُمَاتِ إِلَى النُّوْرِ ، وَالَّذِيْنَ كَفَرُوْا أَوْلِيَاؤُهُمُ الطَّاغُوْتُ يُخْرِجُوْنَهُمْ مِّنَ النُّوْرِ إِلَى الظُّلُمَاتِ ، أُولٰئِكَ أَصْحَابُ النَّارِ هُمْ فِيْهَا خَالِدُوْنَ', 'Allahu waliyyul-ladhina amanu yukhrijuhum minaz-zulumati ilan-nur. Walladhina kafaru awliya''uhumut-taghut, yukhrijunahum minan-nuri ilaz-zulumat. Ula''ika as-habun-nar, hum fiha khalidun.', 'Allah is the ally of those who believe. He brings them out from darknesses into the light. And those who disbelieve — their allies are false deities. They take them out of the light into darknesses. Those are the companions of the Fire; they will abide eternally therein.', 1, 'evening', 'Allah is the Ally of the Believers', 'Quran 2:257', 5, 'This verse affirms that Allah guides and protects the believers, bringing them from the darkness of ignorance into the light of faith.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_6', 'لِلّٰهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ، وَإِنْ تُبْدُوْا مَا فِيْ أَنْفُسِكُمْ أَوْ تُخْفُوْهُ يُحَاسِبْكُمْ بِهِ اللّٰهُ ، فَيَغْفِرُ لِمَنْ يَّشَاءُ وَيُعَذِّبُ مَنْ يَّشَاءُ ، وَاللّٰهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيْرٌ', 'Lillahi ma fis-samawati wa ma fil-ard. Wa in tubdu ma fi anfusikum aw tukhfuhu yuhasibkum bihillah. Fayaghfiru limay-yasha''u wa yu''adhdhibu may-yasha''. Wallahu ''ala kulli shay''in qadir.', 'To Allah belongs whatever is in the heavens and whatever is in the earth. Whether you show what is within yourselves or conceal it, Allah will bring you to account for it. Then He will forgive whom He wills and punish whom He wills, and Allah is over all things competent.', 1, 'evening', 'To Allah Belongs All That Is in the Heavens and Earth', 'Quran 2:284', 6, 'The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_7', 'آمَنَ الرَّسُوْلُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَّبِّهِ وَالْمُؤْمِنُوْنَ ، كُلٌّ آمَنَ بِاللّٰهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّنْ رُسُلِهِ ، وَقَالُوْا سَمِعْنَا وَأَطَعْنَا غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيْرُ', 'Amanar-Rasulu bima unzila ilayhi mir-Rabbihi wal-mu''minun. Kullun amana billahi wa mala''ikatihi wa kutubihi wa rusulih, la nufarriqu bayna ahadim-mir-rusulih. Wa qalu sami''na wa ata''na, ghufranaka Rabbana wa ilaykal-masir.', 'The Messenger has believed in what was revealed to him from his Lord, and so have the believers. All of them have believed in Allah and His angels and His books and His messengers, saying, "We make no distinction between any of His messengers." And they say, "We hear and we obey. Grant us Your forgiveness, our Lord, and to You is the final destination."', 1, 'evening', 'The Messenger Has Believed', 'Quran 2:285, Bukhari 5009', 7, 'Abu Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_8', 'لَا يُكَلِّفُ اللّٰهُ نَفْسًا إِلَّا وُسْعَهَا ، لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ، رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِيْنَا أَوْ أَخْطَأْنَا ، رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِيْنَ مِنْ قَبْلِنَا ، رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ، وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ، أَنْتَ مَوْلَانَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِيْنَ', 'La yukallifullahu nafsan illa wus''aha. Laha ma kasabat wa ''alayha maktasabat. Rabbana la tu''akhidhna in nasina aw akhta''na. Rabbana wa la tahmil ''alayna isran kama hamaltahu ''alal-ladhina min qablina. Rabbana wa la tuhammilna ma la taqata lana bih. Wa''fu ''anna waghfir lana warhamna. Anta mawlana fansurna ''alal-qawmil-kafirin.', 'Allah does not burden a soul beyond that it can bear. It will have the consequence of what good it has gained, and it will bear the consequence of what evil it has earned. "Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people."', 1, 'evening', 'Allah Does Not Burden a Soul Beyond Capacity', 'Quran 2:286, Bukhari 5009', 8, 'Abu Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him." Muslim reported that when this verse was revealed, Allah said after each supplication in it: "I have done so."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_9', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ هُوَ اللّٰهُ أَحَدٌ ، اَللّٰهُ الصَّمَدُ ، لَمْ يَلِدْ وَلَمْ يُوْلَدْ ، وَلَمْ يَكُنْ لَّهُ كُفُوًا أَحَدٌ', 'Bismillahir-Rahmanir-Rahim. Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakul-lahu kufuwan ahad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 3, 'evening', 'Surah Al-Ikhlas: Sincerity', 'Abu Dawud 5082, An-Nasa''i', 9, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to me, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn (Al-Falaq and An-Nas) three times in the morning and evening — they will suffice you against everything."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_10', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ أَعُوْذُ بِرَبِّ الْفَلَقِ ، مِنْ شَرِّ مَا خَلَقَ ، وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ، وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ، وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ', 'Bismillahir-Rahmanir-Rahim. Qul a''udhu bi Rabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-''uqad. Wa min sharri hasidin idha hasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 3, 'evening', 'Surah Al-Falaq: Seek Refuge from Evil', 'Abu Dawud 5082', 10, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to me, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn (Al-Falaq and An-Nas) three times in the morning and evening — they will suffice you against everything."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_11', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ أَعُوْذُ بِرَبِّ النَّاسِ ، مَلِكِ النَّاسِ ، إِلٰهِ النَّاسِ ، مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ، الَّذِيْ يُوَسْوِسُ فِيْ صُدُوْرِ النَّاسِ ، مِنَ الْجِنَّةِ وَالنَّاسِ', 'Bismillahir-Rahmanir-Rahim. Qul a''udhu bi Rabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer — who whispers in the breasts of mankind — from among the jinn and mankind."', 3, 'evening', 'Surah An-Nas: Seek Refuge from Whispers', 'Abu Dawud 5082', 11, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to me, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn (Al-Falaq and An-Nas) three times in the morning and evening — they will suffice you against everything."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_12', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ أَعُوْذُ بِرَبِّ النَّاسِ ﴿١﴾ مَلِكِ النَّاسِ ﴿٢﴾ إِلٰهِ النَّاسِ ﴿٣﴾ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ﴿٤﴾ الَّذِيْ يُوَسْوِسُ فِيْ صُدُوْرِ النَّاسِ ﴿٥﴾ مِنَ الْجِنَّةِ وَالنَّاسِ ﴿٦﴾', 'Bismillahir-Rahmanir-Rahim. Qul a''udhu bi Rabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer — who whispers in the breasts of mankind — from among the jinn and mankind."', 1, 'evening', 'Evening Supplication: Dominion Belongs to Allah', 'Muslim 2723', 12, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to me, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn (Al-Falaq and An-Nas) three times in the morning and evening — they will suffice you against everything."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_13', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ هُوَ اللّٰهُ أَحَدٌ ﴿١﴾ اَللّٰهُ الصَّمَدُ ﴿٢﴾ لَمْ يَلِدْ وَلَمْ يُوْلَدْ ﴿٣﴾ وَلَمْ يَكُنْ لَّهُ كُفُوًا أَحَدٌ ﴿٤﴾', 'Bismillahir-Rahmanir-Rahim. Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakul-lahu kufuwan ahad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 1, 'evening', 'Upon the Fitrah of Islam', 'Ahmad 15367', 13, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to me, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn (Al-Falaq and An-Nas) three times in the morning and evening — they will suffice you against everything."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_14', 'اَللّٰهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوْتُ وَإِلَيْكَ الْمَصِيْرُ.', 'Allāhumma bika amsaynā wa bika aṣbaḥnā wa bika naḥyā wa bika namūtu wa ilayka-l-maṣīr.', 'O Allah, by You we have entered the evening and by You we enter upon the morning. By You, we live and we die, and to You is the return.', 1, 'evening', 'By Your Leave We Have Reached the Evening', 'Al-Adab al-Mufrad 1199', 14, '', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/38.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_15', 'اَللّٰهُمَّ إِنِّيْ أَمْسَيْتُ مِنْكَ فِيْ نِعْمَةٍ وَعَافِيَةٍ وَسِتْرٍ ، فَأَتِمَّ عَلَيَّ نِعْمَتَكَ وَعَافِيَتَكَ وَسِتْرَكَ فِي الدُّنْيَا وَالْآخِرَةِ', 'Allahumma inni amsaitu minka fi ni''matin wa ''afiyatin wa sitr, fa atimma ''alayya ni''mataka wa ''afiyataka wa sitraka fid-dunya wal-akhirah.', 'O Allah, I have entered the evening receiving from You blessings, well-being and concealment (of my faults). So complete Your blessings upon me, Your well-being, and Your concealment in this world and the Hereafter.', 3, 'evening', 'Blessings, Well-being and Concealment', 'Ibn al-Sunni 41', 15, 'Abdullah ibn Umar (رضي الله عنه) reported: The Messenger of Allah (ﷺ) never used to leave this supplication in the morning and evening, asking Allah to complete His blessings, well-being, and concealment of faults upon him in this world and the Hereafter.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_16', 'لَا يُكَلِّفُ اللّٰهُ نَفْسًا إِلَّا وُسْعَهَا ، لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ، رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِيْنَا أَوْ أَخْطَأْنَا ، رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِيْنَ مِنْ قَبْلِنَا ، رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ، وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ، أَنْتَ مَوْلَانَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِيْنَ ﴿٢٨٦﴾', 'La yukallifullahu nafsan illa wus''aha. Laha ma kasabat wa ''alayha maktasabat. Rabbana la tu''akhidhna in nasina aw akhta''na. Rabbana wa la tahmil ''alayna isran kama hamaltahu ''alal-ladhina min qablina. Rabbana wa la tuhammilna ma la taqata lana bih. Wa''fu ''anna waghfir lana warhamna. Anta mawlana fansurna ''alal-qawmil-kafirin.', 'Allah does not burden a soul beyond that it can bear. It will have the consequence of what good it has gained, and it will bear the consequence of what evil it has earned. "Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people."', 1, 'evening', 'Fulfil Your Obligation to Thank Allah', 'Abu Dawud 5073', 16, 'Abu Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him." Muslim reported that when this verse was revealed, Allah said after each supplication in it: "I have done so."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_17', 'يَا رَبِّ لَكَ الْحَمْدُ كَمَا يَنْبَغِيْ لِجَلَالِ وَجْهِكَ وَعَظِيْمِ سُلْطَانِكَ', 'Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.', 'O my Lord, all praise is due to You as befits the Glory of Your Countenance and the Greatness of Your Authority.', 1, 'evening', 'Praise Befitting Divine Greatness', 'Ibn Majah 3801', 17, 'Abdullah ibn Umar (رضي الله عنه) reported: The Prophet (ﷺ) said, "A servant said: ''Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.'' The two angels did not know how to record it, so they ascended to the heavens and said: ''Our Lord, Your servant has said something and we do not know how to record it.'' Allah — while knowing best what His servant said — asked: ''What did My servant say?'' They replied: ''He said: Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.'' Allah said to them: ''Record it as My servant said it, until he meets Me and I shall reward him for it.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_18', 'يَا رَبِّ لَكَ الْحَمْدُ كَمَا يَنْبَغِيْ لِجَلَالِ وَجْهِكَ وَعَظِيْمِ سُلْطَانِكَ', 'Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.', 'O my Lord, all praise is due to You as befits the Glory of Your Countenance and the Greatness of Your Authority.', 3, 'evening', 'Pleased with Allah as Lord', 'Abu Dawud 5072, Ahmad 18967', 18, 'Abdullah ibn Umar (رضي الله عنه) reported: The Prophet (ﷺ) said, "A servant said: ''Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.'' The two angels did not know how to record it, so they ascended to the heavens and said: ''Our Lord, Your servant has said something and we do not know how to record it.'' Allah — while knowing best what His servant said — asked: ''What did My servant say?'' They replied: ''He said: Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.'' Allah said to them: ''Record it as My servant said it, until he meets Me and I shall reward him for it.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_19', 'اَللّٰهُ وَلِيُّ الَّذِيْنَ آمَنُوْا يُخْرِجُهُمْ مِّنَ الظُّلُمَاتِ إِلَى النُّوْرِ ، وَالَّذِيْنَ كَفَرُوْا أَوْلِيَاؤُهُمُ الطَّاغُوْتُ يُخْرِجُوْنَهُمْ مِّنَ النُّوْرِ إِلَى الظُّلُمَاتِ ، أُولٰئِكَ أَصْحَابُ النَّارِ هُمْ فِيْهَا خَالِدُوْنَ ﴿٢٥٧﴾', 'Allahu waliyyul-ladhina amanu yukhrijuhum minaz-zulumati ilan-nur. Walladhina kafaru awliya''uhumut-taghut, yukhrijunahum minan-nuri ilaz-zulumat. Ula''ika as-habun-nar, hum fiha khalidun.', 'Allah is the ally of those who believe. He brings them out from darknesses into the light. And those who disbelieve — their allies are false deities. They take them out of the light into darknesses. Those are the companions of the Fire; they will abide eternally therein.', 1, 'evening', 'Well-being in this World and the Hereafter', 'Ibn Majah 2/323', 19, 'This verse affirms that Allah guides and protects the believers, bringing them from the darkness of ignorance into the light of faith.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_20', 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ ، عَدَدَ خَلْقِهِ ، وَرِضَا نَفْسِهِ ، وَزِنَةَ عَرْشِهِ ، وَمِدَادَ كَلِمَاتِهِ', 'SubhanAllahi wa bihamdihi, ''adada khalqihi, wa rida nafsihi, wa zinata ''arshihi, wa midada kalimatihi.', 'Allah is free from imperfection and all praise is due to Him, as numerous as all He has created, as vast as His pleasure, as limitless as the weight of His Throne, and as endless as the ink of His words.', 3, 'evening', 'SubhanAllah wa bihamdihi: Outweigh All Other Dhikr', 'Muslim 2726', 20, 'Juwairiyah (رضي الله عنها) reported: The Prophet (ﷺ) left her in the morning and came back at forenoon. She was still sitting in prayer. He said, "I said four phrases three times after leaving you, and if they were weighed against all you have said since morning, they would outweigh them: SubhanAllahi wa bihamdihi, ''adada khalqihi, wa rida nafsihi, wa zinata ''arshihi, wa midada kalimatih."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_21', 'يَا رَبِّ لَكَ الْحَمْدُ كَمَا يَنْبَغِيْ لِجَلَالِ وَجْهِكَ وَعَظِيْمِ سُلْطَانِكَ', 'Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.', 'O my Lord, all praise is due to You as befits the Glory of Your Countenance and the Greatness of Your Authority.', 3, 'evening', 'Protect Yourself From All Harm', 'Abu Dawud 5088, Tirmidhi 3388', 21, 'Abdullah ibn Umar (رضي الله عنه) reported: The Prophet (ﷺ) said, "A servant said: ''Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.'' The two angels did not know how to record it, so they ascended to the heavens and said: ''Our Lord, Your servant has said something and we do not know how to record it.'' Allah — while knowing best what His servant said — asked: ''What did My servant say?'' They replied: ''He said: Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.'' Allah said to them: ''Record it as My servant said it, until he meets Me and I shall reward him for it.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_22', 'اَللّٰهُمَّ إِنِّيْ أَعُوْذُ بِكَ أَنْ أُشْرِكَ بِكَ وَأَنَا أَعْلَمُ ، وَأَسْتَغْفِرُكَ لِمَا لَا أَعْلَمُ', 'Allahumma inni a''udhu bika an ushrika bika wa ana a''lam, wa astaghfiruka lima la a''lam.', 'O Allah, I seek refuge in You from associating anything with You knowingly, and I seek Your forgiveness for what I do not know.', 3, 'evening', 'Seek Refuge from Shirk', 'Ahmad 23119', 22, 'Ma''qil ibn Yasar (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever says ''Allahumma inni a''udhu bika an ushrika bika wa ana a''lam, wa astaghfiruka lima la a''lam'' three times, Allah will protect him from shirk."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_23', 'أَعُوْذُ بِكَلِمَاتِ اللّٰهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ.', 'Aʿūdhu bi kalimāti-l-llāhi-t-tāmmāti min sharri mā khalaq.', 'I seek protection in Allah''s perfect words from the evil of whatever He has created.', 3, 'evening', 'Protection From All Evil Wherever You Are', 'Muslim 2708, Ahmad', 23, '', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/47.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_24', 'لِلّٰهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ، وَإِنْ تُبْدُوْا مَا فِيْ أَنْفُسِكُمْ أَوْ تُخْفُوْهُ يُحَاسِبْكُمْ بِهِ اللّٰهُ ، فَيَغْفِرُ لِمَنْ يَّشَاءُ وَيُعَذِّبُ مَنْ يَّشَاءُ ، وَاللّٰهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيْرٌ ﴿٢٨٤﴾', 'Lillahi ma fis-samawati wa ma fil-ard. Wa in tubdu ma fi anfusikum aw tukhfuhu yuhasibkum bihillah. Fayaghfiru limay-yasha''u wa yu''adhdhibu may-yasha''. Wallahu ''ala kulli shay''in qadir.', 'To Allah belongs whatever is in the heavens and whatever is in the earth. Whether you show what is within yourselves or conceal it, Allah will bring you to account for it. Then He will forgive whom He wills and punish whom He wills, and Allah is over all things competent.', 1, 'evening', 'Knower of the Unseen: Protection from Evil', 'Tirmidhi 3392', 24, 'The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_25', 'آمَنَ الرَّسُوْلُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَّبِّهِ وَالْمُؤْمِنُوْنَ ، كُلٌّ آمَنَ بِاللّٰهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّنْ رُسُلِهِ ، وَقَالُوْا سَمِعْنَا وَأَطَعْنَا غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيْرُ ﴿٢٨٥﴾', 'Amanar-Rasulu bima unzila ilayhi mir-Rabbihi wal-mu''minun. Kullun amana billahi wa mala''ikatihi wa kutubihi wa rusulih, la nufarriqu bayna ahadim-mir-rusulih. Wa qalu sami''na wa ata''na, ghufranaka Rabbana wa ilaykal-masir.', 'The Messenger has believed in what was revealed to him from his Lord, and so have the believers. All of them have believed in Allah and His angels and His books and His messengers, saying, "We make no distinction between any of His messengers." And they say, "We hear and we obey. Grant us Your forgiveness, our Lord, and to You is the final destination."', 1, 'evening', 'Ya Hayyu Ya Qayyum: Rectify All My Affairs', 'Hakim 1/545', 25, 'Abu Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_26', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ ﴿١﴾

اَلْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِيْنَ ﴿٢﴾ الرَّحْمٰنِ الرَّحِيْمِ ﴿٣﴾ مَالِكِ يَوْمِ الدِّيْنِ ﴿٤﴾ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِيْنُ ﴿٥﴾ اِهْدِنَا الصِّرَاطَ الْمُسْتَقِيْمَ ﴿٦﴾ صِرَاطَ الَّذِيْنَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوْبِ عَلَيْهِمْ وَلَا الضَّالِّيْنَ ﴿٧﴾', 'Bismillahir-Rahmanir-Rahim. Al-hamdu lillahi Rabbil-''alamin. Ar-Rahmanir-Rahim. Maliki yawmid-din. Iyyaka na''budu wa iyyaka nasta''in. Ihdinas-siratal-mustaqim. Siratal-ladhina an''amta ''alayhim, ghayril-maghdubi ''alayhim wa lad-dallin.', 'In the name of Allah, the Most Gracious, the Most Merciful. All praise is due to Allah, Lord of the worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us to the straight path — the path of those upon whom You have bestowed favor, not of those who have evoked Your anger or of those who are astray.', 1, 'evening', 'Sayyid al-Istighfar: The Best Forgiveness', 'Bukhari 6306', 26, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Allah said: ''I have divided prayer between Myself and My servant into two halves, and My servant shall have what he has asked for.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_27', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ هُوَ اللّٰهُ أَحَدٌ ﴿١﴾ اَللّٰهُ الصَّمَدُ ﴿٢﴾ لَمْ يَلِدْ وَلَمْ يُوْلَدْ ﴿٣﴾ وَلَمْ يَكُنْ لَّهُ كُفُوًا أَحَدٌ ﴿٤﴾', 'Bismillahir-Rahmanir-Rahim. Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakul-lahu kufuwan ahad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 4, 'evening', 'Get Yourself Freed from the Hellfire', 'Abu Dawud 5069', 27, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to me, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn (Al-Falaq and An-Nas) three times in the morning and evening — they will suffice you against everything."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_28', 'اَللّٰهُمَّ إِنِّيْ أَمْسَيْتُ مِنْكَ فِيْ نِعْمَةٍ وَعَافِيَةٍ وَسِتْرٍ ، فَأَتِمَّ عَلَيَّ نِعْمَتَكَ وَعَافِيَتَكَ وَسِتْرَكَ فِي الدُّنْيَا وَالْآخِرَةِ', 'Allahumma inni amsaitu minka fi ni''matin wa ''afiyatin wa sitr, fa atimma ''alayya ni''mataka wa ''afiyataka wa sitraka fid-dunya wal-akhirah.', 'O Allah, I have entered the evening receiving from You blessings, well-being and concealment (of my faults). So complete Your blessings upon me, Your well-being, and Your concealment in this world and the Hereafter.', 3, 'evening', 'Ask Allah For Good Health and Protection', 'Abu Dawud 5090', 28, 'Abdullah ibn Umar (رضي الله عنه) reported: The Messenger of Allah (ﷺ) never used to leave this supplication in the morning and evening, asking Allah to complete His blessings, well-being, and concealment of faults upon him in this world and the Hereafter.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_29', 'لَا يُكَلِّفُ اللّٰهُ نَفْسًا إِلَّا وُسْعَهَا ، لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ، رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِيْنَا أَوْ أَخْطَأْنَا ، رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِيْنَ مِنْ قَبْلِنَا ، رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ، وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ، أَنْتَ مَوْلَانَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِيْنَ ﴿٢٨٦﴾', 'La yukallifullahu nafsan illa wus''aha. Laha ma kasabat wa ''alayha maktasabat. Rabbana la tu''akhidhna in nasina aw akhta''na. Rabbana wa la tahmil ''alayna isran kama hamaltahu ''alal-ladhina min qablina. Rabbana wa la tuhammilna ma la taqata lana bih. Wa''fu ''anna waghfir lana warhamna. Anta mawlana fansurna ''alal-qawmil-kafirin.', 'Allah does not burden a soul beyond that it can bear. It will have the consequence of what good it has gained, and it will bear the consequence of what evil it has earned. "Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people."', 7, 'evening', 'Allah Will Suffice You in Everything', 'Abu Dawud 5081', 29, 'Abu Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him." Muslim reported that when this verse was revealed, Allah said after each supplication in it: "I have done so."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_30', 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ ، عَدَدَ خَلْقِهِ ، وَرِضَا نَفْسِهِ ، وَزِنَةَ عَرْشِهِ ، وَمِدَادَ كَلِمَاتِهِ', 'SubhanAllahi wa bihamdihi, ''adada khalqihi, wa rida nafsihi, wa zinata ''arshihi, wa midada kalimatihi.', 'Allah is free from imperfection and all praise is due to Him, as numerous as all He has created, as vast as His pleasure, as limitless as the weight of His Throne, and as endless as the ink of His words.', 100, 'evening', 'An Unparalleled Reward', 'Bukhari 6403, Muslim', 30, 'Juwairiyah (رضي الله عنها) reported: The Prophet (ﷺ) left her in the morning and came back at forenoon. She was still sitting in prayer. He said, "I said four phrases three times after leaving you, and if they were weighed against all you have said since morning, they would outweigh them: SubhanAllahi wa bihamdihi, ''adada khalqihi, wa rida nafsihi, wa zinata ''arshihi, wa midada kalimatih."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_31', 'اَللّٰهُ وَلِيُّ الَّذِيْنَ آمَنُوْا يُخْرِجُهُمْ مِّنَ الظُّلُمَاتِ إِلَى النُّوْرِ ، وَالَّذِيْنَ كَفَرُوْا أَوْلِيَاؤُهُمُ الطَّاغُوْتُ يُخْرِجُوْنَهُمْ مِّنَ النُّوْرِ إِلَى الظُّلُمَاتِ ، أُولٰئِكَ أَصْحَابُ النَّارِ هُمْ فِيْهَا خَالِدُوْنَ ﴿٢٥٧﴾', 'Allahu waliyyul-ladhina amanu yukhrijuhum minaz-zulumati ilan-nur. Walladhina kafaru awliya''uhumut-taghut, yukhrijunahum minan-nuri ilaz-zulumat. Ula''ika as-habun-nar, hum fiha khalidun.', 'Allah is the ally of those who believe. He brings them out from darknesses into the light. And those who disbelieve — their allies are false deities. They take them out of the light into darknesses. Those are the companions of the Fire; they will abide eternally therein.', 100, 'evening', 'Get Your Sins Forgiven', 'Bukhari 6405, Muslim 2692', 31, 'This verse affirms that Allah guides and protects the believers, bringing them from the darkness of ignorance into the light of faith.');

-- Verify
SELECT id, sort_order, reward, recommended_count FROM azkar_items WHERE category_id = 'evening' ORDER BY sort_order;
