-- Evening Azkar Migration: duaandazkar.com app exact 32-item sequence
-- Generated: 2026-04-08T07:35:24.391Z
-- Run this in Supabase SQL Editor

-- Step 1: Delete ALL old evening azkar
DELETE FROM azkar_items WHERE category_id = 'evening';
DELETE FROM azkar_items WHERE id LIKE 'evening_%';
DELETE FROM azkar_items WHERE id LIKE 'evening_fixed_%';
DELETE FROM azkar_items WHERE id LIKE 'evening_lwa_%';

-- Step 2: Insert 32 evening azkar
INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_1', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

اَلْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِيْنَ ، الرَّحْمٰنِ الرَّحِيْمِ ، مَالِكِ يَوْمِ الدِّيْنِ ، إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِيْنُ ، اِهْدِنَا الصِّرَاطَ الْمُسْتَقِيْمَ ، صِرَاطَ الَّذِيْنَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوْبِ عَلَيْهِمْ وَلَا الضَّالِّيْنَ', 'Bismillahir-Rahmanir-Rahim. Al-hamdu lillahi Rabbil-''alamin. Ar-Rahmanir-Rahim. Maliki yawmid-din. Iyyaka na''budu wa iyyaka nasta''in. Ihdinas-siratal-mustaqim. Siratal-ladhina an''amta ''alayhim, ghayril-maghdubi ''alayhim wa lad-dallin.', 'In the name of Allah, the Most Gracious, the Most Merciful. All praise is due to Allah, Lord of the worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us to the straight path — the path of those upon whom You have bestowed favor, not of those who have evoked Your anger or of those who are astray.', 1, 'evening', 'Al Fateha | Sahih Muslim 395a', 'Quran 1:1-7 | Sahih Muslim 395', 1, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Allah the Almighty said: ''I have divided prayer between Myself and My servant into two halves, and My servant shall have what he has asked for. When the servant says Al-hamdu lillahi Rabbil-''alamin, Allah says: My servant has praised Me. When he says Ar-Rahmanir-Rahim, Allah says: My servant has extolled Me. When he says Maliki yawmid-din, Allah says: My servant has glorified Me. When he says Iyyaka na''budu wa iyyaka nasta''in, Allah says: This is between Me and My servant, and My servant shall have what he has asked for. When he says Ihdinas-siratal-mustaqim, Allah says: This is for My servant, and My servant shall have what he has asked for.''" (Sahih Muslim 395a)', 'https://download.quranicaudio.com/qdc/mishari_al_afasy/murattal/1.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_2', 'الٓمٓ ، ذٰلِكَ الْكِتَابُ لَا رَيْبَ فِيْهِ هُدًى لِّلْمُتَّقِيْنَ ، الَّذِيْنَ يُؤْمِنُوْنَ بِالْغَيْبِ وَيُقِيْمُوْنَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُوْنَ ، وَالَّذِيْنَ يُؤْمِنُوْنَ بِمَا أُنْزِلَ إِلَيْكَ وَمَا أُنْزِلَ مِنْ قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوْقِنُوْنَ ، أُولٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ وَأُولٰئِكَ هُمُ الْمُفْلِحُوْنَ', 'Alif-Lam-Mim. Dhalikal-kitabu la rayba fih, hudal-lil-muttaqin. Alladhina yu''minuna bil-ghaybi wa yuqimunas-salata wa mimma razaqnahum yunfiqun. Walladhina yu''minuna bima unzila ilayka wa ma unzila min qablik, wa bil-akhirati hum yuqinun. Ula''ika ''ala hudam-mir-Rabbihim wa ula''ika humul-muflihun.', 'Alif, Lam, Mim. This is the Book about which there is no doubt, a guidance for those conscious of Allah — who believe in the unseen, establish prayer, and spend out of what We have provided for them, and who believe in what has been revealed to you and what was revealed before you, and of the Hereafter they are certain. Those are upon guidance from their Lord, and it is those who are the successful.', 1, 'evening', 'Alif Laam Meem | Ad-Darimi', 'Quran 2:1-5 | Ad-Darimi', 2, 'Abdullah ibn Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever recites the first four verses of Surah Al-Baqarah, Ayat al-Kursi, and the last three verses of Surah Al-Baqarah — the Shaytan will not come near him or to his family, nor will he be touched by anything that he dislikes." (Ad-Darimi)');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_3', 'أَعُوْذُ بِاللّٰهِ مِنَ الشَّيْطَانِ الرَّجِيْمِ.
اَللّٰهُ لَآ إِلٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّوْمُ ، لَا تَأْخُذُهُۥ سِنَةٌ وَّلَا نَوْمٌ ، لَهُ مَا فِى السَّمٰـوٰتِ وَمَا فِى الْأَرْضِ ، مَنْ ذَا الَّذِىْ يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِۦ ، يَعْلَمُ مَا بَيْنَ أَيْدِيْهِمْ وَمَا خَلْفَهُمْ ، وَلَا يُحِيْطُوْنَ بِشَىْءٍ مِّنْ عِلْمِهِٓ إِلَّا بِمَا شَآءَ ، وَسِعَ كُرْسِيُّهُ السَّمٰـوٰتِ وَالْأَرْضَ، وَلَا يَئُوْدُهُۥ حِفْظُهُمَا ، وَهُوَ الْعَلِىُّ الْعَظِيْمُ.', 'Aʿūdhu bi-llāhi mina-sh-Shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa-l-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatuw-wa lā nawm, lahū mā fi-s-samāwāti wa mā fi-l-arḍ, man dhā''lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''im-min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā wa Huwa-l-ʿAlliyu-l-ʿAẓīm.', 'I seek the protection of Allah from the accursed Shayṭān. Allah, there is no god worthy of worship but He, the Ever Living, The Sustainer of all. Neither drowsiness overtakes Him nor sleep. To Him Alone belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except with His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursī extends over the heavens and the earth, and their preservation does not tire Him. And He is the Most High, the Magnificent. (2:255)', 1, 'evening', 'Ayatul Kursi | Al-Bukhari 5010', 'Quran 2:255 | Al-Bukhari 5010', 3, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) entrusted me to guard the Zakat revenue of Ramadan. Someone came and began stealing from the food. He said, "When you go to your bed, recite Ayat al-Kursi, for then there will be a guard from Allah who will protect you all night long, and Satan will not be able to come near you till dawn." The Prophet (ﷺ) said, "He told you the truth, although he is a liar — that was the Shaytan." (Al-Bukhari 5010)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/25.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_4', 'لَا إِكْرَاهَ فِي الدِّيْنِ ، قَدْ تَبَيَّنَ الرُّشْدُ مِنَ الْغَيِّ ، فَمَنْ يَّكْفُرْ بِالطَّاغُوْتِ وَيُؤْمِنْ بِاللّٰهِ فَقَدِ اسْتَمْسَكَ بِالْعُرْوَةِ الْوُثْقَىٰ لَا انْفِصَامَ لَهَا ، وَاللّٰهُ سَمِيْعٌ عَلِيْمٌ', 'La ikraha fid-din, qad tabayyanar-rushdu minal-ghayy. Faman yakfur bit-taghuti wa yu''min billahi faqadis-tamsaka bil-''urwatil-wuthqa lanfisama laha. Wallahu Sami''un ''Alim.', 'There shall be no compulsion in the religion. The right course has become clear from the wrong. So whoever disbelieves in false deities and believes in Allah has grasped the most trustworthy handhold with no break in it. And Allah is Hearing and Knowing.', 1, 'evening', 'La Ikraha fid-Deen | Ad-Darimi', 'Quran 2:256 | Ad-Darimi', 4, 'This verse is part of the ten verses from Surah Al-Baqarah that the Prophet (ﷺ) recommended. Whoever recites them, the Shaytan will not enter his house that night. (Ad-Darimi)', 'https://audio.qurancdn.com/Alafasy/mp3/002256.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_5', 'اَللّٰهُ وَلِيُّ الَّذِيْنَ آمَنُوْا يُخْرِجُهُمْ مِّنَ الظُّلُمَاتِ إِلَى النُّوْرِ ، وَالَّذِيْنَ كَفَرُوْا أَوْلِيَاؤُهُمُ الطَّاغُوْتُ يُخْرِجُوْنَهُمْ مِّنَ النُّوْرِ إِلَى الظُّلُمَاتِ ، أُولٰئِكَ أَصْحَابُ النَّارِ هُمْ فِيْهَا خَالِدُوْنَ', 'Allahu waliyyul-ladhina amanu yukhrijuhum minaz-zulumati ilan-nur. Walladhina kafaru awliya''uhumut-taghut, yukhrijunahum minan-nuri ilaz-zulumat. Ula''ika as-habun-nar, hum fiha khalidun.', 'Allah is the ally of those who believe. He brings them out from darknesses into the light. And those who disbelieve — their allies are false deities. They take them out of the light into darknesses. Those are the companions of the Fire; they will abide eternally therein.', 1, 'evening', 'Allah is the Ally of the Believers | Ad-Darimi', 'Quran 2:257 | Ad-Darimi', 5, 'This verse is part of the ten verses from Surah Al-Baqarah. Whoever recites them, the Shaytan will not enter his house that night. (Ad-Darimi)', 'https://audio.qurancdn.com/Alafasy/mp3/002257.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_6', 'لِلّٰهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ، وَإِنْ تُبْدُوْا مَا فِيْ أَنْفُسِكُمْ أَوْ تُخْفُوْهُ يُحَاسِبْكُمْ بِهِ اللّٰهُ ، فَيَغْفِرُ لِمَنْ يَّشَاءُ وَيُعَذِّبُ مَنْ يَّشَاءُ ، وَاللّٰهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيْرٌ', 'Lillahi ma fis-samawati wa ma fil-ard. Wa in tubdu ma fi anfusikum aw tukhfuhu yuhasibkum bihillah. Fayaghfiru limay-yasha''u wa yu''adhdhibu may-yasha''. Wallahu ''ala kulli shay''in qadir.', 'To Allah belongs whatever is in the heavens and whatever is in the earth. Whether you show what is within yourselves or conceal it, Allah will bring you to account for it. Then He will forgive whom He wills and punish whom He wills, and Allah is over all things competent.', 1, 'evening', 'To Allah Belongs All | Al-Bukhari 4723', 'Quran 2:284 | Al-Bukhari 4723', 6, 'Abu Mas''ud al-Badri (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, it will suffice him." (Al-Bukhari 4723)', 'https://audio.qurancdn.com/Alafasy/mp3/002284.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_7', 'آمَنَ الرَّسُوْلُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَّبِّهِ وَالْمُؤْمِنُوْنَ ، كُلٌّ آمَنَ بِاللّٰهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّنْ رُسُلِهِ ، وَقَالُوْا سَمِعْنَا وَأَطَعْنَا غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيْرُ', 'Amanar-Rasulu bima unzila ilayhi mir-Rabbihi wal-mu''minun. Kullun amana billahi wa mala''ikatihi wa kutubihi wa rusulih, la nufarriqu bayna ahadim-mir-rusulih. Wa qalu sami''na wa ata''na, ghufranaka Rabbana wa ilaykal-masir.', 'The Messenger has believed in what was revealed to him from his Lord, and so have the believers. All of them have believed in Allah and His angels and His books and His messengers, saying, "We make no distinction between any of His messengers." And they say, "We hear and we obey. Grant us Your forgiveness, our Lord, and to You is the final destination."', 1, 'evening', 'The Messenger Has Believed | Al-Bukhari 4723', 'Quran 2:285 | Al-Bukhari 4723', 7, 'Abu Mas''ud al-Badri (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, it will suffice him." (Al-Bukhari 4723, Sahih Muslim 807)', 'https://audio.qurancdn.com/Alafasy/mp3/002285.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_8', 'لَا يُكَلِّفُ اللّٰهُ نَفْسًا إِلَّا وُسْعَهَا ، لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ، رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِيْنَا أَوْ أَخْطَأْنَا ، رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِيْنَ مِنْ قَبْلِنَا ، رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ، وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ، أَنْتَ مَوْلَانَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِيْنَ', 'La yukallifullahu nafsan illa wus''aha. Laha ma kasabat wa ''alayha maktasabat. Rabbana la tu''akhidhna in nasina aw akhta''na. Rabbana wa la tahmil ''alayna isran kama hamaltahu ''alal-ladhina min qablina. Rabbana wa la tuhammilna ma la taqata lana bih. Wa''fu ''anna waghfir lana warhamna. Anta mawlana fansurna ''alal-qawmil-kafirin.', 'Allah does not burden a soul beyond that it can bear. It will have the consequence of what good it has gained, and it will bear the consequence of what evil it has earned. "Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people."', 1, 'evening', 'Allah Does Not Burden a Soul | Sahih Muslim 807', 'Quran 2:286 | Sahih Muslim 807', 8, 'Abu Mas''ud al-Badri (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, it will suffice him." When this verse was revealed, after each supplication in it, Allah said: "I have done so." (Sahih Muslim 807)', 'https://audio.qurancdn.com/Alafasy/mp3/002286.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_9', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ هُوَ اللّٰهُ أَحَدٌ ، اَللّٰهُ الصَّمَدُ ، لَمْ يَلِدْ وَلَمْ يُوْلَدْ ، وَلَمْ يَكُنْ لَّهُ كُفُوًا أَحَدٌ', 'Bismillahir-Rahmanir-Rahim. Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakul-lahu kufuwan ahad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 3, 'evening', 'Surah Al-Ikhlas | Abu Dawud 5082', 'Quran 112 | Abu Dawud 5082', 9, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn three times at dawn and dusk. It will suffice you in all respects." (Abu Dawud 5082, At-Tirmidhi 3575)', 'https://download.quranicaudio.com/qdc/mishari_al_afasy/murattal/112.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_10', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ أَعُوْذُ بِرَبِّ الْفَلَقِ ، مِنْ شَرِّ مَا خَلَقَ ، وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ، وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ، وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ', 'Bismillahir-Rahmanir-Rahim. Qul a''udhu bi Rabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-''uqad. Wa min sharri hasidin idha hasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 3, 'evening', 'Surah Al-Falaq | At-Tirmidhi 3575', 'Quran 113 | At-Tirmidhi 3575', 10, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn three times at dawn and dusk. It will suffice you in all respects." (Abu Dawud 5082, At-Tirmidhi 3575)', 'https://download.quranicaudio.com/qdc/mishari_al_afasy/murattal/113.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_11', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ أَعُوْذُ بِرَبِّ النَّاسِ ، مَلِكِ النَّاسِ ، إِلٰهِ النَّاسِ ، مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ، الَّذِيْ يُوَسْوِسُ فِيْ صُدُوْرِ النَّاسِ ، مِنَ الْجِنَّةِ وَالنَّاسِ', 'Bismillahir-Rahmanir-Rahim. Qul a''udhu bi Rabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer — who whispers in the breasts of mankind — from among the jinn and mankind."', 3, 'evening', 'Surah An-Nas | At-Tirmidhi 3575', 'Quran 114 | At-Tirmidhi 3575', 11, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn three times at dawn and dusk. It will suffice you in all respects." (Abu Dawud 5082, At-Tirmidhi 3575)', 'https://download.quranicaudio.com/qdc/mishari_al_afasy/murattal/114.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_12', 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلّٰهِ وَالْحَمْدُ لِلّٰهِ ، لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيْكَ لَهُ ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيْرٌ ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِيْ هٰذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا ، وَأَعُوْذُ بِكَ مِنْ شَرِّ مَا فِيْ هٰذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا ، رَبِّ أَعُوْذُ بِكَ مِنَ الْكَسَلِ وَسُوْءِ الْكِبَرِ ، رَبِّ أَعُوْذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ.', 'Amsaynā wa amsa-l-mulku li-llāh, wa-l-ḥamdu li-llāh, lā ilāha illa-llāhu waḥdahū lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamd, wa huwa ʿalā kulli shay''in Qadīr, Rabbi as''aluka khayra mā fī hādhihi-l-laylati wa khayra mā baʿdah, wa aʿūdhu bika min sharri mā fī hādhihi-l-laylati wa sharri mā baʿdah. Rabbi aʿūdhu bika mina-l-kasali wa sū''i-l-kibar, Rabbi aʿūdhu bika min ʿadhābin fi-n-nāri wa ʿadhābin fi-l-qabr.', 'We have entered the evening and at this very time the whole kingdom belongs to Allah. All praise is due to Allah. There is no god worthy of worship except Allah, the One; He has no partner with Him. The entire kingdom belongs solely to Him, to Him is all praise due, and He is All-Powerful over everything. My Lord, I ask You for the good that is in this night and the good that follows it, and I seek Your protection from the evil that is in this night and from the evil that follows it. My Lord, I seek Your protection from laziness and the misery of old age. My Lord, I seek Your protection from the torment of the Hell-fire and the punishment of the grave.', 1, 'evening', 'Dominion Belongs to Allah | Sahih Muslim 2723', 'Sahih Muslim 2723', 12, 'Abdullah ibn Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) used to say in the evening: "Amsaina wa amsal-mulku lillah..."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/35.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_13', 'أَمْسَيْنَا عَلَىٰ فِطْرَةِ الْإِسْلَامِ ، وَعَلَىٰ كَلِمَةِ الْإِخْلَاصِ ، وَعَلَىٰ دِيْنِ نَبِيِّنَا مُحَمَّدٍ ، وَعَلَىٰ مِلَّةِ أَبِيْنَا إِبْرَاهِيْمَ حَنِيْفًا مُّسْلِمًا وَّمَا كَانَ مِنَ الْمُشْرِكِيْنَ.', 'Amsaynā ʿalā fiṭrati-l-islām, wa ʿalā kalimati-l-ikhlāṣ, wa ʿalā dīni Nabiyyinā Muḥammadin ṣallallāhu ʿalayhi wa sallam, wa ʿalā millati abīnā Ibrāhīma ḥanīfam-muslima, wa mā kāna mina-l-mushrikīn.', 'We have entered the evening upon the natural religion of Islam, the statement of pure faith (i.e. Shahādah), the religion of our Prophet Muhammad ﷺ and upon the way of our father Ibrāhīm, who turned away from all that is false, having surrendered to Allah, and he was not of the polytheists.', 1, 'evening', 'Upon the Fitrah of Islam | Ahmad 15367', 'Ahmad 15367', 13, 'This day I have perfected for you your religion and completed my favour upon you and have approved for you Islam as religion. (Al-Maa''idah 5:3) Abdullah bin Abdur Rahman bin Abza رضي الله عنه reported from his father, who said: When the Prophet ﷺ woke up in the morning, he would say: "This morning we affirm our adherence to the path of Islam and the word of sincerity and the way of our Prophet Muhammad (peace and blessings of Allah be upon him) and the religion of our father Ibrahim, pure monotheism and submission to Allah, and he was not of those who associate others with Allah.” (Sunan ad-Darimi 2605)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/33.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_14', 'اَللّٰهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوْتُ وَإِلَيْكَ الْمَصِيْرُ.', 'Allāhumma bika amsaynā wa bika aṣbaḥnā wa bika naḥyā wa bika namūtu wa ilayka-l-maṣīr.', 'O Allah, by You we have entered the evening and by You we enter upon the morning. By You, we live and we die, and to You is the return.', 1, 'evening', 'By Your Leave | At-Tirmidhi 3391', 'At-Tirmidhi 3391', 14, 'Narrated Abu Hurayrah رضي الله عنه : The Prophet ﷺ used to say in the morning: "O Allah, by Thee we come to the morning, by Thee we come to the evening, by Thee are we resurrected." In the evening he would say: "O Allah, by Thee we come to the evening, by Thee we die, and to Thee are we resurrected." (Sunan Abi Dawud 5068) Abu Hurairah (ra) said رضي الله عنه: The Messenger of Allah ﷺ used to teach his Companions, saying: “When one of you reached the morning, then let him say: ‘O Allah, by You we enter the morning, and by You we enter the evening, and be You we live, and by You we died, and to You is the Return (Allahumma bika aṣbahna wa bika amsaina wa bika nahya wa bika namūtu wa ilaikal-maṣīr). And when he reaches the evening let him say: ‘O Allah, by You we enter the evening, and by You we enter the morning, and by You we live, and by You we die, and to You is the Resurrection (Allahumma bika amsaina wa bika aṣbahna wa bika nahya wa bika namūtu wa ilaikan-maseer).” (Jami` at-Tirmidhi 3391)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/38.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_15', 'اَللّٰهُمَّ إِنِّيْ أَمْسَيْتُ مِنْكَ فِيْ نِعْمَةٍ وَعَافِيَةٍ وَسِتْرٍ ، فَأَتِمَّ عَلَيَّ نِعْمَتَكَ وَعَافِيَتَكَ وَسِتْرَكَ فِي الدُّنْيَا وَالْآخِرَةِ', 'Allahumma inni amsaitu minka fi ni''matin wa ''afiyatin wa sitr, fa atimma ''alayya ni''mataka wa ''afiyataka wa sitraka fid-dunya wal-akhirah.', 'O Allah, I have entered the evening receiving from You blessings, well-being and concealment of my faults. So complete Your blessings upon me, Your well-being, and Your concealment in this world and the Hereafter.', 3, 'evening', 'Blessings, Well-being and Concealment', 'Ibn al-Sunni 41', 15, 'The Messenger of Allah (ﷺ) never used to leave this supplication in the morning and evening.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_16', 'اَللّٰهُمَّ مَا أَمْسَىٰ بِيْ مِنْ نِّعْمَةٍ أَوْ بِأَحَدٍ مِّنْ خَلْقِكَ ، فَمِنْكَ وَحْدَكَ لَا شَرِيْكَ لَكَ ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ.', 'Allāhumma mā amsā bī min niʿmatin aw bi-aḥadin min khalqik, fa-minka waḥdaka lā sharīka lak, fa laka-l-ḥamdu wa laka-sh-shukr.', 'O Allah, all the favours that I or anyone from Your creation has received in the evening, are from You Alone. You have no partner. To You Alone belong all praise and all thanks.', 1, 'evening', 'Fulfil Obligation of Gratitude | Abu Dawud 5073', 'Abu Dawud 5073', 16, 'Abdullah ibn Ghannam (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever says: ''Allahumma ma amsa bi min ni''matin...'' — he has fulfilled his obligation of giving thanks for that night." (Abu Dawud 5073)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/32.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('evening_17', 'يَا رَبِّ لَكَ الْحَمْدُ كَمَا يَنْبَغِيْ لِجَلَالِ وَجْهِكَ وَعَظِيْمِ سُلْطَانِكَ', 'Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.', 'O my Lord, all praise is due to You as befits the Glory of Your Countenance and the Greatness of Your Authority.', 1, 'evening', 'Praise Befitting Divine Greatness', 'Ibn Majah 3801', 17, 'The Prophet (ﷺ) said, "A servant said this and the angels did not know how to record it. Allah said: ''Record it as My servant said it, until he meets Me and I shall reward him for it.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_18', 'رَضِيْتُ بِاللّٰهِ رَبًّا ، وَبِالْإِسْلَامِ دِيْنًا ، وَبِمُحَمَّدٍ نَّبِيًّا.', 'Raḍītu bi-llāhi Rabbā, wa bi-l-islāmi dīnā, wa bi Muḥammadin-Nabiyyā.', 'I am pleased with Allah as my Lord, with Islām as my religion and with Muhammad ﷺ as my Prophet.', 3, 'evening', 'Pleased with Allah | Ahmad 18967', 'Abu Dawud 5072 | Ahmad 18967', 18, 'Abu Sallam (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever says in the morning and evening: ''Raditu billahi Rabba, wa bil-Islami dina, wa bi-Muhammadin nabiyya'' — Allah has promised that He will please him on the Day of Resurrection." (Abu Dawud 5072, Ahmad 18967)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/41.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_19', 'اَللّٰهُمَّ إِنِّيْ أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ ، اَللّٰهُمَّ إِنِّيْ أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِيْ دِيْنِيْ وَدُنْيَايَ وَأَهْلِيْ وَمَالِيْ ، اَللّٰهُمَّ اسْتُرْ عَوْرَاتِيْ وَآمِنْ رَوْعَاتِيْ ، اَللّٰهُمَّ احْفَظْنِيْ مِنْ بَيْنِ يَدَيَّ ، وَمِنْ خَلْفِيْ ، وَعَنْ يَّمِيْنِيْ ، وَعَنْ شِمَالِيْ ، وَمِنْ فَوْقِيْ ، وَأَعُوْذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِيْ.', 'Allāhumma innī as''aluka-l-ʿāfiyata fi-d-dunyā wa-l-ākhirah. Allāhumma innī as''aluka-l-ʿafwa wa-l-ʿāfiyata fī dīnī wa dunyāya wa ahlī wa mālī, Allāhumma-stur ʿawrātī wa āmin rawʿātī. Allāhumma-ḥfaẓnī mim bayni yadayya wa min khalfī, wa ʿay-yamīnī wa ʿan shimālī wa min fawqī, wa aʿūdhu bi-ʿaẓamatika an ughtāla min taḥtī.', 'O Allah, I ask You for well-being in this world and the next. O Allah, I ask You for forgiveness and well-being in my religion, in my worldly affairs, in my family and in my wealth. O Allah, conceal my faults and calm my fears. O Allah, guard me from in front of me and behind me, from my right, and from my left, and from above me. I seek protection in Your Greatness from being unexpectedly destroyed from beneath me.', 1, 'evening', 'Well-being in Both Worlds | Abu Dawud 5074', 'Abu Dawud 5074', 19, 'Abdullah ibn Umar (رضي الله عنهما) reported: The Messenger of Allah (ﷺ) never failed to say these supplications in the morning and evening. (Abu Dawud 5074)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/29.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_20', 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ ، عَدَدَ خَلْقِهِ ، وَرِضَا نَفْسِهِ ، وَزِنَةَ عَرْشِهِ ، وَمِدَادَ كَلِمَاتِهِ', 'SubhanAllahi wa bihamdihi, ''adada khalqihi, wa rida nafsihi, wa zinata ''arshihi, wa midada kalimatihi.', 'Allah is free from imperfection and all praise is due to Him, as numerous as all He has created, as vast as His pleasure, as limitless as the weight of His Throne, and as endless as the ink of His words.', 3, 'evening', 'Outweigh All Other Dhikr | Sahih Muslim 2726', 'Sahih Muslim 2726', 20, 'Juwairiyah (رضي الله عنها) reported: The Prophet (ﷺ) said, "I said four phrases three times and if they were weighed against all you have said since morning, they would outweigh them."', 'https://www.hisnmuslim.com/audio/ar/94.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_21', 'بِسْمِ اللّٰهِ الَّذِيْ لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ ، وَهُوَ السَّمِيْعُ الْعَلِيْمُ.', 'Bismi-llāhi-lladhī lā yaḍurru maʿsmihi shay''un fi-l-arḍi wa lā fi-s-samā'', wa Huwa-s-Samīʿu-l-ʿAlīm.', 'In the Name of Allah, with whose Name nothing can harm in the earth nor in the sky. He is The All-Hearing and All-Knowing.', 3, 'evening', 'Protect From All Harm | At-Tirmidhi 3388', 'Abu Dawud 5088 | At-Tirmidhi 3388', 21, 'Uthman ibn Affan (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "No servant says this three times in the morning and evening, and anything will harm him." (At-Tirmidhi 3388)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/42.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_22', 'اَللّٰهُمَّ إِنِّيْ أَعُوْذُ بِكَ أَنْ أُشْرِكَ بِكَ وَأَنَا أَعْلَمُ ، وَأَسْتَغْفِرُكَ لِمَا لَا أَعْلَمُ', 'Allahumma inni a''udhu bika an ushrika bika wa ana a''lam, wa astaghfiruka lima la a''lam.', 'O Allah, I seek refuge in You from associating anything with You knowingly, and I seek Your forgiveness for what I do not know.', 3, 'evening', 'Seek Refuge from Shirk | Sahih Al-Jaami 2876', 'Ahmad 23119 | Sahih Al-Jaami 2876', 22, 'Ma''qil ibn Yasar (رضي الله عنه) reported: The Prophet (ﷺ) said, "Shirk among you is more subtle than the sound of footsteps of an ant on a rock. Shall I not teach you something which, if you say it, will rid you of both minor and major shirk? Say: ''Allahumma inni a''udhu bika an ushrika bika wa ana a''lam, wa astaghfiruka lima la a''lam.''" (Sahih Al-Jaami 2876)', 'https://salafiaudio.files.wordpress.com/2015/07/hisn-al-muslim-audio-dua-203.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_23', 'أَعُوْذُ بِكَلِمَاتِ اللّٰهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ.', 'Aʿūdhu bi kalimāti-l-llāhi-t-tāmmāti min sharri mā khalaq.', 'I seek protection in Allah''s perfect words from the evil of whatever He has created.', 3, 'evening', 'Protection From All Evil | Sahih Muslim 2709', 'Sahih Muslim 2709', 23, 'Khawlah bint Hakim (رضي الله عنها) reported: The Messenger of Allah (ﷺ) said, "If anyone lands at a place and says: ''A''udhu bi kalimatillahit-tammati min sharri ma khalaq'' — nothing will harm him until he leaves that place." (Sahih Muslim 2709)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/47.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_24', 'اَللّٰهُمَّ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ ، فَاطِرَ السَّمٰوَاتِ وَالْأَرْضِ ، رَبَّ كُلِّ شَيْءٍ وَمَلِيْكَهُ ، أَشْهَدُ أَنْ لَّا إِلٰهَ إِلَّا أَنْتَ ، أَعُوْذُ بِكَ مِنْ شَرِّ نَفْسِيْ ، وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ ، وَأَنْ أَقْتَرِفَ عَلَىٰ نَفْسِيْ سُوْءًا ، أَوْ أَجُرَّهُ إِلَىٰ مُسْلِمٍ.', 'Allāhumma ʿālima-l-ghaybi wa-sh-shahādah, fāṭir-as-samāwāti wa-l-arḍi, rabba kulli shay''iw-wa malīkah, ash-hadu al-lā ilāha illā Anta, aʿūdhu bika min sharri nafsī wa min sharri-sh-shayṭāni wa shirkihī wa an aqtarifa ʿalā nafsī sū''an aw ajurrahū ilā muslim.', 'O Allah, Knower of the unseen and the seen, Creator of the heavens and the earth, the Lord and Sovereign of everything; I bear witness that there is no god worthy of worship but You. I seek Your protection from the evil of my own self, from the evil of Shayṭān and from the evil of polytheism to which he calls, and from inflicting evil on myself, or bringing it upon a Muslim.', 1, 'evening', 'Knower of the Unseen | At-Tirmidhi 3392', 'At-Tirmidhi 3392', 24, 'Reference: Tirmidhī 3392, 3529', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/30.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_25', 'يَا حَيُّ يَا قَيُّوْمُ ، بِرَحْمَتِكَ أَسْتَغِيْثُ ، أَصْلِحْ لِيْ شَأْنِيْ كُلَّهُ ، وَلَا تَكِلْنِيْ إِلَىٰ نَفْسِيْ طَرْفَةَ عَيْنٍ.', 'Yā Ḥayyu yā Qayyūm, bi-raḥmatika astaghīth, aṣliḥ lī sha''nī kullah, wa lā takilnī ilā nafsī ṭarfata ʿayn.', 'O The Ever Living, The Sustainer of all; I seek assistance through Your mercy. Rectify all of my affairs and do not entrust me to myself for the blink of an eye.', 1, 'evening', 'Ya Hayyu Ya Qayyum | Mustadrak Al-Hakim', 'Hakim 1/545', 25, 'Anas ibn Malik (رضي الله عنه) reported: The Prophet (ﷺ) said to Fatimah, "Say in the morning and evening: ''Ya Hayyu ya Qayyumu birahmatika astaghith...''"', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/31.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_26', 'اَللّٰهُمَّ أَنْتَ رَبِّيْ لَا إِلٰهَ إِلَّا أَنْتَ ، خَلَقْتَنِيْ وَأَنَا عَبْدُكَ ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ ، أَعُوْذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ ، أَبُوْءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوْءُ لَكَ بِذَنْبِيْ ، فَاغْفِرْ لِيْ فَإِنَّهُ لَا يَغْفِرُ الذُّنُوْبَ إِلَّا أَنْتَ.', 'Allāhumma Anta Rabbī, lā ilāha illā Ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika mā''staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi niʿmatika ʿalayya wa abū''u laka bi-dhambī fa-ghfir lī fa-innahū lā yaghfiru-dh-dhunūba illā Ant.', 'O Allah, You are my Lord. There is no god worthy of worship except You. You have created me, and I am Your slave, and I am under Your covenant and pledge (to fulfil it) to the best of my ability. I seek Your protection from the evil that I have done. I acknowledge the favours that You have bestowed upon me, and I admit my sins. Forgive me, for none forgives sins but You.', 1, 'evening', 'Sayyid al-Istighfar | Al-Bukhari 6306', 'Al-Bukhari 6306', 26, 'Shaddad ibn Aws (رضي الله عنه) reported: The Prophet (ﷺ) said, "The most superior way of asking for forgiveness is Sayyidul-Istighfar. Whoever says it at night with firm belief in it, and dies before morning comes, he will be one of the people of Paradise." (Al-Bukhari 6306)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/27.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_27', 'اَللّٰهُمَّ إِنِّيْ أَمْسَيْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيْعَ خَلْقِكَ ، أَنَّكَ أَنْتَ اللّٰهُ لَا إِلٰهَ إِلَّا أَنْتَ وَحْدَكَ لَا شَرِيْكَ لَكَ ، وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُوْلُكَ.', 'Allāhumma innī amsaytu ush-hiduka, wa ush-hidu ḥamlata ʿarshika, wa malā''ikatika, wa jamī''a khalqika, annaka Anta-llāhu lā ilāha illā Anta waḥdak, lā sharīka lak, wa an-na Muḥammadan ʿabduka wa rasūluk.', 'O Allah, I have entered the evening, and I call upon You, the bearers of Your Throne, Your angels and all creation, to bear witness that surely You are Allah. There is no god worthy of worship except You Alone. You have no partners, and that Muḥammad ﷺ is Your slave and Your Messenger.', 4, 'evening', 'Freed from the Hellfire | Abu Dawud 5069', 'Abu Dawud 5069', 27, 'The Prophet ﷺ said: If anyone says in the morning: "O Allah! in the morning we call Thee, the bearers of Thy Throne, Thy angels, and all Thy creatures to witness that Thou art Allah than Whom there is no god, Thou being alone and without a partner, and that Muhammad is Thy servant and Thy Apostle," Allah will forgive him any sins that he commits that day; and if he repeats them in the evening. Allah will forgive him any sins he commits that night. (Sunan Abi Dawud 5078)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/37.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_28', 'اَللّٰهُمَّ عَافِنِيْ فِيْ بَدَنِيْ ، اَللّٰهُمَّ عَافِنِيْ فِيْ سَمْعِيْ ، اَللّٰهُمَّ عَافِنِيْ فِيْ بَصَرِيْ ، لَا إِلٰهَ إِلَّا أَنْتَ ، اَللّٰهُمَّ إِنِّيْ أَعُوْذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وأَعُوْذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لَا إِلٰهَ إِلَّا أَنْتَ.', 'Allāhumma ʿāfinī fī badanī, Allāhumma ʿāfinī fī samʿī, Allāhumma ʿāfinī fī baṣarī, lā ilāha illā Ant, Allāhumma innī aʿūdhu bika mina-l-kufri wa-l-faqr, wa aʿūdhu bika min ʿadhābi-l-qabr, lā ilāha illā Ant.', 'O Allah, grant me well-being in my body. O Allah, grant me well-being in my hearing. O Allah, grant me well-being in my sight. There is no god worthy of worship except You. O Allah, I seek Your protection from disbelief and poverty and I seek Your protection from the punishment of the grave. There is no god worthy of worship except You.', 3, 'evening', 'Good Health & Protection | Abu Dawud 5090', 'Abu Dawud 5090', 28, 'AbdurRahman ibn AbuBakrah (رضي الله عنه) said that he told his father: O my father! I hear you supplicating every morning: "O Allah! Grant me health in my body. O Allah! Grant me good hearing. O Allah! Grant me good eyesight. There is no god but Thou." You repeat them three times in the morning and three times in the evening. He said: I heard the Messenger of Allah (ﷺ) using these words as a supplication and I like to follow his practice... The Messenger of Allah (ﷺ) said: The supplications to be used by one who is distressed are: "O Allah! Thy mercy is what I hope for. Do not abandon me to myself for an instant, but put all my affairs in good order for me. There is no god but Thou." (Sunan Abi Dawud 5090)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/39.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_29', 'حَسْبِيَ اللّٰهُ لَا إِلٰهَ إِلَّا هُوَ ، عَلَيْهِ تَوَكَّلْتُ ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيْمِ.', 'Ḥasbiya-Allāhu lā ilāha illā Huwa, ʿalayhi tawakkaltu, wa Huwa Rabbu-l-ʿArshi-l-ʿaẓīm.', 'Allah is sufficient for me. There is no god worthy of worship except Him. I have placed my trust in Him only and He is the Lord of the Magnificent Throne.', 7, 'evening', 'Allah Will Suffice You | Abu Dawud 5081', 'Abu Dawud 5081', 29, 'Abu ad-Darda'' (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever says this seven times in the morning and evening, Allah will suffice him against whatever concerns him." (Abu Dawud 5081)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/40.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_30', 'لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيْكَ لَهُ ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيْرٌ.', 'Lā ilāha illā-Allāh, waḥdahū lā sharīka lah, lahu-l-mulk, wa lahu-l-ḥamd, wa Huwa ʿalā kulli shay''in Qadīr.', 'There is no god worthy of worship except Allah. He is Alone and He has no partner whatsoever. To Him Alone belong all sovereignty and all praise. He is over all things All-Powerful.', 100, 'evening', 'An Unparalleled Reward | Al-Bukhari 6403', 'Al-Bukhari 6403 | Sahih Muslim 2693', 30, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever says this one hundred times a day will get the same reward as given for manumitting ten slaves; one hundred good deeds will be written, one hundred sins deducted, and it will be a shield from Satan." (Al-Bukhari 6403)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/44.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_31', 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ.', 'Subḥāna-llāhi wa bi ḥamdih.', 'Allah is free from imperfection, and all praise is due to Him.', 100, 'evening', 'Get Your Sins Forgiven | Al-Bukhari 6405', 'Al-Bukhari 6405 | Sahih Muslim 2691', 31, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever says ''SubhanAllahi wa bihamdihi'' one hundred times a day, his sins will be forgiven even if they were as much as the foam of the sea." (Al-Bukhari 6405)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/43.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('evening_32', 'اَللّٰهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَّعَلَىٰ اٰلِ مُحَمَّدٍ ، كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيْمَ وَعَلَىٰ اٰلِ إِبْرَاهِيْمَ ، إِنَّكَ حَمِيْدٌ مَّجِيْدٌ ، اَللّٰهُمَّ بَارِكْ عَلَىٰ مُحَمَّدٍ وَّعَلَىٰ اٰلِ مُحَمَّدٍ ، كَمَا بَارَكْتَ عَلَىٰ إِبْرَاهِيْمَ وَعَلَىٰ اٰلِ إِبْرَاهِيْمَ ، إِنَّكَ حَمِيْدٌ مَّجِيْدٌ.', 'Allāhumma ṣalli ʿalā Muḥammad wa ʿalā āli Muḥammad, kamā ṣallayta ʿalā Ibrāhīma wa ʿalā āli Ibrāhīm, innaka Ḥamīdu-m-Majīd, Allāhumma bārik ʿalā Muḥammad, wa ʿalā āli Muḥammad, kamā bārakta ʿalā Ibrāhīma wa ʿalā āli Ibrāhīm, innaka Ḥamīdu-m-Majīd.', 'O Allah, honour and have mercy upon Muhammad and the family of Muhammad as You have honoured and had mercy upon Ibrāhīm and the family of Ibrāhīm. Indeed, You are the Most Praiseworthy, the Most Glorious. O Allah, bless Muhammad and the family of Muhammad as You have blessed Ibrāhīm and the family of Ibrāhīm. Indeed, You are the Most Praiseworthy, the Most Glorious.', 10, 'evening', 'Durood Ibrahim | Al-Bukhari 6357', 'Al-Bukhari 6357', 32, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever sends blessings upon me ten times in the morning and ten times in the evening, my intercession will reach him on the Day of Judgment." (At-Tabarani, Sahih Al-Jaami 6357)', 'https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/46.mp3');

-- Verify
SELECT id, sort_order, reward, recommended_count, LEFT(arabic, 40) as arabic_start FROM azkar_items WHERE category_id = 'evening' ORDER BY sort_order;
