-- Morning Azkar Migration: Dua & Adhkar v7.5.0 exact 32-item sequence
-- Run this in Supabase SQL Editor

-- Step 1: Delete old morning azkar
DELETE FROM azkar_items WHERE category_id = 'morning';

-- Step 2: Insert new 32 morning azkar
INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_1', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

اَلْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِيْنَ ، الرَّحْمٰنِ الرَّحِيْمِ ، مَالِكِ يَوْمِ الدِّيْنِ ، إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِيْنُ ، اِهْدِنَا الصِّرَاطَ الْمُسْتَقِيْمَ ، صِرَاطَ الَّذِيْنَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوْبِ عَلَيْهِمْ وَلَا الضَّالِّيْنَ', 'Bismillahir-Rahmanir-Rahim. Al-hamdu lillahi Rabbil-''alamin. Ar-Rahmanir-Rahim. Maliki yawmid-din. Iyyaka na''budu wa iyyaka nasta''in. Ihdinas-siratal-mustaqim. Siratal-ladhina an''amta ''alayhim, ghayril-maghdubi ''alayhim wa lad-dallin.', 'In the name of Allah, the Most Gracious, the Most Merciful. All praise is due to Allah, Lord of the worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment. You alone we worship, and You alone we ask for help. Guide us to the straight path — the path of those upon whom You have bestowed favor, not of those who have evoked Your anger or of those who are astray.', 1, 'morning', 'Al Fateha: The Opening of the Quran', 'Quran 1:1-7', 1, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Allah said: ''I have divided prayer between Myself and My servant into two halves, and My servant shall have what he has asked for.'' When the servant says ''Al-hamdu lillahi Rabbil-''alamin,'' Allah says: ''My servant has praised Me.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_2', 'الٓمٓ ، ذٰلِكَ الْكِتَابُ لَا رَيْبَ فِيْهِ هُدًى لِّلْمُتَّقِيْنَ ، الَّذِيْنَ يُؤْمِنُوْنَ بِالْغَيْبِ وَيُقِيْمُوْنَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُوْنَ ، وَالَّذِيْنَ يُؤْمِنُوْنَ بِمَا أُنْزِلَ إِلَيْكَ وَمَا أُنْزِلَ مِنْ قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوْقِنُوْنَ ، أُولٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ وَأُولٰئِكَ هُمُ الْمُفْلِحُوْنَ', 'Alif-Lam-Mim. Dhalikal-kitabu la rayba fih, hudal-lil-muttaqin. Alladhina yu''minuna bil-ghaybi wa yuqimunas-salata wa mimma razaqnahum yunfiqun. Walladhina yu''minuna bima unzila ilayka wa ma unzila min qablik, wa bil-akhirati hum yuqinun. Ula''ika ''ala hudam-mir-Rabbihim wa ula''ika humul-muflihun.', 'Alif, Lam, Mim. This is the Book about which there is no doubt, a guidance for those conscious of Allah — who believe in the unseen, establish prayer, and spend out of what We have provided for them, and who believe in what has been revealed to you and what was revealed before you, and of the Hereafter they are certain. Those are upon guidance from their Lord, and it is those who are the successful.', 1, 'morning', 'Alif Laam Meem: Opening of Al-Baqarah', 'Quran 2:1-5, Ad-Darimi', 2, 'It is reported that the Shaytan will not come near the one who recites the opening verses of Surah Al-Baqarah along with Ayat al-Kursi and the last verses of Al-Baqarah in the morning.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_3', 'أَعُوْذُ بِاللّٰهِ مِنَ الشَّيْطَانِ الرَّجِيْمِ. اَللّٰهُ لَآ إِلٰهَ إِلَّا هُوَ الْحَىُّ الْقَيُّوْمُ ، لَا تَأْخُذُهُۥ سِنَةٌ وَّلَا نَوْمٌ ، لَهُ مَا فِى السَّمٰـوٰتِ وَمَا فِى الْأَرْضِ ، مَنْ ذَا الَّذِىْ يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِۦ ، يَعْلَمُ مَا بَيْنَ أَيْدِيْهِمْ وَمَا خَلْفَهُمْ ، وَلَا يُحِيْطُوْنَ بِشَىْءٍ مِّنْ عِلْمِهِٓ إِلَّا بِمَا شَآءَ ، وَسِعَ كُرْسِيُّهُ السَّمٰـوٰتِ وَالْأَرْضَ، وَلَا يَئُوْدُهُۥ حِفْظُهُمَا ، وَهُوَ الْعَلِىُّ الْعَظِيْمُ.', 'Aʿūdhu bi-llāhi mina-sh-Shayṭāni-r-rajīm. Allāhu lā ilāha illā Huwa-l-Ḥayyu-l-Qayyūm, lā ta''khudhuhū sinatuw-wa lā nawm, lahū mā fi-s-samāwāti wa mā fi-l-arḍ, man dhā''lladhī yashfaʿu ʿindahū illā bi-idhnih, yaʿlamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay''im-min ʿilmihī illā bi-mā shā'', wasiʿa kursiyyuhu-s-samāwāti wa-l-arḍ, wa lā ya''ūduhū ḥifẓuhumā wa Huwa-l-ʿAlliyu-l-ʿAẓīm.', 'I seek the protection of Allah from the accursed Shayṭān. Allah, there is no god worthy of worship but He, the Ever Living, The Sustainer of all. Neither drowsiness overtakes Him nor sleep. To Him Alone belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except with His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursī extends over the heavens and the earth, and their preservation does not tire Him. And He is the Most High, the Magnificent. (2:255)', 1, 'morning', 'Ayatul Kursi: The Greatest Protection', 'Quran 2:255, Hakim 1/562', 3, 'Abu Huraira (رضي الله عنه) reported: The Prophet (ﷺ) entrusted me to guard the Zakat revenue of Ramadan. Someone came and began stealing from the food. When caught, he said, "When you go to bed, recite Ayat al-Kursi. Then there will be a guard from Allah who will protect you all night long, and Satan will not be able to come near you till dawn." The Prophet (ﷺ) confirmed, "He told you the truth, though he is a liar." Al-Hakim also reported that whoever recites it in the morning is protected until evening, and whoever recites it in the evening is protected until morning.', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/1.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_4', 'لَا إِكْرَاهَ فِي الدِّيْنِ ، قَدْ تَبَيَّنَ الرُّشْدُ مِنَ الْغَيِّ ، فَمَنْ يَّكْفُرْ بِالطَّاغُوْتِ وَيُؤْمِنْ بِاللّٰهِ فَقَدِ اسْتَمْسَكَ بِالْعُرْوَةِ الْوُثْقَىٰ لَا انْفِصَامَ لَهَا ، وَاللّٰهُ سَمِيْعٌ عَلِيْمٌ', 'La ikraha fid-din, qad tabayyanar-rushdu minal-ghayy. Faman yakfur bit-taghuti wa yu''min billahi faqadis-tamsaka bil-''urwatil-wuthqa lanfisama laha. Wallahu Sami''un ''Alim.', 'There shall be no compulsion in the religion. The right course has become clear from the wrong. So whoever disbelieves in false deities and believes in Allah has grasped the most trustworthy handhold with no break in it. And Allah is Hearing and Knowing.', 1, 'morning', 'La Ikraha fid-Deen: No Compulsion in Religion', 'Quran 2:256', 4, 'This verse establishes the principle that faith must come from sincere conviction. Reciting it in the morning affirms one''s conscious choice of Islam and trust in Allah''s guidance.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_5', 'اَللّٰهُ وَلِيُّ الَّذِيْنَ آمَنُوْا يُخْرِجُهُمْ مِّنَ الظُّلُمَاتِ إِلَى النُّوْرِ ، وَالَّذِيْنَ كَفَرُوْا أَوْلِيَاؤُهُمُ الطَّاغُوْتُ يُخْرِجُوْنَهُمْ مِّنَ النُّوْرِ إِلَى الظُّلُمَاتِ ، أُولٰئِكَ أَصْحَابُ النَّارِ هُمْ فِيْهَا خَالِدُوْنَ', 'Allahu waliyyul-ladhina amanu yukhrijuhum minaz-zulumati ilan-nur. Walladhina kafaru awliya''uhumut-taghut, yukhrijunahum minan-nuri ilaz-zulumat. Ula''ika as-habun-nar, hum fiha khalidun.', 'Allah is the ally of those who believe. He brings them out from darknesses into the light. And those who disbelieve — their allies are false deities. They take them out of the light into darknesses. Those are the companions of the Fire; they will abide eternally therein.', 1, 'morning', 'Allah is the Ally of the Believers', 'Quran 2:257', 5, 'This verse affirms that Allah guides and protects the believers, bringing them from the darkness of ignorance into the light of faith. Reciting it in the morning places oneself under Allah''s guardianship for the day.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_6', 'لِلّٰهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ، وَإِنْ تُبْدُوْا مَا فِيْ أَنْفُسِكُمْ أَوْ تُخْفُوْهُ يُحَاسِبْكُمْ بِهِ اللّٰهُ ، فَيَغْفِرُ لِمَنْ يَّشَاءُ وَيُعَذِّبُ مَنْ يَّشَاءُ ، وَاللّٰهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيْرٌ', 'Lillahi ma fis-samawati wa ma fil-ard. Wa in tubdu ma fi anfusikum aw tukhfuhu yuhasibkum bihillah. Fayaghfiru limay-yasha''u wa yu''adhdhibu may-yasha''. Wallahu ''ala kulli shay''in qadir.', 'To Allah belongs whatever is in the heavens and whatever is in the earth. Whether you show what is within yourselves or conceal it, Allah will bring you to account for it. Then He will forgive whom He wills and punish whom He wills, and Allah is over all things competent.', 1, 'morning', 'To Allah Belongs All That Is in the Heavens and Earth', 'Quran 2:284', 6, 'This is one of the last three verses of Surah Al-Baqarah. The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him." Scholars include 2:284 as part of this protective recitation.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_7', 'آمَنَ الرَّسُوْلُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَّبِّهِ وَالْمُؤْمِنُوْنَ ، كُلٌّ آمَنَ بِاللّٰهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّنْ رُسُلِهِ ، وَقَالُوْا سَمِعْنَا وَأَطَعْنَا غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيْرُ', 'Amanar-Rasulu bima unzila ilayhi mir-Rabbihi wal-mu''minun. Kullun amana billahi wa mala''ikatihi wa kutubihi wa rusulih, la nufarriqu bayna ahadim-mir-rusulih. Wa qalu sami''na wa ata''na, ghufranaka Rabbana wa ilaykal-masir.', 'The Messenger has believed in what was revealed to him from his Lord, and so have the believers. All of them have believed in Allah and His angels and His books and His messengers, saying, "We make no distinction between any of His messengers." And they say, "We hear and we obey. Grant us Your forgiveness, our Lord, and to You is the final destination."', 1, 'morning', 'The Messenger Has Believed', 'Quran 2:285, Bukhari 5009', 7, 'Abu Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_8', 'لَا يُكَلِّفُ اللّٰهُ نَفْسًا إِلَّا وُسْعَهَا ، لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ، رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِيْنَا أَوْ أَخْطَأْنَا ، رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِيْنَ مِنْ قَبْلِنَا ، رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ، وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ، أَنْتَ مَوْلَانَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِيْنَ', 'La yukallifullahu nafsan illa wus''aha. Laha ma kasabat wa ''alayha maktasabat. Rabbana la tu''akhidhna in nasina aw akhta''na. Rabbana wa la tahmil ''alayna isran kama hamaltahu ''alal-ladhina min qablina. Rabbana wa la tuhammilna ma la taqata lana bih. Wa''fu ''anna waghfir lana warhamna. Anta mawlana fansurna ''alal-qawmil-kafirin.', 'Allah does not burden a soul beyond that it can bear. It will have the consequence of what good it has gained, and it will bear the consequence of what evil it has earned. "Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people."', 1, 'morning', 'Allah Does Not Burden a Soul Beyond Capacity', 'Quran 2:286, Bukhari 5009', 8, 'Abu Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice him." Muslim reported that when this verse was revealed, Allah said after each supplication in it: "I have done so."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_9', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ هُوَ اللّٰهُ أَحَدٌ ، اَللّٰهُ الصَّمَدُ ، لَمْ يَلِدْ وَلَمْ يُوْلَدْ ، وَلَمْ يَكُنْ لَّهُ كُفُوًا أَحَدٌ', 'Bismillahir-Rahmanir-Rahim. Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakul-lahu kufuwan ahad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."', 3, 'morning', 'Surah Al-Ikhlas: Sincerity', 'Abu Dawud 5082, An-Nasa''i', 9, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to me, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn (Al-Falaq and An-Nas) three times in the morning and evening — they will suffice you against everything."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_10', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ أَعُوْذُ بِرَبِّ الْفَلَقِ ، مِنْ شَرِّ مَا خَلَقَ ، وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ، وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ، وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ', 'Bismillahir-Rahmanir-Rahim. Qul a''udhu bi Rabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-''uqad. Wa min sharri hasidin idha hasad.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of daybreak, from the evil of that which He created, and from the evil of darkness when it settles, and from the evil of the blowers in knots, and from the evil of an envier when he envies."', 3, 'morning', 'Surah Al-Falaq: Seek Refuge from Evil', 'Abu Dawud 5082', 10, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to me, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn (Al-Falaq and An-Nas) three times in the morning and evening — they will suffice you against everything."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_11', 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ

قُلْ أَعُوْذُ بِرَبِّ النَّاسِ ، مَلِكِ النَّاسِ ، إِلٰهِ النَّاسِ ، مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ، الَّذِيْ يُوَسْوِسُ فِيْ صُدُوْرِ النَّاسِ ، مِنَ الْجِنَّةِ وَالنَّاسِ', 'Bismillahir-Rahmanir-Rahim. Qul a''udhu bi Rabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.', 'In the name of Allah, the Most Gracious, the Most Merciful. Say, "I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer — who whispers in the breasts of mankind — from among the jinn and mankind."', 3, 'morning', 'Surah An-Nas: Seek Refuge from Whispers', 'Abu Dawud 5082', 11, 'Abdullah ibn Khubayb (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to me, "Recite Qul Huwa Allahu Ahad and Al-Mu''awwidhatayn (Al-Falaq and An-Nas) three times in the morning and evening — they will suffice you against everything."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_12', 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلّٰهِ وَالْحَمْدُ لِلّٰهِ ، لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيْكَ لَهُ ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيْرٌ ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِيْ هٰذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ ، وَأَعُوْذُ بِكَ مِنْ شَرِّ مَا فِيْ هٰذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ ، رَبِّ أَعُوْذُ بِكَ مِنَ الْكَسَلِ وَسُوْءِ الْكِبَرِ ، رَبِّ أَعُوْذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ.', 'Aṣbaḥnā wa aṣbaḥa-l-mulku li-llāh, wa-l-ḥamdu li-llāh, lā ilāha illa-llāhu waḥdahū lā sharīka lah, lahu-l-mulku wa lahu-l-ḥamd, wa huwa ʿalā kulli shay''in Qadīr, Rabbi as''aluka khayra mā fī hādha-l-yawmi wa khayra mā baʿdah, wa aʿūdhu bika min sharri mā fī hādha-l-yawmi wa sharri mā baʿdah. Rabbi aʿūdhu bika mina-l-kasali wa sū''i-l-kibar, Rabbi aʿūdhu bika min ʿadhābin fi-n-nāri wa ʿadhābin fi-l-qabr.', 'We have entered the morning and at this very time the whole kingdom belongs to Allah. All praise is due to Allah. There is no god worthy of worship except Allah, the One; He has no partner with Him. The entire kingdom belongs solely to Him, to Him is all praise due, and He is All-Powerful over everything. My Lord, I ask You for the good that is in this day and the good that follows it, and I seek Your protection from the evil that is in this day and from the evil that follows it. My Lord, I seek Your protection from laziness and the misery of old age. My Lord, I seek Your protection from the torment of the Hell-fire and the punishment of the grave.', 1, 'morning', 'Morning Supplication: Dominion Belongs to Allah', 'Muslim 2723', 12, 'Abdullah ibn Mas''ud (رضي الله عنه) reported: The Prophet (ﷺ) used to say in the morning: "Asbahna wa asbahal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa Huwa ''ala kulli shay''in Qadir. Rabbi as''aluka khayra ma fi hadhal-yawm wa khayra ma ba''dah, wa a''udhu bika min sharri hadhal-yawm wa sharri ma ba''dah."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/11.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_13', 'أَصْبَحْنَا عَلَىٰ فِطْرَةِ الْإِسْلَامِ ، وَعَلَىٰ كَلِمَةِ الْإِخْلَاصِ ، وَعَلَىٰ دِيْنِ نَبِيِّنَا مُحَمَّدٍ ، وَعَلَىٰ مِلَّةِ أَبِيْنَا إِبْرَاهِيْمَ حَنِيْفًا مُّسْلِمًا وَّمَا كَانَ مِنَ الْمُشْرِكِيْنَ.', 'Aṣbaḥnā ʿalā fiṭrati-l-islām. wa ʿalā kalimati-l-ikhlāṣ, wa ʿalā dīni Nabiyyinā Muḥammadin ṣallallāhu ʿalayhi wa sallam, wa ʿalā millati abīnā Ibrāhīma ḥanīfam-muslima, wa mā kāna min-l-mushrikīn.', 'We have entered the morning upon the natural religion of Islam, the statement of pure faith (i.e. Shahādah), the religion of our Prophet Muhammad ﷺ and upon the way of our father Ibrāhīm, who turned away from all that is false, having surrendered to Allah, and he was not of the polytheists.', 1, 'morning', 'Upon the Fitrah of Islam', 'Ahmad 15360', 13, 'Abu Huraira (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever says La ilaha illallahu wahdahu la sharika lahu, lahul-mulku wa lahul-hamdu, wa Huwa ''ala kulli shay''in Qadir one hundred times: he gets the reward of freeing ten slaves, one hundred good deeds are written, one hundred sins are erased, and it is a protection from Shaytan till evening."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/9.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_14', 'اَللّٰهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوْتُ وَإِلَيْكَ النُّشُوْرُ.', 'Allāhumma bika aṣbaḥnā wa bika amsaynā wa bika naḥyā wa bika namūtu wa ilayka-n-nushūr.', 'O Allah, by You we have entered the morning and by You we enter upon the evening. By You, we live and we die, and to You is the resurrection.', 1, 'morning', 'By Your Leave We Have Reached the Morning', 'Al-Adab al-Mufrad 1199', 14, 'Abu Huraira (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever says in the morning and evening: ''Radhitu billahi Rabba, wa bil-Islami dina, wa bi-Muhammadin nabiyya'' — it is a right upon Allah to please him on the Day of Judgment."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/14.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_15', 'اَللّٰهُمَّ إِنِّيْ أَصْبَحْتُ مِنْكَ فِيْ نِعْمَةٍ وَعَافِيَةٍ وَسِتْرٍ ، فَأَتِمَّ عَلَيَّ نِعْمَتَكَ وَعَافِيَتَكَ وَسِتْرَكَ فِي الدُّنْيَا وَالْآخِرَةِ', 'Allahumma inni asbahtu minka fi ni''matin wa ''afiyatin wa sitr, fa atimma ''alayya ni''mataka wa ''afiyataka wa sitraka fid-dunya wal-akhirah.', 'O Allah, I have entered the morning receiving from You blessings, well-being and concealment (of my faults). So complete Your blessings upon me, Your well-being, and Your concealment in this world and the Hereafter.', 3, 'morning', 'Blessings, Well-being and Concealment', 'Ibn al-Sunni 41', 15, 'Abdullah ibn Umar (رضي الله عنه) reported: The Messenger of Allah (ﷺ) never used to leave this supplication in the morning and evening, asking Allah to complete His blessings, well-being, and concealment of faults upon him in this world and the Hereafter.');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_16', 'اَللّٰهُمَّ مَا أَصْبَحَ بِيْ مِنْ نِّعْمَةٍ أَوْ بِأَحَدٍ مِّنْ خَلْقِكَ ، فَمِنْكَ وَحْدَكَ لَا شَرِيْكَ لَكَ ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ.', 'Allāhumma mā aṣbaḥa bī min niʿmatin aw bi-aḥadim-min khalqik, fa-minka waḥdaka lā sharīka lak, fa laka-l-ḥamdu wa laka-sh-shukr.', 'O Allah, all the favours that I or anyone from Your creation has received in the morning, are from You Alone. You have no partner. To You Alone belong all praise and all thanks.', 1, 'morning', 'Fulfil Your Obligation to Thank Allah', 'Abu Dawud 5073', 16, 'Abdullah ibn Ghannam (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever says in the morning: ''Allahumma ma asbaha bi min ni''matin aw bi-ahadin min khalqik, faminka wahdaka la sharika lak, falakal-hamdu wa lakash-shukr'' — he has fulfilled his duty of giving thanks for that day."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/8.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_17', 'يَا رَبِّ لَكَ الْحَمْدُ كَمَا يَنْبَغِيْ لِجَلَالِ وَجْهِكَ وَعَظِيْمِ سُلْطَانِكَ', 'Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.', 'O my Lord, all praise is due to You as befits the Glory of Your Countenance and the Greatness of Your Authority.', 1, 'morning', 'Praise Befitting Divine Greatness', 'Ibn Majah 3801', 17, 'Abdullah ibn Umar (رضي الله عنه) reported: The Prophet (ﷺ) said, "A servant said: ''Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.'' The two angels did not know how to record it, so they ascended to the heavens and said: ''Our Lord, Your servant has said something and we do not know how to record it.'' Allah — while knowing best what His servant said — asked: ''What did My servant say?'' They replied: ''He said: Ya Rabbi lakal-hamdu kama yanbaghi li jalali wajhika wa ''azimi sultanik.'' Allah said to them: ''Record it as My servant said it, until he meets Me and I shall reward him for it.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_18', 'رَضِيْتُ بِاللّٰهِ رَبًّا ، وَبِالْإِسْلَامِ دِيْنًا ، وَبِمُحَمَّدٍ صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا', 'Raditu billahi Rabba, wa bil-Islami dina, wa bi-Muhammadin sallallahu ''alayhi wa sallama nabiyya.', 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (ﷺ) as my Prophet.', 3, 'morning', 'Pleased with Allah as Lord', 'Abu Dawud 5072, Ahmad 18967', 18, 'Abu Sallam (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever says in the morning and evening: ''Raditu billahi Rabba, wa bil-Islami dina, wa bi-Muhammadin nabiyya'' — it is a right upon Allah to please him on the Day of Judgment."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_19', 'اَللّٰهُمَّ إِنِّيْ أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ ، اَللّٰهُمَّ إِنِّيْ أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِيْ دِيْنِيْ وَدُنْيَايَ وَأَهْلِيْ وَمَالِيْ ، اَللّٰهُمَّ اسْتُرْ عَوْرَاتِيْ وَآمِنْ رَوْعَاتِيْ ، اَللّٰهُمَّ احْفَظْنِيْ مِنْ بَيْنِ يَدَيَّ ، وَمِنْ خَلْفِيْ ، وَعَنْ يَّمِيْنِيْ ، وَعَنْ شِمَالِيْ ، وَمِنْ فَوْقِيْ ، وَأَعُوْذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِيْ.', 'Allāhumma innī as''aluka-l-ʿāfiyata fi-d-dunyā wa-l-ākhirah. Allāhumma innī as''aluka-l-ʿafwa wa-l-ʿāfiyata fī dīnī wa dunyāya wa ahlī wa mālī, Allāhumma-stur ʿawrātī wa āmin rawʿātī. Allāhumma-ḥfaẓnī mim bayni yadayya wa min khalfī, wa ʿay-n yamīnī wa ʿan shimālī wa min fawqī, wa aʿūdhu bi-ʿaẓamatika an ughtāla min taḥtī.', 'O Allah, I ask You for well-being in this world and the next. O Allah, I ask You for forgiveness and well-being in my religion, in my worldly affairs, in my family and in my wealth. O Allah, conceal my faults and calm my fears. O Allah, guard me from in front of me and behind me, from my right, and from my left, and from above me. I seek protection in Your Greatness from being unexpectedly destroyed from beneath me.', 1, 'morning', 'Well-being in this World and the Hereafter', 'Ibn Majah 2/323', 19, 'Abdullah ibn Umar (رضي الله عنهما) reported: The Messenger of Allah (ﷺ) never used to leave these supplications in the morning and evening: "Allahumma inni as''alukal-''afiyata fid-dunya wal-akhirah. Allahumma inni as''alukal-''afwa wal-''afiyata fi dini wa dunyaya wa ahli wa mali (O Allah, I ask You for well-being in this world and the next. O Allah, I ask You for pardon and well-being in my religion, worldly life, family, and wealth)."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/5.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_20', 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ ، عَدَدَ خَلْقِهِ ، وَرِضَا نَفْسِهِ ، وَزِنَةَ عَرْشِهِ ، وَمِدَادَ كَلِمَاتِهِ.', 'Subḥāna-llāhi wa bi ḥamdih, ʿadada khalqih, wa riḍā nafsih, wa zinata ʿarshih, wa midāda kalimātih.', 'Allah is free from imperfection and all praise is due to Him, (in ways) as numerous as all He has created, (as vast) as His pleasure, (as limitless) as the weight of His Throne, and (as endless) as the ink of His words.', 3, 'morning', 'SubhanAllah wa bihamdihi: Outweigh All Other Dhikr', 'Muslim 2726', 20, 'Jabir ibn Abdullah (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "The best remembrance is: La ilaha illallah, and the best supplication is: Alhamdulillah." And he (ﷺ) said, "The phrases SubhanAllah, Alhamdulillah, La ilaha illallah, and Allahu Akbar are the most beloved of all words to Allah. It does not matter which of them you begin with."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/24.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_21', 'بِسْمِ اللّٰهِ الَّذِيْ لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ ، وَهُوَ السَّمِيْعُ الْعَلِيْمُ.', 'Bismi-llāhi-lladhī lā yaḍurru maʿasmihi shay''un fi-l-arḍi wa lā fi-s-samā'', wa Huwa-s-Samīʿu-l-ʿAlīm.', 'In the Name of Allah, with whose Name nothing can harm in the earth nor in the sky. He is The All-Hearing and All-Knowing.', 3, 'morning', 'Protect Yourself From All Harm', 'Abu Dawud 5088, Tirmidhi 3388', 21, 'Uthman ibn Affan (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "No servant says in the morning and evening: ''Bismillahilladhi la yadurru ma''asmihi shay''un fil-ardi wa la fis-sama'', wa Huwas-Sami''ul-''Alim'' three times, and anything will harm him."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/18.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_22', 'اَللّٰهُمَّ إِنِّيْ أَعُوْذُ بِكَ أَنْ أُشْرِكَ بِكَ وَأَنَا أَعْلَمُ ، وَأَسْتَغْفِرُكَ لِمَا لَا أَعْلَمُ', 'Allahumma inni a''udhu bika an ushrika bika wa ana a''lam, wa astaghfiruka lima la a''lam.', 'O Allah, I seek refuge in You from associating anything with You knowingly, and I seek Your forgiveness for what I do not know.', 3, 'morning', 'Seek Refuge from Shirk', 'Ahmad 23119', 22, 'Ma''qil ibn Yasar (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever says ''Allahumma inni a''udhu bika an ushrika bika wa ana a''lam, wa astaghfiruka lima la a''lam'' three times, Allah will protect him from shirk."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_23', 'أَعُوْذُ بِكَلِمَاتِ اللّٰهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ', 'A''udhu bi kalimatillahit-tammati min sharri ma khalaq.', 'I seek refuge in the perfect words of Allah from the evil of what He has created.', 3, 'morning', 'Protection From All Evil Wherever You Are', 'Muslim 2708, Ahmad', 23, 'Khawlah bint Hakim (رضي الله عنها) reported: The Messenger of Allah (ﷺ) said, "Whoever arrives at a place and says: ''A''udhu bi kalimatillahit-tammati min sharri ma khalaq'' — nothing will harm him until he leaves that place."');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_24', 'اَللّٰهُمَّ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ ، فَاطِرَ السَّمٰوَاتِ وَالْأَرْضِ ، رَبَّ كُلِّ شَيْءٍ وَمَلِيْكَهُ ، أَشْهَدُ أَنْ لَّا إِلٰهَ إِلَّا أَنْتَ ، أَعُوْذُ بِكَ مِنْ شَرِّ نَفْسِيْ ، وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ ، وَأَنْ أَقْتَرِفَ عَلَىٰ نَفْسِيْ سُوْءًا ، أَوْ أَجُرَّهُ إِلَىٰ مُسْلِمٍ.', 'Allāhumma ʿālima-l-ghaybi wa-sh-shahādah, fāṭir-as-samāwāti wa-l-arḍi, rabba kulli shay''iw-wa malīkah, ash-hadu al-lā ilāha illā Anta, aʿūdhu bika min sharri nafsī wa min sharri-sh-shayṭāni wa shirkihī wa an aqtarifa ʿalā nafsī sū''an aw ajurrahū ilā muslim.', 'O Allah, Knower of the unseen and the seen, Creator of the heavens and the earth, the Lord and Sovereign of everything; I bear witness that there is no god worthy of worship but You. I seek Your protection from the evil of my own self, from the evil of Shayṭān and from the evil of polytheism to which he calls, and from inflicting evil on myself, or bringing it upon a Muslim.', 1, 'morning', 'Knower of the Unseen: Protection from Evil', 'Tirmidhi 3392', 24, 'Abdullah ibn Umar (رضي الله عنهما) reported: The Prophet (ﷺ) used to say in the morning and evening: "Allahumma inni a''udhu bika minal-kufri wal-faqr, wa a''udhu bika min ''adhabil-qabr, la ilaha illa Ant (O Allah, I seek refuge in You from disbelief, poverty, and the punishment of the grave)."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/6.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full)
VALUES ('morning_25', 'يَا حَيُّ يَا قَيُّوْمُ ، بِرَحْمَتِكَ أَسْتَغِيْثُ ، أَصْلِحْ لِيْ شَأْنِيْ كُلَّهُ ، وَلَا تَكِلْنِيْ إِلَىٰ نَفْسِيْ طَرْفَةَ عَيْنٍ', 'Ya Hayyu ya Qayyumu birahmatika astaghith, aslih li sha''ni kullahu, wa la takilni ila nafsi tarfata ''ayn.', 'O Ever-Living, O Sustainer, in Your mercy I seek relief. Rectify all my affairs and do not leave me to myself even for the blink of an eye.', 1, 'morning', 'Ya Hayyu Ya Qayyum: Rectify All My Affairs', 'Hakim 1/545', 25, 'Anas ibn Malik (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said to Fatimah (رضي الله عنها), "What prevents you from listening to what I advise you? Say in the morning and evening: ''Ya Hayyu ya Qayyumu birahmatika astaghith, aslih li sha''ni kullahu, wa la takilni ila nafsi tarfata ''ayn.''"');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_26', 'اَللّٰهُمَّ أَنْتَ رَبِّيْ لَا إِلٰهَ إِلَّا أَنْتَ ، خَلَقْتَنِيْ وَأَنَا عَبْدُكَ ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ ، أَعُوْذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ ، أَبُوْءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوْءُ لَكَ بِذَنْبِيْ ، فَاغْفِرْ لِيْ فَإِنَّهُ لَا يَغْفِرُ الذُّنُوْبَ إِلَّا أَنْتَ.', 'Allāhumma Anta Rabbī, lā ilāha illā Ant, khalaqtanī wa ana ʿabduk, wa ana ʿalā ʿahdika wa waʿdika mā''staṭaʿt, aʿūdhu bika min sharri mā ṣanaʿt, abū''u laka bi niʿmatika ʿalayya wa abū''u laka bi-dhambī fa-ghfir lī fa-innahū lā yaghfiru-dh-dhunūba illā Ant.', 'O Allah, You are my Lord. There is no god worthy of worship except You. You have created me, and I am Your slave, and I am under Your covenant and pledge (to fulfil it) to the best of my ability. I seek Your protection from the evil that I have done. I acknowledge the favours that You have bestowed upon me, and I admit my sins. Forgive me, for none forgives sins but You.', 1, 'morning', 'Sayyid al-Istighfar: The Best Forgiveness', 'Bukhari 6306', 26, 'Shaddad ibn Aws (رضي الله عنه) reported: The Prophet (ﷺ) said, "The most superior way of asking for forgiveness is Sayyidul-Istighfar: ''Allahumma Anta Rabbi la ilaha illa Anta, khalaqtani wa ana ''abduka, wa ana ''ala ''ahdika wa wa''dika mastata''tu, a''udhu bika min sharri ma sana''tu, abu''u laka bini''matika ''alayya, wa abu''u bidhanbi, faghfir li, fa innahu la yaghfirudh-dhunuba illa Ant.'' Whoever says it during the day with firm belief and dies that day, he will be from the people of Paradise."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/3.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_27', 'اَللّٰهُمَّ إِنِّيْ أَصْبَحْتُ أُشْهِدُكَ ، وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيْعَ خَلْقِكَ ، أَنَّكَ أَنْتَ اللّٰهُ لَا إِلٰهَ إِلَّا أَنْتَ وَحْدَكَ لَا شَرِيْكَ لَكَ ، وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُوْلُكَ.', 'Allāhumma innī aṣbaḥtu ush-hiduk, wa ush-hidu ḥamlata ʿarshik, wa malā''ikatika wa jamīʿa khalqik, an-naka Anta-llāhu lā ilāha illā Anta waḥdak, lā sharīka lak, wa anna Muḥammadan ʿabduka wa rasūluk.', 'O Allah, I have entered the morning, and I call upon You, the bearers of Your Throne, Your angels and all creation, to bear witness that surely You are Allah. There is no god worthy of worship except You Alone. You have no partners, and that Muḥammad ﷺ is Your slave and Your Messenger.', 4, 'morning', 'Get Yourself Freed from the Hellfire', 'Abu Dawud 5069', 27, 'Muslim ibn al-Harith (رضي الله عنه) reported: The Prophet (ﷺ) whispered to me: "When you finish the Maghrib prayer, say before speaking to anyone: ''Allahumma ajirni minan-nar'' seven times. If you say it and die that night, you will be granted protection from it. And when you finish the Fajr prayer, say the same."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/13.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_28', 'اَللّٰهُمَّ عَافِنِيْ فِيْ بَدَنِيْ ، اَللّٰهُمَّ عَافِنِيْ فِيْ سَمْعِيْ ، اَللّٰهُمَّ عَافِنِيْ فِيْ بَصَرِيْ ، لَا إِلٰهَ إِلَّا أَنْتَ ، اَللّٰهُمَّ إِنِّيْ أَعُوْذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وأَعُوْذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لَا إِلٰهَ إِلَّا أَنْتَ.', 'Allāhumma ʿāfinī fī badanī, Allāhumma ʿāfinī fī samʿī, Allāhumma ʿāfinī fī baṣarī, lā ilāha illā Ant, Allāhumma innī aʿūdhu bika mina-l-kufri wa-l-faqr, wa aʿūdhu bika min ʿadhābi-l-qabr, lā ilāha illā Ant.', 'O Allah, grant me well-being in my body. O Allah, grant me well-being in my hearing. O Allah, grant me well-being in my sight. There is no god worthy of worship except You. O Allah, I seek Your protection from disbelief and poverty and I seek Your protection from the punishment of the grave. There is no god worthy of worship except You.', 3, 'morning', 'Ask Allah For Good Health and Protection', 'Abu Dawud 5090', 28, 'Abdullah ibn Umar (رضي الله عنهما) reported: The Messenger of Allah (ﷺ) never used to leave these supplications in the morning and evening: "Allahumma inni as''alukal-''afiyata fi dini wa dunyaya wa ahli wa mali. Allahumma-stur ''awrati wa amin raw''ati (O Allah, I ask You for well-being in my religion, my worldly life, my family, and my wealth. O Allah, conceal my faults and calm my fears)."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/15.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_29', 'حَسْبِيَ اللّٰهُ لَا إِلٰهَ إِلَّا هُوَ ، عَلَيْهِ تَوَكَّلْتُ ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيْمِ.', 'Ḥasbiya-Allāhu lā ilāha illā Huwa, ʿalayhi tawakkaltu, wa Huwa Rabbu-l-ʿArshi-l-ʿaẓīm.', 'Allah is sufficient for me. There is no god worthy of worship except Him. I have placed my trust in Him only and He is the Lord of the Magnificent Throne.', 7, 'morning', 'Allah Will Suffice You in Everything', 'Abu Dawud 5081', 29, 'Abu ad-Darda'' (رضي الله عنه) reported: The Prophet (ﷺ) said, "Whoever says ''Hasbiyallahu la ilaha illa Huwa, ''alayhi tawakkaltu wa Huwa Rabbul-''Arshil-''Azim'' seven times in the morning and evening, Allah will suffice him in whatever concerns him."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/16.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_30', 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلّٰهِ رَبِّ الْعَالَمِيْنَ ، اَللّٰهُمَّ إِنِّيْ أَسْأَلُكَ خَيْرَ هٰذَا الْيَوْمِ ، فَتْحَهُ وَنَصْرَهُ وَنُوْرَهُ وَبَرَكَتَهُ وَهُدَاهُ ، وَأَعُوْذُ بِكَ مِنْ شَرِّ مَا فِيْهِ وَشَرِّ مَا بَعْدَهُ.', 'Aṣbaḥnā wa aṣbaḥa-l-mulku li-llāhi Rabbi-l-ʿālamīn, Allāhumma innī as''aluka khayra hādha-l-yawm, fatḥahū wa naṣrahū wa nūrahū wa barakatahū wa hudāh, wa aʿūdhu bika min sharri mā fīhi wa sharri mā baʿdah.', 'We have entered the morning and at this very time the whole kingdom belongs to Allah, Lord of the Worlds. O Allah, I ask You for the goodness of this day: its victory, its help, its light, and its blessings and guidance. I seek Your protection from the evil that is in it and from the evil that follows it.', 1, 'morning', 'Ask Allah to Bless Your Day', 'Abu Dawud 5084', 30, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) used to say in the morning: "Allahumma bika asbahna wa bika amsayna, wa bika nahya wa bika namutu, wa ilaykan-nushur (O Allah, by You we enter the morning and by You we enter the evening. By You we live and by You we die, and to You is the resurrection)."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/13.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_31', 'لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيْكَ لَهُ ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيْرٌ.', 'Lā ilāha illā-Allāh, waḥdahū lā sharīka lah, lahu-l-mulk, wa lahu-l-ḥamd, wa Huwa ʿalā kulli shay''in Qadīr.', 'There is no god worthy of worship except Allah. He is Alone and He has no partner whatsoever. To Him Alone belong all sovereignty and all praise. He is over all things All-Powerful.', 100, 'morning', 'An Unparalleled Reward', 'Bukhari 6403, Muslim', 31, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever says La ilaha illallahu wahdahu la sharika lahu, lahul-mulku wa lahul-hamdu, wa Huwa ''ala kulli shay''in Qadir one hundred times a day, will get the same reward as given for manumitting ten slaves; one hundred good deeds will be written in his accounts, one hundred sins will be deducted, and it will be a shield for him from Satan on that day till night, and nobody will be able to do a better deed except the one who does more."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/20.mp3');

INSERT INTO azkar_items (id, arabic, transliteration, translation, recommended_count, category_id, reward, reference, sort_order, hadith_full, audio_url)
VALUES ('morning_32', 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ.', 'Subḥāna-llāhi wa bi ḥamdih.', 'Allah is free from imperfection, and all praise is due to Him.', 100, 'morning', 'Get Your Sins Forgiven', 'Bukhari 6405, Muslim 2692', 32, 'Abu Huraira (رضي الله عنه) reported: The Messenger of Allah (ﷺ) said, "Whoever says SubhanAllahi wa bihamdihi one hundred times a day, his sins will be forgiven even if they were as much as the foam of the sea."', 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/19.mp3');

-- Verify
SELECT id, sort_order, reward, recommended_count FROM azkar_items WHERE category_id = 'morning' ORDER BY sort_order;
