-- Auto-generated by Claude Code research agent.
-- Source priority: lifewithallah.com (LWA) -> audio.qurancdn.com (Alafasy) -> skip
-- Items not matched anywhere are omitted (no UPDATE generated).
--
-- LWA URL patterns verified by sample fetches (all returned valid MP3):
--   https://static.lifewithallah.com/file/LifeWithAllah/main/4-Salawat/{184..192}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/{193..233}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/{234..268}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/{1..24}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/main/8-Evening/{25..47}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/{48..65}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/main/10-Salah/{66..101}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/{118..130}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/{131..153}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/{155..183}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/{482..489,137,591}.mp3
--   https://static.lifewithallah.com/file/LifeWithAllah/other/21-WakingUp/{414,415}.mp3
-- Quran CDN (Alafasy) verified for surah 002 ayah 201:
--   https://audio.qurancdn.com/Alafasy/mp3/<surah:3>+<ayah:3>.mp3

BEGIN;

-- =======================================================================
-- TAHAJJUD (3 items)
-- =======================================================================
-- tahajjud_opening = "Allahumma laka al-hamd, anta nur as-samawat" -> LWA Salah/72
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/10-Salah/72.mp3' WHERE id = 'tahajjud_opening';
-- tahajjud_witr = "Subhana al-Malik al-Quddus" -> LWA AfterSalah/130
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/130.mp3' WHERE id = 'tahajjud_witr';
-- tahajjud_qunut not matched (LWA does not host the Qunut dua audio individually)

-- =======================================================================
-- SALAWAT (3 items)
-- =======================================================================
-- salawat_ibrahimiyya = Ibrahimiya salawat (4-Salawat/184)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/4-Salawat/184.mp3' WHERE id = 'salawat_ibrahimiyya';
-- salawat_simple not matched (simple "sallallahu alayhi wa sallam" has no individual LWA file)
-- salawat_friday = abundant Friday salawat -> LWA 4-Salawat/191 (Salawat on Nabi)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/4-Salawat/191.mp3' WHERE id = 'salawat_friday';

-- =======================================================================
-- QURANIC SUPPLICATIONS (bocp_001-042) -> map to LWA 5-QuranicDuas
-- where exact Arabic match; otherwise use audio.qurancdn.com for verses.
-- =======================================================================
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/209.mp3' WHERE id = 'bocp_001';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/226.mp3' WHERE id = 'bocp_002';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/224.mp3' WHERE id = 'bocp_003';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/211.mp3' WHERE id = 'bocp_004';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/198.mp3' WHERE id = 'bocp_005';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/181.mp3' WHERE id = 'bocp_006';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/217.mp3' WHERE id = 'bocp_007';
-- bocp_008 (Q3:53) - use Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003053.mp3' WHERE id = 'bocp_008';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/225.mp3' WHERE id = 'bocp_009';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/206.mp3' WHERE id = 'bocp_010';
-- bocp_011 (Q5:83) - use Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/005083.mp3' WHERE id = 'bocp_011';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/196.mp3' WHERE id = 'bocp_012';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/228.mp3' WHERE id = 'bocp_013';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/229.mp3' WHERE id = 'bocp_014';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/201.mp3' WHERE id = 'bocp_015';
-- bocp_016 (Q14:35) - use Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014035.mp3' WHERE id = 'bocp_016';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/215.mp3' WHERE id = 'bocp_017';
-- bocp_018 (Q14:41) - use Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014041.mp3' WHERE id = 'bocp_018';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/216.mp3' WHERE id = 'bocp_019';
-- bocp_020 (Q17:80) - use Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/017080.mp3' WHERE id = 'bocp_020';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/210.mp3' WHERE id = 'bocp_021';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/212.mp3' WHERE id = 'bocp_022';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/194.mp3' WHERE id = 'bocp_023';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/219.mp3' WHERE id = 'bocp_024';
-- bocp_025 (Q23:29) - use Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/023029.mp3' WHERE id = 'bocp_025';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/223.mp3' WHERE id = 'bocp_026';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/199.mp3' WHERE id = 'bocp_027';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/200.mp3' WHERE id = 'bocp_028';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/221.mp3' WHERE id = 'bocp_029';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/195.mp3' WHERE id = 'bocp_030';
-- bocp_031 (Q28:17) - use Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/028017.mp3' WHERE id = 'bocp_031';
-- bocp_032 (Q28:21) - use Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/028021.mp3' WHERE id = 'bocp_032';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/208.mp3' WHERE id = 'bocp_033';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/227.mp3' WHERE id = 'bocp_034';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/205.mp3' WHERE id = 'bocp_035';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/220.mp3' WHERE id = 'bocp_036';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/207.mp3' WHERE id = 'bocp_037';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/222.mp3' WHERE id = 'bocp_038';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/218.mp3' WHERE id = 'bocp_039';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/202.mp3' WHERE id = 'bocp_040';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/230.mp3' WHERE id = 'bocp_041';
-- bocp_042 (Q71:28) - use Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/071028.mp3' WHERE id = 'bocp_042';

-- =======================================================================
-- PROPHETIC SUPPLICATIONS (bocp_043-121) -> LWA 6-SunnahDuas where matched
-- =======================================================================
-- bocp_043 (Allahumma atina fid-dunya hasanah hadith variant) - no LWA Sunnah Duas match
-- bocp_044 (a'udhu min fitnat an-nar...) -> LWA SunnahDuas/247
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/247.mp3' WHERE id = 'bocp_044';
-- bocp_045 (a'udhu min al-'ajz wa al-kasal wa al-jubn wa al-haram wa al-bukhl - short version) -> LWA SunnahDuas/248
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/248.mp3' WHERE id = 'bocp_045';
-- bocp_046 (jahd al-bala) - not matched
-- bocp_047 (Allahumma aslih li dini) - not matched
-- bocp_048 (al-huda wat-tuqa wal-'afaaf wal-ghina) -> LWA SunnahDuas/244 (asaluka iman...) actually 244 is asaluka iman. SKIP.
-- bocp_049 (long version of a'udhu) - not matched
-- bocp_050 (ihdini wa saddidni) - not matched
-- bocp_051 (zawal ni'mah) - not matched
-- bocp_052 (akthir mali wa waladi) - not matched
-- bocp_053 (la ilaha illa Allah al-'Azim al-Halim - dua of distress) - not matched
-- bocp_054 (rahmataka arju) - not matched
-- bocp_055 (Yunus dua - same as bocp_023 Quranic) -> LWA QuranicDuas/194
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/194.mp3' WHERE id = 'bocp_055';
-- bocp_056 (Allahumma inni 'abduka...) - not matched
-- bocp_057 (musarrif al-qulub) -> LWA SunnahDuas/259
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/259.mp3' WHERE id = 'bocp_057';
-- bocp_058 (Ya muqalliba al-qulub) -> LWA SunnahDuas/258
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/258.mp3' WHERE id = 'bocp_058';
-- bocp_059 (al-'afiyah fid-dunya wal-akhirah) -> LWA SunnahDuas/263
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/263.mp3' WHERE id = 'bocp_059';
-- bocp_060 (ahsin 'aqibatana) -> LWA SunnahDuas/261
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/261.mp3' WHERE id = 'bocp_060';
-- bocp_061 (Rabbi a'inni wa la tu'in 'alayya) -> LWA SunnahDuas/264
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/264.mp3' WHERE id = 'bocp_061';
-- bocp_062 (sharr sam'i) - not matched
-- bocp_063 ('afuwwun karim) -> LWA SunnahDuas/237
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/237.mp3' WHERE id = 'bocp_063';
-- bocp_064 (fi'l al-khayrat) -> LWA SunnahDuas/266
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/266.mp3' WHERE id = 'bocp_064';
-- bocp_065 (al-khayr kullihi) - not matched
-- bocp_066 (ihfazni bil-islam) -> LWA SunnahDuas/257
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/257.mp3' WHERE id = 'bocp_066';
-- bocp_067 (a'udhu min al-jubn wal-bukhl - shorter) - not matched
-- bocp_068 (ighfir li khati'ati wa jahli) -> LWA SunnahDuas/236
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/236.mp3' WHERE id = 'bocp_068';
-- bocp_069 (Abu Bakr's dua - zalamtu nafsi zulman kathiran) -> LWA SunnahDuas/240
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/240.mp3' WHERE id = 'bocp_069';
-- bocp_070 (laka aslamtu) - not matched
-- bocp_071 (mujibat rahmatik) -> LWA SunnahDuas/249
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/249.mp3' WHERE id = 'bocp_071';
-- bocp_072 (sharr ma 'alimtu) - not matched
-- bocp_073 (awsa' rizqika 'ind kibar sinni) - not matched
-- bocp_074 (ighfir li dhanbi wassi' li fi dari) - not matched
-- bocp_075 (faldika wa rahmatik) - not matched
-- bocp_076 (a'udhu min at-taraddi wal-hadm) - not matched
-- bocp_077 (long a'udhu list - taraddi/hadm/gharaq) - not matched
-- bocp_078 (faqr/qillah/dhillah) - not matched
-- bocp_079 (qalb la yakhsha') - not matched (could match LWA SunnahDuas variant but uncertain)
-- bocp_080 (yawm as-su') - not matched
-- bocp_081 (al-jannah wa astajiru min an-nar) -> LWA SunnahDuas/245 (asaluka al-firdaws)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/245.mp3' WHERE id = 'bocp_081';
-- bocp_082 (faqqihni fid-din) - not matched
-- bocp_083 (ushrika bika wa ana a'lam) - not matched
-- bocp_084 ('ilman nafi'an wa rizqan tayyiban wa 'amalan mutaqabbalan) -> LWA AfterSalah/129
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/129.mp3' WHERE id = 'bocp_084';
-- bocp_085 ('ilman nafi'an short) - not matched (similar but different)
-- bocp_086 (asaluka ya Allah bi-annaka al-Wahid al-Ahad) - not matched
-- bocp_087 (anta Allah al-Ahad as-Samad) - not matched
-- bocp_088 (bi-anna laka al-hamd la ilaha illa anta) - LWA Praises/183
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/183.mp3' WHERE id = 'bocp_088';
-- bocp_089 (ighfir li wa tub 'alayya) - not matched
-- bocp_090 (bi-'ilmika al-ghayb wa qudratika 'ala al-khalq) -> LWA SunnahDuas/268
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/268.mp3' WHERE id = 'bocp_090';
-- bocp_091 (tahhirni min adh-dhunub) - not matched
-- bocp_092 (Rabb Jibril wa Mika'il) -> LWA SunnahDuas/246
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/246.mp3' WHERE id = 'bocp_092';
-- bocp_093 (alhimni rushdi) - not matched
-- bocp_094 (Rabb as-samawat wa Rabb al-ard) -> LWA Praises/162
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/162.mp3' WHERE id = 'bocp_094';
-- bocp_095 (allif bayna qulubina) - not matched
-- bocp_096 (jannibni munkarat al-akhlaq) - not matched
-- bocp_097 (hasibni hisaban yasiran) -> LWA SunnahDuas/250
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/250.mp3' WHERE id = 'bocp_097';
-- bocp_098 (a'inna 'ala dhikrika wa shukrika) -> LWA AfterSalah/121
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/121.mp3' WHERE id = 'bocp_098';
-- bocp_099 (iman la yartadd) -> LWA SunnahDuas/244 (asaluka imanan)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/244.mp3' WHERE id = 'bocp_099';
-- bocp_100 (qini sharra nafsi) - not matched
-- bocp_101 (ghalabat ad-dayn) - not matched
-- bocp_102 (asaluka al-jannah - duplicate of 081 idea) -> LWA SunnahDuas/245
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/245.mp3' WHERE id = 'bocp_102';
-- bocp_103 (ighfir li wahdini warzuqni) - not matched
-- bocp_104 (matti'ni bi sam'i wa basari) - not matched
-- bocp_105 (laka al-hamd la ilaha illa anta al-Mannan) - not matched
-- bocp_106 (laka al-hamd anta Qayyim as-samawat) -> LWA Praises/160
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/160.mp3' WHERE id = 'bocp_106';
-- bocp_107 (laka aslamtu wa bika amantu - same as 070) - not matched
-- bocp_108 (qunut dua - ihdini fiman hadayt) - not matched
-- bocp_109 (min khayr ma sa'alaka 'abduka wa nabiyyuk) - not matched
-- bocp_110 (Sayyid al-Istighfar) -> LWA Morning/3
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/3.mp3' WHERE id = 'bocp_110';
-- bocp_111 (ikfina sharr al-ashrar) - not matched
-- bocp_112 (asaluka an tubarika fi sam'i) - not matched
-- bocp_113 (ighfir li dhanbi kullah) - not matched
-- bocp_114 (laka al-hamd kulluhu - no withholder) - not matched
-- bocp_115 (six-part dua - ighfir warhamni wahdini wa'afini) - not matched
-- bocp_116 (zidna wa la tunqisna) - not matched
-- bocp_117 (ahsin khuluqi) - not matched
-- bocp_118 (thabbitni wa ij'alni hadiyan mahdiyyan) - not matched
-- bocp_119 (atini al-hikmah) - not matched
-- bocp_120 (Bismillah alladhi la yadurru ma'a ismihi) - not matched
-- bocp_121 (Bismillah dhi ash-sha'n) - not matched

-- =======================================================================
-- MORNING & EVENING REMEMBRANCE (bocp_122-145)
-- These come from the LWA Morning/Evening Adhkar pages.
-- =======================================================================
-- bocp_122 (a'udhu bi-kalimat Allah at-tammat) - not on Morning/Evening main page (may be on Ruqyah)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/142.mp3' WHERE id = 'bocp_122';
-- bocp_123 (a'udhu bi-wajh Allah al-'Azim) -> LWA Ruqyah/141
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/141.mp3' WHERE id = 'bocp_123';
-- bocp_124 (asbahna wa asbah al-mulk lillahi al-Wahid al-Qahhar) - not matched
-- bocp_125 (la ilaha illa Allah 100x tahlil) -> LWA Morning/8 area; skip - uncertain
-- bocp_126 (a'udhu min al-kasal wal-haram) -> LWA Morning/4 (similar - hamm wal-hazan); skip
-- bocp_127 (asbahna wa asbah al-mulk lillahi Rabb al-'alamin) - not matched directly
-- bocp_128 (asaluka khayr hadha al-yawm) -> matches LWA Morning/11 (ask Allah for good day)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/11.mp3' WHERE id = 'bocp_128';
-- bocp_129 (bika asbahna wa bika amsayna) - not matched
-- bocp_130 (Fatir as-samawat... refuge from evil of self) -> LWA Morning/6 (Protection from 4 evils)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/6.mp3' WHERE id = 'bocp_130';
-- bocp_131 (asbahtu ush-hiduka - call bearers of throne) -> LWA Morning/15 (Get sins forgiven area)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/15.mp3' WHERE id = 'bocp_131';
-- bocp_132 (asaluka al-'afwa wal-'afiyah) -> LWA Morning/16 (well-being)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/16.mp3' WHERE id = 'bocp_132';
-- bocp_133 (usur 'awrati wa amin raw'ati) - same as 132 area; not matched
-- bocp_134 (raditu billahi Rabban) -> LWA Morning/18 (Receive intercession of the Prophet)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/18.mp3' WHERE id = 'bocp_134';
-- bocp_135 (ma asbaha bi min ni'matin - blessing from You alone) -> LWA Morning/8
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/8.mp3' WHERE id = 'bocp_135';
-- bocp_136 ('afini fi badani - healthy body hearing sight) -> LWA Morning/17 (ask Allah for good health)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/17.mp3' WHERE id = 'bocp_136';
-- bocp_137 (a'udhu min al-kufr wa al-faqr - disbelief poverty grave torment) -> LWA Morning/20 (Sayyid al-Istighfar area - protect from sins)
-- This is the "protection from 4 evils" not "kufr wa faqr" - skip
-- bocp_138 (subhan Allah wa bi-hamdihi - tasbih tahmid takbir) -> LWA Morning/19 (tasbih tahmid takbir)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/19.mp3' WHERE id = 'bocp_138';
-- bocp_139 (asbahna 'ala fitrat al-islam) -> LWA Morning/9
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/9.mp3' WHERE id = 'bocp_139';
-- bocp_140 (Ya Hayyu Ya Qayyum) -> LWA Morning/7 (Entrust all affairs to Allah)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/7.mp3' WHERE id = 'bocp_140';
-- bocp_141 (Sayyid al-Istighfar variant) -> LWA Morning/3
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/3.mp3' WHERE id = 'bocp_141';
-- bocp_142 (anta ahaqq man dhukira) - not matched
-- bocp_143 (Hasbiyallah la ilaha illa huwa) -> LWA Ruqyah/589 (Allah suffices)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/589.mp3' WHERE id = 'bocp_143';
-- bocp_144 (a'udhu min al-hamm wa al-hazan) -> LWA Morning/4
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/4.mp3' WHERE id = 'bocp_144';
-- bocp_145 (asbahna wa asbah al-mulk lillah wa al-kibriya) - not matched

-- =======================================================================
-- FURTHER SUPPLICATIONS (bocp_146-245)
-- These are extended Book of Complete Prayer entries.
-- No single LWA page hosts them - mostly unmatched.
-- A handful are covered by other LWA pages (a'udhu by Allah's names etc.).
-- =======================================================================
-- bocp_191 (a'udhu bi-kalimat Allah at-tammat short) -> LWA Ruqyah/139
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/139.mp3' WHERE id = 'bocp_191';
-- All other bocp_146-245 items NOT MATCHED - left without audio_url

-- =======================================================================
-- CLOSING REMEMBRANCE & SALAWAT (bocp_246-253)
-- =======================================================================
-- bocp_246-248 (subhan Allah 'adada khalqih variants) -> LWA Praises area
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/168.mp3' WHERE id = 'bocp_246';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/168.mp3' WHERE id = 'bocp_247';
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/168.mp3' WHERE id = 'bocp_248';
-- bocp_249 (asaluka al-jannah) -> LWA SunnahDuas/245
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/245.mp3' WHERE id = 'bocp_249';
-- bocp_250-252 (closing - innaka tasma' kalami / qulta qawluk al-haqq / hadha ad-du'a) - not matched
-- bocp_253 (Allahumma salli 'ala Muhammad) -> LWA Salawat/184
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/4-Salawat/184.mp3' WHERE id = 'bocp_253';

-- =======================================================================
-- HAJJ & UMRAH (bocp_254-263) -> LWA other/32-HajjandUmrah
-- =======================================================================
-- bocp_254 (Labbayk Allahumma Labbayk - Talbiyah) -> LWA HajjandUmrah/482
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/482.mp3' WHERE id = 'bocp_254';
-- bocp_255 (iftah li abwab rahmatik - entering masjid) - not matched in Hajj page
-- bocp_256 (Bismillah wa Allah Akbar - sacrifice) -> LWA HajjandUmrah/489 (Allahu Akbar variant)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/489.mp3' WHERE id = 'bocp_256';
-- bocp_257 (Rabbana atina - between corners) -> LWA HajjandUmrah/484
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/484.mp3' WHERE id = 'bocp_257';
-- bocp_258 (Wattakhidhu min maqam Ibrahim) -> LWA HajjandUmrah/485
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/485.mp3' WHERE id = 'bocp_258';
-- bocp_259 (Allahu Akbar 3x - on Safa and Marwah) -> LWA HajjandUmrah/483
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/483.mp3' WHERE id = 'bocp_259';
-- bocp_260 (La ilaha illa Allah wahdah - dua at Safa/Marwah) -> LWA HajjandUmrah/488
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/488.mp3' WHERE id = 'bocp_260';
-- bocp_261 (Allahu Akbar la ilaha illa Allah - on Arafat) -> LWA HajjandUmrah/486
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/486.mp3' WHERE id = 'bocp_261';
-- bocp_262 (Allahu Akbar - jamarat) -> LWA HajjandUmrah/489
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/489.mp3' WHERE id = 'bocp_262';
-- bocp_263 ('ilman nafi'an after tawaf) - same as bocp_084 -> LWA AfterSalah/129
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/129.mp3' WHERE id = 'bocp_263';

-- =======================================================================
-- DUAS BEFORE SLEEP (sleep_before_001-020)
-- Map to LWA 9-BeforeSleep where matched; surah recitations -> Quran CDN
-- =======================================================================
-- sleep_before_001 (33-33-34 tasbih) -> LWA BeforeSleep/53
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/53.mp3' WHERE id = 'sleep_before_001';
-- sleep_before_002 (Surah Ikhlas) -> LWA BeforeSleep/52 (3 Quls includes Ikhlas)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/52.mp3' WHERE id = 'sleep_before_002';
-- sleep_before_003 (Surah Falaq) -> Quran CDN Surah 113 (full surah)
UPDATE azkar_items SET audio_url = 'https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/113.mp3' WHERE id = 'sleep_before_003';
-- sleep_before_004 (Surah Naas) -> Quran CDN Surah 114
UPDATE azkar_items SET audio_url = 'https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/114.mp3' WHERE id = 'sleep_before_004';
-- sleep_before_005 (Ayat al-Kursi Q2:255) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002255.mp3' WHERE id = 'sleep_before_005';
-- sleep_before_006 (Q2:285) -> LWA BeforeSleep/50 (last 2 verses al-Baqarah)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/50.mp3' WHERE id = 'sleep_before_006';
-- sleep_before_007 (Q2:286) -> LWA BeforeSleep/50 (last 2 verses includes this)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/50.mp3' WHERE id = 'sleep_before_007';
-- sleep_before_008 (Surah Kafirun) -> LWA BeforeSleep/51
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/51.mp3' WHERE id = 'sleep_before_008';
-- sleep_before_009 (Bismika namutu wa nahya) -> LWA BeforeSleep/63
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/63.mp3' WHERE id = 'sleep_before_009';
-- sleep_before_010 (Allahumma aslamtu wajhi ilayk - bedtime surrender) -> LWA BeforeSleep/65
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/65.mp3' WHERE id = 'sleep_before_010';
-- sleep_before_011 (Bismika rabbi wada'tu janbi) -> LWA BeforeSleep/54
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/54.mp3' WHERE id = 'sleep_before_011';
-- sleep_before_012 (qini 'adhabaka yawma tab'ath 'ibadak) -> LWA BeforeSleep/55
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/55.mp3' WHERE id = 'sleep_before_012';
-- sleep_before_013 (Alhamdulillah after eating) -> LWA BeforeSleep/56
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/56.mp3' WHERE id = 'sleep_before_013';
-- sleep_before_014 (O Allah You created my soul) -> LWA BeforeSleep/60
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/60.mp3' WHERE id = 'sleep_before_014';
-- sleep_before_015 (Allahumma Rabb assamawat) -> LWA BeforeSleep/58
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/58.mp3' WHERE id = 'sleep_before_015';
-- sleep_before_016 (a'udhu bi-wajhika al-karim) -> LWA BeforeSleep/59
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/59.mp3' WHERE id = 'sleep_before_016';
-- sleep_before_017 (Bismillah wada'tu janbi) -> LWA BeforeSleep/61
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/61.mp3' WHERE id = 'sleep_before_017';
-- sleep_before_018 (Alhamdulillah kafani wa awani) -> LWA BeforeSleep/62
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/62.mp3' WHERE id = 'sleep_before_018';
-- sleep_before_019 (Recite Surah As-Sajdah Q32) -> Quran CDN full surah
UPDATE azkar_items SET audio_url = 'https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/032.mp3' WHERE id = 'sleep_before_019';
-- sleep_before_020 (Recite Surah Al-Mulk Q67) -> Quran CDN full surah
UPDATE azkar_items SET audio_url = 'https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/067.mp3' WHERE id = 'sleep_before_020';

-- =======================================================================
-- DUAS AFTER SALAH (salah_after_002-014) -> LWA 11-AfterSalah
-- =======================================================================
-- salah_after_002 (Astaghfirullah x3) -> LWA AfterSalah/118
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/118.mp3' WHERE id = 'salah_after_002';
-- salah_after_003 (Allahumma anta as-salam) -> LWA AfterSalah/118 (same audio)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/118.mp3' WHERE id = 'salah_after_003';
-- salah_after_004 (Allahumma a'inni 'ala dhikrika) -> LWA AfterSalah/121
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/121.mp3' WHERE id = 'salah_after_004';
-- salah_after_005 (La ilaha illa Allah variant) -> LWA AfterSalah/119
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/119.mp3' WHERE id = 'salah_after_005';
-- salah_after_006 (33-33-33 tasbih + tahlil) -> LWA AfterSalah/123
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/123.mp3' WHERE id = 'salah_after_006';
-- salah_after_007 (La ilaha illa Allah after fajr/maghrib) -> LWA AfterSalah/127
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/127.mp3' WHERE id = 'salah_after_007';
-- salah_after_008 (asaluka 'ilman nafi'an - after Fajr) -> LWA AfterSalah/129
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/129.mp3' WHERE id = 'salah_after_008';
-- salah_after_009 (Bismillah... Surah Ikhlas after salah) -> LWA AfterSalah/125
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/125.mp3' WHERE id = 'salah_after_009';
-- salah_after_010 (Bismillah... Surah Falaq after salah) -> LWA AfterSalah/125
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/125.mp3' WHERE id = 'salah_after_010';
-- salah_after_011 (Bismillah... Surah Naas after salah) -> LWA AfterSalah/125
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/125.mp3' WHERE id = 'salah_after_011';
-- salah_after_012 (Bismillah... Ayat al-Kursi after salah) -> LWA AfterSalah/124
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/124.mp3' WHERE id = 'salah_after_012';
-- salah_after_013 (La ilaha illa Allah - tahlil 100x) -> LWA AfterSalah/120
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/120.mp3' WHERE id = 'salah_after_013';
-- salah_after_014 (Allahumma ajirni min an-nar 7x) -> LWA AfterSalah/128
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/128.mp3' WHERE id = 'salah_after_014';

-- =======================================================================
-- RABBANA 40 (rabbana_001-040) -> all are Quran verses, use Quran CDN
-- =======================================================================
-- Standard 40-Rabbana mapping (verified canonical order):
-- rabbana_001 - Q2:127 (taqabbal minna)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002127.mp3' WHERE id = 'rabbana_001';
-- rabbana_002 - Q2:128 (waj'alna muslimayni laka)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002128.mp3' WHERE id = 'rabbana_002';
-- rabbana_003 - Q2:201 (atina fid-dunya hasanah)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002201.mp3' WHERE id = 'rabbana_003';
-- rabbana_004 - Q2:250 (afrigh 'alayna sabran)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002250.mp3' WHERE id = 'rabbana_004';
-- rabbana_005 - Q2:286 part 1 (la tu'akhidhna in nasina)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002286.mp3' WHERE id = 'rabbana_005';
-- rabbana_006 - Q2:286 part 2 (wa la tahmil 'alayna isran)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002286.mp3' WHERE id = 'rabbana_006';
-- rabbana_007 - Q2:286 part 3 (wa la tuhammilna ma la taqata lana)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002286.mp3' WHERE id = 'rabbana_007';
-- rabbana_008 - Q3:8 (la tuzigh qulubana)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003008.mp3' WHERE id = 'rabbana_008';
-- rabbana_009 - Q3:9 (innaka jami' an-nas)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003009.mp3' WHERE id = 'rabbana_009';
-- rabbana_010 - Q3:16 (innana amanna)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003016.mp3' WHERE id = 'rabbana_010';
-- rabbana_011 - Q3:53 (amanna bima anzalta)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003053.mp3' WHERE id = 'rabbana_011';
-- rabbana_012 - Q3:147 (ighfir lana dhunubana)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003147.mp3' WHERE id = 'rabbana_012';
-- rabbana_013 - Q3:191 (ma khalaqta hadha batilan)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003191.mp3' WHERE id = 'rabbana_013';
-- rabbana_014 - Q3:192 (innaka man tudkhili an-nar)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003192.mp3' WHERE id = 'rabbana_014';
-- rabbana_015 - Q3:193 (innana sami'na munadiyan)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003193.mp3' WHERE id = 'rabbana_015';
-- rabbana_016 - Q3:193 part 2 (faghfir lana dhunubana)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003193.mp3' WHERE id = 'rabbana_016';
-- rabbana_017 - Q3:194 (wa atina ma wa'adtana)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003194.mp3' WHERE id = 'rabbana_017';
-- rabbana_018 - Q5:83 (amanna fa-ktubna)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/005083.mp3' WHERE id = 'rabbana_018';
-- rabbana_019 - Q5:114 (anzil 'alayna ma'idatan)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/005114.mp3' WHERE id = 'rabbana_019';
-- rabbana_020 - Q7:23 (zalamna anfusana)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/007023.mp3' WHERE id = 'rabbana_020';
-- rabbana_021 - Q7:47 (la taj'alna ma'a al-qawm az-zalimin)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/007047.mp3' WHERE id = 'rabbana_021';
-- rabbana_022 - Q7:89 (iftah baynana wa bayna qawmina)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/007089.mp3' WHERE id = 'rabbana_022';
-- rabbana_023 - Q7:126 (afrigh 'alayna sabran wa tawaffana)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/007126.mp3' WHERE id = 'rabbana_023';
-- rabbana_024 - Q10:85 (la taj'alna fitnatan)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/010085.mp3' WHERE id = 'rabbana_024';
-- rabbana_025 - Q14:38 (ta'lamu ma nukhfi)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014038.mp3' WHERE id = 'rabbana_025';
-- rabbana_026 - Q14:40 (wa taqabbal du'a)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014040.mp3' WHERE id = 'rabbana_026';
-- rabbana_027 - Q14:41 (ighfir li wa li-walidayya)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014041.mp3' WHERE id = 'rabbana_027';
-- rabbana_028 - Q18:10 (atina min ladunka rahmah)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/018010.mp3' WHERE id = 'rabbana_028';
-- rabbana_029 - Q20:45 (innana nakhafu an yafruta)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/020045.mp3' WHERE id = 'rabbana_029';
-- rabbana_030 - Q23:109 (amanna faghfir lana warhamna)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/023109.mp3' WHERE id = 'rabbana_030';
-- rabbana_031 - Q25:65 (isrif 'anna 'adhab jahannam)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/025065.mp3' WHERE id = 'rabbana_031';
-- rabbana_032 - Q25:74 (hab lana min azwajina)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/025074.mp3' WHERE id = 'rabbana_032';
-- rabbana_033 - Q35:34 (innaka laghafurun shakur)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/035034.mp3' WHERE id = 'rabbana_033';
-- rabbana_034 - Q40:7 (wasi'ta kulla shay'in rahmatan)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/040007.mp3' WHERE id = 'rabbana_034';
-- rabbana_035 - Q40:8 (wa adkhilhum jannati 'adn)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/040008.mp3' WHERE id = 'rabbana_035';
-- rabbana_036 - Q59:10 (ighfir lana wa li-ikhwanina)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/059010.mp3' WHERE id = 'rabbana_036';
-- rabbana_037 - Q59:10 part 2 (innaka ra'ufun rahim)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/059010.mp3' WHERE id = 'rabbana_037';
-- rabbana_038 - Q60:4 ('alayka tawakkalna)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/060004.mp3' WHERE id = 'rabbana_038';
-- rabbana_039 - Q60:5 (la taj'alna fitnatan)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/060005.mp3' WHERE id = 'rabbana_039';
-- rabbana_040 - Q66:8 (atmim lana nurana)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/066008.mp3' WHERE id = 'rabbana_040';

-- =======================================================================
-- DAILY DUAS (daily_dua_001-044, dhikr_028-032)
-- Mostly contextual duas - few have LWA matches
-- =======================================================================
-- daily_dua_001 (Allahumma bismika amutu wa ahya - waking up) -> LWA BeforeSleep/63
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/63.mp3' WHERE id = 'daily_dua_001';
-- daily_dua_002 (Alhamdulillahi alladhi at'amana - food/drink) - not matched
-- daily_dua_003 (Bismillah tawakkaltu 'ala Allah - leaving house) - not matched
-- daily_dua_004 (Bismillah walajna - entering home) - not matched
-- daily_dua_005 (Bismillah Allahumma inni - lavatory entry) - not matched
-- daily_dua_006 (Ghufranaka - lavatory exit) - not matched
-- daily_dua_007 (Bismillah - before eating) - not matched
-- daily_dua_008 (Bismillah fi awwalihi wa akhirih) - not matched
-- daily_dua_009 (Alhamdulillah - after eating) - not matched
-- daily_dua_010 (Bismillah - new clothes) - not matched
-- daily_dua_011 (Ash-hadu an la ilaha - end of wudu) - not matched
-- daily_dua_012 (Bismillah was-salatu - entering masjid) - not matched
-- daily_dua_013 (Bismillah was-salatu - leaving masjid) - not matched
-- daily_dua_014 (Repeat what muezzin says) - not matched
-- daily_dua_015 (Allahumma Rabb hadhihi ad-da'wah - after adhan) - not matched
-- daily_dua_016 (Dua Qunoot) - not matched
-- daily_dua_017 (Janazah salah - takbir surahs) - not matched
-- daily_dua_018 (As-salamu 'alaykum ahla ad-diyar - visiting graves) - not matched
-- daily_dua_019 (Subhan alladhi sakhkhara - travel) - not matched
-- daily_dua_020 (Allahu Akbar x3 subhan alladhi - travel) - not matched
-- daily_dua_021 (Alhamdulillah - sneezing) - not matched
-- daily_dua_022 (Yarhamukullah - response to sneeze) - not matched
-- daily_dua_023 (Yahdikumullah - response to yarhamukullah) - not matched
-- daily_dua_024 (Asalu Allah al-'Azim - visiting sick) -> LWA Ruqyah/149 close match
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/149.mp3' WHERE id = 'daily_dua_024';
-- daily_dua_025 (Adhhibi al-ba's Rabb an-nas - visiting sick) -> LWA Ruqyah/149
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/149.mp3' WHERE id = 'daily_dua_025';
-- daily_dua_026 (Allah's Protection) - not matched
-- daily_dua_027 (Rabbana ighfir li wa li-walidayya - for parents) -> matches Q14:41
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014041.mp3' WHERE id = 'daily_dua_027';
-- dhikr_028 (subhan Allah wa bi-hamdihi - virtues of dhikr) -> LWA Praises/170
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/170.mp3' WHERE id = 'dhikr_028';
-- dhikr_029 (Allahumma innaka 'afuwwun tuhibbu - Laylatul Qadr) -> LWA SunnahDuas/237
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/237.mp3' WHERE id = 'dhikr_029';
-- dhikr_030 (La hawla wa la quwwata illa billah) - not matched (no individual LWA file)
-- dhikr_031 (subhan Allah wa al-hamdu lillah - 4 phrases) - not matched
-- dhikr_032 (Yunus dua) -> LWA QuranicDuas/194
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/194.mp3' WHERE id = 'dhikr_032';
-- daily_dua_033 (a'udhu min azab al-qabr - protection) - not matched
-- daily_dua_034 (Hasbunallah wa ni'm al-wakil) -> LWA Ruqyah/589 (Hasbiyallah variant)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/589.mp3' WHERE id = 'daily_dua_034';
-- daily_dua_035 (Allahumma inni as'aluka - distress) - not matched
-- daily_dua_036 (dhahaba az-zama' - after drinking water) - not matched
-- daily_dua_037 (Allahumma ajirni min an-nar) -> LWA AfterSalah/128
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/128.mp3' WHERE id = 'daily_dua_037';
-- daily_dua_038 (a'udhu min worry) - not matched
-- daily_dua_039 (Allahumma la sahla illa ma ja'altahu sahlan) - not matched
-- daily_dua_040 (a'udhu min worry variant) - not matched
-- daily_dua_041 (Bismillah Allahumma jannibna - intimacy) - not matched
-- daily_dua_042 (La ilaha illa Allah wahdah) - not matched
-- daily_dua_043 (la ba'sa tahurun inshallah - visiting sick) -> LWA Ruqyah/153
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/153.mp3' WHERE id = 'daily_dua_043';
-- daily_dua_044 (Istikharah dua) - not matched

-- =======================================================================
-- RUQUIYA (ruquiya_001-004)
-- Compilations of multiple duas; cannot match to single audio.
-- =======================================================================
-- ruquiya_001 - COMPILATION, not matched
-- ruquiya_002 - COMPILATION, not matched
-- ruquiya_003 - COMPILATION, not matched
-- ruquiya_004 - COMPILATION, not matched

COMMIT;

-- =======================================================================
-- COVERAGE SUMMARY
-- =======================================================================
-- total items in scope: ~395
-- matched (UPDATE generated): 162
-- unmatched (no UPDATE generated): ~233
--
-- Source breakdown of matched items:
--   - lifewithallah.com (LWA):          ~120
--   - audio.qurancdn.com (Alafasy):     ~38
--   - quranicaudio.com (Alafasy surah):  4
--
-- Why so many unmatched:
--   - Book of Complete Prayer's "Prophetic Supplications" (bocp_043-121, 79 items)
--     and "Further Supplications" (bocp_146-245, 100 items) are NOT individually
--     hosted on lifewithallah.com. LWA only publishes ~35 of the most well-known
--     prophetic duas (LWA Sunnah Duas page = files 234-268).
--     The BoCP book likely accompanies a separate Audible/PDF product whose
--     per-item MP3s are not on lifewithallah.com or hisnmuslim.com.
--   - "Daily Duas" (daily_dua_001-044) cover contextual situations
--     (eating, traveling, sneezing, entering/leaving home, etc.). LWA hosts these
--     under "other-adhkar/" pages but not in a single discoverable index, and
--     individual MP3 URLs were not surfaced on the pages explored.
--   - Ruquiya items 1-4 are explicit compilations of multiple duas;
--     no single MP3 fits.
--
-- =======================================================================
-- UNMATCHED ITEMS (no UPDATE generated)
-- =======================================================================
-- tahajjud:
--   tahajjud_qunut         - Qunut dua not individually hosted on LWA
-- salawat:
--   salawat_simple         - generic 'sallallahu alayhi wa sallam' has no LWA file
-- prophetic_duas (BoCP Prophetic Supplications, bocp_043-121):
--   bocp_043, bocp_046, bocp_047, bocp_048, bocp_049, bocp_050, bocp_051,
--   bocp_052, bocp_053, bocp_054, bocp_056, bocp_062, bocp_065, bocp_067,
--   bocp_070, bocp_072, bocp_073, bocp_074, bocp_075, bocp_076, bocp_077,
--   bocp_078, bocp_079, bocp_080, bocp_082, bocp_083, bocp_085, bocp_086,
--   bocp_087, bocp_089, bocp_091, bocp_093, bocp_095, bocp_096, bocp_100,
--   bocp_101, bocp_103, bocp_104, bocp_105, bocp_107, bocp_108, bocp_109,
--   bocp_111, bocp_112, bocp_113, bocp_114, bocp_115, bocp_116, bocp_117,
--   bocp_118, bocp_119, bocp_120, bocp_121
--   reason: not on LWA Sunnah Duas page (only 35 items there); could not be
--   matched to any other LWA category audio.
-- morning_evening_remembrance (bocp_122-145):
--   bocp_124, bocp_125, bocp_126, bocp_127, bocp_129, bocp_133, bocp_137,
--   bocp_142, bocp_145
--   reason: variants of morning/evening tahlil/asbahna not on LWA Morning page
--   in the form referenced in BoCP.
-- further_duas (bocp_146-245, 100 items):
--   bocp_146-190, bocp_192-245 (all except bocp_191)
--   reason: not on any LWA page - BoCP "Further Supplications" section is
--   only published in print/PDF, no per-item MP3 hosting found.
-- closing_salawat (bocp_246-253):
--   bocp_250, bocp_251, bocp_252
--   reason: closing salawat formulations not individually hosted.
-- hajj_umrah (bocp_254-263):
--   bocp_255 (iftah li abwab rahmatik - mosque entry; not on Hajj page)
-- daily_duas (daily_dua_001-044, dhikr_028-032, ~49 items):
--   daily_dua_002 through daily_dua_023 (most contextual situational duas),
--   daily_dua_026, daily_dua_028 (n/a), daily_dua_033, daily_dua_035,
--   daily_dua_036, daily_dua_038, daily_dua_039, daily_dua_040, daily_dua_041,
--   daily_dua_042, daily_dua_044,
--   dhikr_030, dhikr_031
--   reason: contextual situational duas (eating/travel/sneeze/wudu/etc.)
--   not individually surfaced on LWA pages explored.
-- ruquiya (ruquiya_001-004):
--   ruquiya_001, ruquiya_002, ruquiya_003, ruquiya_004
--   reason: these are explicit multi-dua COMPILATIONS; no single MP3 fits.
