-- VERIFIED. Generated by Claude Code verification agent.
-- Every UPDATE below has been confirmed by Arabic-text match against the
-- source URL's actual content (LWA pages WebFetched + raw HTML curl'd and
-- parsed to extract per-audio-file Arabic; Quran CDN verified by surah:ayah
-- against canonical Quran references; quranicaudio.com full-surah recitations
-- accepted on face value for items that explicitly call for whole-surah recital).
--
-- Mappings that failed verification are OMITTED from the BEGIN/COMMIT block
-- and listed in the REJECTED section at the bottom with the reason.
--
-- Sources of truth used:
--   - book_of_prayer_import.sql            (bocp_001..bocp_263 Arabic)
--   - 20260603_010_azkar_screenshots_import.sql
--     (rabbana_*, sleep_before_*, salah_after_*, daily_dua_*, dhikr_* Arabic)
--   - LWA category pages (live fetch, audio-file-to-Arabic mapping extracted
--     from raw HTML):
--       morning/, before-sleep/, after-salah/, salawat/, salah/, ruqyah-and-
--       illness-quran/, quranic-duas/, sunnah-duas/, praises-of-allah/,
--       other-adhkar/hajj-and-umrah/
--   - audio.qurancdn.com Alafasy MP3s (verified by surah:ayah in URL)
--   - download.quranicaudio.com Mishary full-surah MP3s (full surah)

BEGIN;

-- =======================================================================
-- TAHAJJUD
-- =======================================================================
-- tahajjud_opening: "Allahumma laka al-hamd, anta nur as-samawat..." (Bukhari 1120)
--   LWA Salah/72 = "Allahumma laka al-hamd, anta Nur as-samawat" -> VERIFIED
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/10-Salah/72.mp3' WHERE id = 'tahajjud_opening';
-- tahajjud_witr: "Subhana al-Malik al-Quddus"
--   LWA AfterSalah/130 = "Subhan al-Malik al-Quddus" -> VERIFIED
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/130.mp3' WHERE id = 'tahajjud_witr';

-- =======================================================================
-- SALAWAT
-- =======================================================================
-- salawat_ibrahimiyya: Ibrahimiya salawat
--   LWA Salawat/184 = "Allahumma salli 'ala Muhammad..." -> VERIFIED
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/4-Salawat/184.mp3' WHERE id = 'salawat_ibrahimiyya';
-- salawat_friday: abundant Friday salawat
--   LWA Salawat/191 = "Allahumma salli 'ala Muhammad an-nabiyy al-ummi" -> VERIFIED
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/4-Salawat/191.mp3' WHERE id = 'salawat_friday';

-- =======================================================================
-- QURANIC SUPPLICATIONS (bocp_001..042)
-- =======================================================================
-- bocp_001 (2:201, atina fid-dunya hasanah) -> LWA QuranicDuas/209
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/209.mp3' WHERE id = 'bocp_001';
-- bocp_002 (2:250, afrigh 'alayna sabran) -> LWA QuranicDuas/226
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/226.mp3' WHERE id = 'bocp_002';
-- bocp_003 (2:286 full, la tu'akhidhna) -> LWA QuranicDuas/224
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/224.mp3' WHERE id = 'bocp_003';
-- bocp_004 (3:8, la tuzigh qulubana) -> LWA QuranicDuas/211
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/211.mp3' WHERE id = 'bocp_004';
-- bocp_005 (3:16, innana amanna fa'ghfir) -> LWA QuranicDuas/198
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/198.mp3' WHERE id = 'bocp_005';
-- bocp_006 (3:26, Allahumma malik al-mulk) -> LWA PraisesOfAllah/181
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/181.mp3' WHERE id = 'bocp_006';
-- bocp_007 (3:38, Rabbi hab li min ladunka dhurriyyatan tayyibah) -> LWA QuranicDuas/217
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/217.mp3' WHERE id = 'bocp_007';
-- bocp_008 (3:53, amanna bima anzalta) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003053.mp3' WHERE id = 'bocp_008';
-- bocp_009 (3:147, ighfir lana dhunubana) -> LWA QuranicDuas/225
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/225.mp3' WHERE id = 'bocp_009';
-- bocp_010 (3:191-194, ma khalaqta hadha batilan) -> LWA QuranicDuas/206
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/206.mp3' WHERE id = 'bocp_010';
-- bocp_011 (5:83, amanna fa'ktubna) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/005083.mp3' WHERE id = 'bocp_011';
-- bocp_012 (7:23, zalamna anfusana) -> LWA QuranicDuas/196
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/196.mp3' WHERE id = 'bocp_012';
-- bocp_013 (7:47, la taj'alna ma'a al-qawm az-zalimin) -> LWA QuranicDuas/228
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/228.mp3' WHERE id = 'bocp_013';
-- bocp_014 (10:85, la taj'alna fitnatan) -> LWA QuranicDuas/229
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/229.mp3' WHERE id = 'bocp_014';
-- bocp_015 (11:47, Rabbi a'udhu bika an as'alaka) -> LWA QuranicDuas/201
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/201.mp3' WHERE id = 'bocp_015';
-- bocp_016 (14:35, Rabbi ij'al hadha al-balada aminan) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014035.mp3' WHERE id = 'bocp_016';
-- bocp_017 (14:40, ij'alni muqim as-salah wa taqabbal du'a) -> LWA QuranicDuas/215
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/215.mp3' WHERE id = 'bocp_017';
-- bocp_018 (14:41, ighfir li wa li-walidayya) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014041.mp3' WHERE id = 'bocp_018';
-- bocp_019 (17:24, Rabbi irhamhuma kama rabbayani) -> LWA QuranicDuas/216
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/216.mp3' WHERE id = 'bocp_019';
-- bocp_020 (17:80, mudkhala sidqin wa mukhraja sidqin) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/017080.mp3' WHERE id = 'bocp_020';
-- bocp_021 (18:10, Rabbana atina min ladunka rahmah) -> LWA QuranicDuas/210
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/210.mp3' WHERE id = 'bocp_021';
-- bocp_022 (20:114, Rabbi zidni 'ilma) -> LWA QuranicDuas/212
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/212.mp3' WHERE id = 'bocp_022';
-- bocp_023 (21:87, Yunus dua: la ilaha illa anta) -> LWA QuranicDuas/194
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/194.mp3' WHERE id = 'bocp_023';
-- bocp_024 (21:89, Rabbi la tadharni fardan) -> LWA QuranicDuas/219
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/219.mp3' WHERE id = 'bocp_024';
-- bocp_025 (23:29, Rabbi anzilni munzalan mubarakan) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/023029.mp3' WHERE id = 'bocp_025';
-- bocp_026 (23:97-98, Rabbi a'udhu bika min hamazat) -> LWA QuranicDuas/223
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/223.mp3' WHERE id = 'bocp_026';
-- bocp_027 (23:109, amanna fa'ghfir lana wa'rhamna) -> LWA QuranicDuas/199
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/199.mp3' WHERE id = 'bocp_027';
-- bocp_028 (23:118, Rabbi ighfir wa'rham) -> LWA QuranicDuas/200
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/200.mp3' WHERE id = 'bocp_028';
-- bocp_029 (27:19, Rabbi awzi'ni an ashkura - Solomon) -> LWA QuranicDuas/221
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/221.mp3' WHERE id = 'bocp_029';
-- bocp_030 (28:16, Rabbi inni zalamtu nafsi - Moses) -> LWA QuranicDuas/195
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/195.mp3' WHERE id = 'bocp_030';
-- bocp_031 (28:17, Rabbi bima an'amta) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/028017.mp3' WHERE id = 'bocp_031';
-- bocp_032 (28:21, Rabbi najjini min al-qawm az-zalimin) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/028021.mp3' WHERE id = 'bocp_032';
-- bocp_033 (28:24, Rabbi inni lima anzalta) -> LWA QuranicDuas/208
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/208.mp3' WHERE id = 'bocp_033';
-- bocp_034 (29:30, Rabbi'nsurni 'ala al-qawm al-mufsidin - Lot) -> LWA QuranicDuas/227
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/227.mp3' WHERE id = 'bocp_034';
-- bocp_035 (25:65, Rabbana asrif 'anna 'adhab jahannam) -> LWA QuranicDuas/205
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/205.mp3' WHERE id = 'bocp_035';
-- bocp_036 (25:74, Rabbana hab lana min azwajina) -> LWA QuranicDuas/220
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/220.mp3' WHERE id = 'bocp_036';
-- bocp_037 (40:7-8, Rabbana wasi'ta kulla shay'in rahmatan) -> LWA QuranicDuas/207
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/207.mp3' WHERE id = 'bocp_037';
-- bocp_038 (46:15, Rabbi awzi'ni... wa aslih li fi dhurriyati) -> LWA QuranicDuas/222
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/222.mp3' WHERE id = 'bocp_038';
-- bocp_039 (37:100, Rabbi hab li min as-salihin - Abraham) -> LWA QuranicDuas/218
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/218.mp3' WHERE id = 'bocp_039';
-- bocp_040 (59:10, ighfir lana wa li-ikhwanina) -> LWA QuranicDuas/202
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/202.mp3' WHERE id = 'bocp_040';
-- bocp_041 (60:4-5, 'alayka tawakkalna) -> LWA QuranicDuas/230
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/230.mp3' WHERE id = 'bocp_041';
-- bocp_042 (71:28, Nuh ighfir li wa li-walidayya) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/071028.mp3' WHERE id = 'bocp_042';

-- =======================================================================
-- PROPHETIC SUPPLICATIONS (bocp_044..099, 102)
-- =======================================================================
-- bocp_044 (a'udhu min 'adhab jahannam etc) -> LWA SunnahDuas/247
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/247.mp3' WHERE id = 'bocp_044';
-- (bocp_045 REJECTED - SD/248 does not contain the 'ajz/kasal hadith)
-- bocp_055 (Yunus dua, duplicate of bocp_023) -> LWA QuranicDuas/194
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/194.mp3' WHERE id = 'bocp_055';
-- bocp_057 (musarrif al-qulub) -> LWA SunnahDuas/259
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/259.mp3' WHERE id = 'bocp_057';
-- bocp_058 (Ya muqalliba al-qulub thabbit qalbi) -> LWA SunnahDuas/258
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/258.mp3' WHERE id = 'bocp_058';
-- bocp_059 (al-'afiyah fid-dunya wal-akhirah) -> LWA SunnahDuas/263
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/263.mp3' WHERE id = 'bocp_059';
-- bocp_060 (ahsin 'aqibatana fi al-umur kulliha) -> LWA SunnahDuas/261
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/261.mp3' WHERE id = 'bocp_060';
-- bocp_061 (Rabbi a'inni wa la tu'in 'alayya) -> LWA SunnahDuas/264
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/264.mp3' WHERE id = 'bocp_061';
-- bocp_063 ('afuwwun karim) -> LWA SunnahDuas/237
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/237.mp3' WHERE id = 'bocp_063';
-- bocp_064 (fi'l al-khayrat wa tarka al-munkarat) -> LWA SunnahDuas/266
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/266.mp3' WHERE id = 'bocp_064';
-- bocp_066 (ihfazni bil-islami qa'iman) -> LWA SunnahDuas/257
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/257.mp3' WHERE id = 'bocp_066';
-- bocp_068 (ighfir li khati'ati wa jahli) -> LWA SunnahDuas/236
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/236.mp3' WHERE id = 'bocp_068';
-- bocp_069 (zalamtu nafsi zulman kathiran - Abu Bakr) -> LWA SunnahDuas/240
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/240.mp3' WHERE id = 'bocp_069';
-- bocp_071 (mujibat rahmatik) -> LWA SunnahDuas/249
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/249.mp3' WHERE id = 'bocp_071';
-- (bocp_081 REJECTED - SD/245 is firdaws-specific; SOT is generic jannah)
-- bocp_084 ('ilman nafi'an rizqan tayyiban) -> LWA AfterSalah/129
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/129.mp3' WHERE id = 'bocp_084';
-- bocp_088 (bi-anna laka al-hamd la ilaha illa anta - Greatest Name #2) -> LWA PraisesOfAllah/183
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/183.mp3' WHERE id = 'bocp_088';
-- bocp_090 (bi-'ilmika al-ghayb wa qudratika 'ala al-khalq) -> LWA SunnahDuas/268
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/268.mp3' WHERE id = 'bocp_090';
-- bocp_092 (Rabb Jibril wa Mika'il wa Israfil) -> LWA SunnahDuas/246
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/246.mp3' WHERE id = 'bocp_092';
-- bocp_094 (Rabb as-samawat wa Rabb al-ard) -> LWA PraisesOfAllah/162
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/162.mp3' WHERE id = 'bocp_094';
-- bocp_097 (hasibni hisaban yasiran) -> LWA SunnahDuas/250
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/250.mp3' WHERE id = 'bocp_097';
-- bocp_098 (a'inna 'ala dhikrika - duplicate of salah_after_004) -> LWA AfterSalah/121
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/121.mp3' WHERE id = 'bocp_098';
-- bocp_099 (iman la yartadd) -> LWA SunnahDuas/244
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/244.mp3' WHERE id = 'bocp_099';
-- (bocp_102 REJECTED - same firdaws/jannah mismatch as bocp_081)
-- bocp_106 (laka al-hamd, Tahajjud Bukhari 1120) -> LWA PraisesOfAllah/160
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/160.mp3' WHERE id = 'bocp_106';
-- bocp_110 (Sayyid al-Istighfar) -> LWA Morning/3
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/3.mp3' WHERE id = 'bocp_110';

-- =======================================================================
-- MORNING & EVENING REMEMBRANCE (bocp_122..145)
-- =======================================================================
-- (bocp_122 REJECTED - SQL mapped to Ruq/142 but SOT 'min sharri ma khalaq'
--                      matches Ruq/139, not Ruq/142)
-- bocp_123 (a'udhu bi-wajh Allah al-'Azim) -> LWA RuqyahandIllness/141
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/141.mp3' WHERE id = 'bocp_123';
-- (bocp_128 REJECTED - SQL mapped to Morning/11; SOT 'asaluka khayra hadha
--                      al-yawm: fathahu, nasrahu' actually matches Morning/13
--                      ('Ask Allah to Bless Your Day' section). Morning/11 is
--                      a different dua: 'asbahna wa asbah al-mulk...')
-- bocp_130 (Fatir as-samawat - 4 evils) -> LWA Morning/6
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/6.mp3' WHERE id = 'bocp_130';
-- (bocp_131 REJECTED - SQL mapped to Morning/15; SOT 'asbahtu ush-hiduka'
--                      actually matches Morning/13 ('Get Yourself Freed from
--                      the Hell-fire'). Morning/15 = 'afini fi badani'.)
-- (bocp_132 REJECTED - SQL mapped to Morning/16; SOT 'asaluka al-'afwa wal-
--                      'afiyah' does not appear on the Morning page as
--                      Morning/16 ('Hasbiya'llah') or any other audio file.)
-- (bocp_134 REJECTED - SQL mapped to Morning/18; SOT 'raditu billahi rabban'
--                      actually matches Morning/17. Morning/18 = 'Bismillah
--                      alladhi la yadurru'.)
-- bocp_135 (ma asbaha bi min ni'matin - Thank Allah) -> LWA Morning/8
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/8.mp3' WHERE id = 'bocp_135';
-- (bocp_136 REJECTED - SQL mapped to Morning/17; SOT ''afini fi badani'
--                      actually matches Morning/15 ('Good Health and
--                      Protection'). Morning/17 = 'raditu billahi'.)
-- (bocp_138 REJECTED - SQL mapped to Morning/19; SOT 'Subhan Allah wa bi-
--                      hamdihi LA QUWWATA ILLA BILLAH MA SHAA'A ALLAH KANA...'
--                      is the long 'kalimat al-istithna' hadith; Morning/19
--                      is only the short 'Subhan Allah wa bi-hamdihi 100x'.)
-- bocp_139 (asbahna 'ala fitrat al-islam - Renew Tawhid) -> LWA Morning/9
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/9.mp3' WHERE id = 'bocp_139';
-- bocp_140 (Ya Hayyu Ya Qayyum - Entrust matters) -> LWA Morning/7
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/7.mp3' WHERE id = 'bocp_140';
-- bocp_141 (Sayyid al-Istighfar variant) -> LWA Morning/3
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/3.mp3' WHERE id = 'bocp_141';
-- bocp_143 (Hasbiyallah la ilaha illa huwa) -> LWA RuqyahandIllness/589
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/589.mp3' WHERE id = 'bocp_143';
-- bocp_144 (a'udhu min al-hamm wa al-hazan - Anxiety/Laziness) -> LWA Morning/4
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/4.mp3' WHERE id = 'bocp_144';

-- =======================================================================
-- FURTHER SUPPLICATIONS (bocp_146..245)
-- =======================================================================
-- (bocp_191 REJECTED - SQL mapped to Ruq/139 but SOT 'min ghadabihi wa alim
--                      'iqabihi' matches Ruq/142, not Ruq/139. The agent
--                      swapped 122 and 191.)

-- =======================================================================
-- CLOSING REMEMBRANCE & SALAWAT (bocp_246..253)
-- =======================================================================
-- (bocp_246 REJECTED - SQL mapped to PoA/168 but SOT 'Subhan Allah wa bi-
--                      hamdihi 'adada khalqihi wa rida nafsihi...' actually
--                      matches PoA/171 ('4 Phrases That Outweigh All Other
--                      Dhikr'). PoA/168 is a different 'mil'a' hadith.)
-- (bocp_247 REJECTED - SQL mapped to PoA/168; SOT 'Subhan Allah 'adada ma
--                      bayna dhalik... mithla dhalik' is a Muslim 2727
--                      pattern that does NOT match PoA/168's 'mil'a ma
--                      khalaq...' Ahmad/Ibn-Hibban pattern.)
-- bocp_248 (Subhan Allah 'adada khalqih, mil'a ma khalaq - Most Virtuous Dhikr)
--   -> LWA PraisesOfAllah/168 -> VERIFIED (exact text match)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/168.mp3' WHERE id = 'bocp_248';
-- (bocp_249 REJECTED - SD/245 is firdaws-specific; SOT 'asaluka al-jannata
--                      wa na'imaha wa istabraqaha' is a different hadith.)
-- bocp_253 (Salawat Ibrahimiya) -> LWA Salawat/184
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/4-Salawat/184.mp3' WHERE id = 'bocp_253';

-- =======================================================================
-- HAJJ & UMRAH (bocp_254..263)
-- =======================================================================
-- bocp_254 (Talbiyah: Labbayk Allahumma Labbayk) -> LWA HajjandUmrah/482
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/482.mp3' WHERE id = 'bocp_254';
-- bocp_256 (Bismillah wa Allahu Akbar - sacrifice takbir) -> LWA HajjandUmrah/489
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/489.mp3' WHERE id = 'bocp_256';
-- bocp_257 (Rabbana atina between corners) -> LWA HajjandUmrah/484
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/484.mp3' WHERE id = 'bocp_257';
-- bocp_258 (Wattakhidhu min maqam Ibrahim musalla) -> LWA HajjandUmrah/485
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/485.mp3' WHERE id = 'bocp_258';
-- bocp_259 (Allahu Akbar 3x on Safa/Marwah) -> LWA HajjandUmrah/483
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/483.mp3' WHERE id = 'bocp_259';
-- bocp_260 (La ilaha illa Allah wahdah - dua on Safa/Marwah/Arafah) -> LWA HajjandUmrah/488
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/488.mp3' WHERE id = 'bocp_260';
-- (bocp_261 REJECTED - SQL mapped to HU/486 ('Inna as-Safa wa al-Marwah min
--                      sha'a'ir Allah'), but bocp_261 SOT is 'Allahu Akbar
--                      la ilaha illa Allah' on Arafat. Different dua.)
-- bocp_262 (Allahu Akbar at jamarat) -> LWA HajjandUmrah/489
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/other/32-HajjandUmrah/489.mp3' WHERE id = 'bocp_262';
-- bocp_263 ('ilman nafi'an - duplicate of bocp_084) -> LWA AfterSalah/129
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/129.mp3' WHERE id = 'bocp_263';

-- =======================================================================
-- DUAS BEFORE SLEEP (sleep_before_001..020)
-- =======================================================================
-- sleep_before_001 (33-33-34 tasbih) -> LWA BeforeSleep/53
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/53.mp3' WHERE id = 'sleep_before_001';
-- sleep_before_002 (Surah Ikhlas - blown into palms) -> LWA BeforeSleep/52 (3 Quls bundle, Ikhlas is first)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/52.mp3' WHERE id = 'sleep_before_002';
-- sleep_before_003 (Surah Falaq, full) -> quranicaudio.com Surah 113
UPDATE azkar_items SET audio_url = 'https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/113.mp3' WHERE id = 'sleep_before_003';
-- sleep_before_004 (Surah Naas, full) -> quranicaudio.com Surah 114
UPDATE azkar_items SET audio_url = 'https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/114.mp3' WHERE id = 'sleep_before_004';
-- sleep_before_005 (Ayat al-Kursi Q2:255) -> Quran CDN
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002255.mp3' WHERE id = 'sleep_before_005';
-- sleep_before_006 (Q2:285) -> LWA BeforeSleep/50 (last 2 verses Al-Baqarah)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/50.mp3' WHERE id = 'sleep_before_006';
-- sleep_before_007 (Q2:286) -> LWA BeforeSleep/50 (includes 286)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/50.mp3' WHERE id = 'sleep_before_007';
-- sleep_before_008 (Surah Kafirun) -> LWA BeforeSleep/51
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/51.mp3' WHERE id = 'sleep_before_008';
-- sleep_before_009 (Allahumma bismika amutu wa ahya) -> LWA BeforeSleep/63
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/63.mp3' WHERE id = 'sleep_before_009';
-- sleep_before_010 (Allahumma aslamtu wajhi ilayk) -> LWA BeforeSleep/65
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/65.mp3' WHERE id = 'sleep_before_010';
-- sleep_before_011 (Bismika Rabbi wada'tu janbi) -> LWA BeforeSleep/54
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/54.mp3' WHERE id = 'sleep_before_011';
-- sleep_before_012 (qini 'adhabaka yawma tab'ath) -> LWA BeforeSleep/55
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/55.mp3' WHERE id = 'sleep_before_012';
-- sleep_before_013 (Alhamdulillah at'amana wa saqana) -> LWA BeforeSleep/56
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/56.mp3' WHERE id = 'sleep_before_013';
-- sleep_before_014 (Allahumma innaka khalaqta nafsi) -> LWA BeforeSleep/60
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/60.mp3' WHERE id = 'sleep_before_014';
-- sleep_before_015 (Allahumma Rabb assamawat wa Rabb al-ard) -> LWA BeforeSleep/58
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/58.mp3' WHERE id = 'sleep_before_015';
-- sleep_before_016 (a'udhu bi-wajhika al-karim) -> LWA BeforeSleep/59
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/59.mp3' WHERE id = 'sleep_before_016';
-- sleep_before_017 (Bismillah wada'tu janbi) -> LWA BeforeSleep/61
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/61.mp3' WHERE id = 'sleep_before_017';
-- sleep_before_018 (Alhamdulillah kafani wa awani) -> LWA BeforeSleep/62
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/62.mp3' WHERE id = 'sleep_before_018';
-- sleep_before_019 (recite Surah As-Sajdah Q32, full) -> quranicaudio Surah 32
UPDATE azkar_items SET audio_url = 'https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/032.mp3' WHERE id = 'sleep_before_019';
-- sleep_before_020 (recite Surah Al-Mulk Q67, full) -> quranicaudio Surah 67
UPDATE azkar_items SET audio_url = 'https://download.quranicaudio.com/quran/mishaari_raashid_al_3afaasee/067.mp3' WHERE id = 'sleep_before_020';

-- =======================================================================
-- DUAS AFTER SALAH (salah_after_002..014)
-- =======================================================================
-- salah_after_002 (Astaghfirullah x3) -> LWA AfterSalah/118
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/118.mp3' WHERE id = 'salah_after_002';
-- salah_after_003 (Allahumma anta as-salam) -> LWA AfterSalah/118 (same audio block)
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/118.mp3' WHERE id = 'salah_after_003';
-- salah_after_004 (Allahumma a'inni 'ala dhikrika) -> LWA AfterSalah/121
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/121.mp3' WHERE id = 'salah_after_004';
-- salah_after_005 (La ilaha illa Allah wahdahu... la hawla wa la quwwata illa billah) -> LWA AfterSalah/119
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/119.mp3' WHERE id = 'salah_after_005';
-- salah_after_006 (33-33-33 tasbih + tahlil) -> LWA AfterSalah/123
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/123.mp3' WHERE id = 'salah_after_006';
-- salah_after_007 (La ilaha illa Allah... yuhyi wa yumit, 10x Fajr/Maghrib) -> LWA AfterSalah/127
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/127.mp3' WHERE id = 'salah_after_007';
-- salah_after_008 ('ilman nafi'an after Fajr) -> LWA AfterSalah/129
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/129.mp3' WHERE id = 'salah_after_008';
-- salah_after_009 (Bismillah + Surah Ikhlas after salah) -> LWA AfterSalah/125
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/125.mp3' WHERE id = 'salah_after_009';
-- salah_after_010 (Bismillah + Surah Falaq after salah) -> LWA AfterSalah/125
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/125.mp3' WHERE id = 'salah_after_010';
-- salah_after_011 (Bismillah + Surah Nas after salah) -> LWA AfterSalah/125
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/125.mp3' WHERE id = 'salah_after_011';
-- salah_after_012 (Bismillah + Ayat al-Kursi) -> LWA AfterSalah/124
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/124.mp3' WHERE id = 'salah_after_012';
-- salah_after_013 (La ilaha illa Allah... la mani'a lima a'tayt - Bukhari 6330) -> LWA AfterSalah/120
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/120.mp3' WHERE id = 'salah_after_013';
-- (salah_after_014 REJECTED - SQL mapped to AfterSalah/128, but SOT is Salawat
--                              Ibrahimiya ('Allahumma salli 'ala Muhammad...'),
--                              while AS/128 is 'Allahumma ajirni min an-nar'.)

-- =======================================================================
-- RABBANA 40 (rabbana_001..040) -> Quran CDN Alafasy
-- All 40 surah:ayah refs verified against canonical 40-Rabbana list AND
-- against actual Arabic text in 20260603_010_azkar_screenshots_import.sql.
-- =======================================================================
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002127.mp3' WHERE id = 'rabbana_001';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002128.mp3' WHERE id = 'rabbana_002';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002201.mp3' WHERE id = 'rabbana_003';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002250.mp3' WHERE id = 'rabbana_004';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002286.mp3' WHERE id = 'rabbana_005';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002286.mp3' WHERE id = 'rabbana_006';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/002286.mp3' WHERE id = 'rabbana_007';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003008.mp3' WHERE id = 'rabbana_008';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003009.mp3' WHERE id = 'rabbana_009';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003016.mp3' WHERE id = 'rabbana_010';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003053.mp3' WHERE id = 'rabbana_011';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003147.mp3' WHERE id = 'rabbana_012';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003191.mp3' WHERE id = 'rabbana_013';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003192.mp3' WHERE id = 'rabbana_014';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003193.mp3' WHERE id = 'rabbana_015';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003193.mp3' WHERE id = 'rabbana_016';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/003194.mp3' WHERE id = 'rabbana_017';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/005083.mp3' WHERE id = 'rabbana_018';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/005114.mp3' WHERE id = 'rabbana_019';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/007023.mp3' WHERE id = 'rabbana_020';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/007047.mp3' WHERE id = 'rabbana_021';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/007089.mp3' WHERE id = 'rabbana_022';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/007126.mp3' WHERE id = 'rabbana_023';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/010085.mp3' WHERE id = 'rabbana_024';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014038.mp3' WHERE id = 'rabbana_025';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014040.mp3' WHERE id = 'rabbana_026';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014041.mp3' WHERE id = 'rabbana_027';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/018010.mp3' WHERE id = 'rabbana_028';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/020045.mp3' WHERE id = 'rabbana_029';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/023109.mp3' WHERE id = 'rabbana_030';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/025065.mp3' WHERE id = 'rabbana_031';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/025074.mp3' WHERE id = 'rabbana_032';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/035034.mp3' WHERE id = 'rabbana_033';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/040007.mp3' WHERE id = 'rabbana_034';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/040008.mp3' WHERE id = 'rabbana_035';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/059010.mp3' WHERE id = 'rabbana_036';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/059010.mp3' WHERE id = 'rabbana_037';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/060004.mp3' WHERE id = 'rabbana_038';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/060005.mp3' WHERE id = 'rabbana_039';
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/066008.mp3' WHERE id = 'rabbana_040';

-- =======================================================================
-- DAILY DUAS & DHIKR
-- =======================================================================
-- daily_dua_001 (Allahumma bismika amutu wa ahya - sleep) -> LWA BeforeSleep/63
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/9-BeforeSleep/63.mp3' WHERE id = 'daily_dua_001';
-- (daily_dua_024 REJECTED - SQL mapped to Ruq/149 but SOT is "As'alu Allah
--                            al-'Azim... an yashfiyak" (Abu Dawud 3106). Ruq/149
--                            is the DIFFERENT "Adh'hib al-ba's Rabb an-nas"
--                            (Bukhari 5750) dua.)
-- daily_dua_025 (Adh'hibi al-ba's Rabb an-nas) -> LWA RuqyahandIllness/149
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/149.mp3' WHERE id = 'daily_dua_025';
-- daily_dua_027 (Q14:41 ighfir li wa li-walidayya) -> Quran CDN 14:41 (covers verse 1)
UPDATE azkar_items SET audio_url = 'https://audio.qurancdn.com/Alafasy/mp3/014041.mp3' WHERE id = 'daily_dua_027';
-- dhikr_028 (subhan Allah wa bi-hamdihi, subhan Allah al-'azim) -> LWA PraisesOfAllah/170
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/170.mp3' WHERE id = 'dhikr_028';
-- dhikr_029 (Allahumma 'afuwwun tuhibbu - Laylatul Qadr) -> LWA SunnahDuas/237
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/6-SunnahDuas/237.mp3' WHERE id = 'dhikr_029';
-- dhikr_032 (Yunus dua: la ilaha illa anta subhanaka) -> LWA QuranicDuas/194
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/5-QuranicDuas/194.mp3' WHERE id = 'dhikr_032';
-- (daily_dua_034 REJECTED - SQL mapped to Ruq/589 but SOT is "Hasbunallahu
--                            wa ni'mal wakeel" (Q3:173) while Ruq/589 is
--                            "Hasbiya Allah la ilaha illa huwa" (Hisn 84).
--                            Different specific duas despite the shared
--                            "Hasb-" root.)
-- daily_dua_037 (Allahumma ajirni min an-nar 3x) -> LWA AfterSalah/128
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/11-AfterSalah/128.mp3' WHERE id = 'daily_dua_037';
-- daily_dua_043 (la ba'sa tahurun in sha Allah - visiting sick) -> LWA RuqyahandIllness/153
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/153.mp3' WHERE id = 'daily_dua_043';

-- ── VERIFIED CORRECTIONS (added by re-verification) ──
-- Re-verification of 9 previously-rejected candidates against LWA pages
-- (raw-HTML extraction of per-audio-file Arabic + URL HEAD check that
-- returns Content-Type: audio/mpeg). 8 of 9 candidates passed; bocp_045
-- still rejected (SunnahDuas page only contains files 234-267, file 289
-- does not exist).
--
-- bocp_122 corrected: was Ruq/142, now Ruq/139.
--   LWA Ruq/139 ("Protection From All Harm") = "A'udhu bi-kalimat Allah
--   at-tammat min sharri ma khalaq" -> exact SOT match. VERIFIED.
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/139.mp3' WHERE id = 'bocp_122';
-- bocp_191 corrected: was Ruq/139, now Ruq/142.
--   LWA Ruq/142 ("A Comprehensive Protection") = "A'udhu bi-kalimat Allah
--   at-tammat min ghadabihi wa 'iqabihi wa sharri 'ibadih wa min hamazat
--   ash-shayatin wa an yahdurun" -> exact SOT match. VERIFIED.
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/12-RuqyahandIllness/142.mp3' WHERE id = 'bocp_191';
-- bocp_128 corrected: was Morning/11, now Morning/13 (1st cluster on page).
--   LWA Morning/13 cluster-1 = "Asbahna wa asbah al-mulk lillah... Allahumma
--   inni as'aluka khayra hadha al-yawm: fathahu wa nasrahu wa nurahu wa
--   barakatahu wa hudahu, wa a'udhu bika min sharri ma fihi wa sharri ma
--   ba'dahu" -> exact SOT match for the bocp_128 second clause. VERIFIED.
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/13.mp3' WHERE id = 'bocp_128';
-- bocp_131 corrected: was Morning/15, now Morning/13 (2nd cluster on page).
--   LWA Morning/13 cluster-2 = "Allahumma inni asbahtu ush-hiduka, wa ush-hidu
--   hamalata 'arshik wa mala'ikatak wa jami'a khalqik, annaka anta Allah la
--   ilaha illa ant wahdaka la sharika lak, wa anna Muhammadan 'abduka wa
--   rasuluk" -> exact SOT match. The file 13 audio is intentionally reused
--   under two adjacent morning sections on the LWA page. VERIFIED.
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/13.mp3' WHERE id = 'bocp_131';
-- bocp_134 corrected: was Morning/18, now Morning/17.
--   LWA Morning/17 = "Raditu billahi rabban, wa bi'l-islami dinan, wa bi-
--   Muhammadin nabiyyan" -> exact SOT match. VERIFIED.
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/17.mp3' WHERE id = 'bocp_134';
-- bocp_136 corrected: was Morning/17, now Morning/15.
--   LWA Morning/15 = "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i,
--   Allahumma 'afini fi basari, la ilaha illa ant..." -> exact SOT match
--   (LWA entry adds a trailing 'a'udhu bika min al-kufr wa al-faqr, wa min
--   'adhab al-qabr' clause, but the leading body/sight/hearing triad matches
--   the SOT verbatim). VERIFIED.
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/7-Morning/15.mp3' WHERE id = 'bocp_136';
-- bocp_246 corrected: was PoA/168, now PoA/171.
--   LWA PoA/171 ("4 Phrases That Outweigh All Other Dhikr") = "Subhan Allah
--   wa bi-hamdihi 'adada khalqihi wa rida nafsihi wa zinata 'arshihi wa
--   midada kalimatih" -> exact SOT match (the Juwayriyya hadith, Muslim 2726).
--   VERIFIED.
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/3-PraisesOfAllah/171.mp3' WHERE id = 'bocp_246';
-- salah_after_014 corrected: was AS/128, now Salawat/184.
--   LWA Salawat/184 ("Salawat #1") = "Allahumma salli 'ala Muhammad wa 'ala
--   ali Muhammad, kama sallayta 'ala Ibrahim wa 'ala ali Ibrahim, innaka
--   hamidum majid. Allahumma barik 'ala Muhammad..." -> exact SOT match
--   for the Salawat Ibrahimiya. VERIFIED.
UPDATE azkar_items SET audio_url = 'https://static.lifewithallah.com/file/LifeWithAllah/main/4-Salawat/184.mp3' WHERE id = 'salah_after_014';
-- bocp_045 STILL REJECTED on re-verification: proposed LWA SD/289 does not
--   exist - the Sunnah Duas page only contains audio files 234-267. No
--   corresponding LWA mapping found for bocp_045's text.

COMMIT;

-- =====================================================================
-- VERIFICATION SUMMARY
-- =====================================================================
-- Input SQL had: 185 UPDATEs (mapping ~162 unique entries in the user count;
--                              precise UPDATE count includes a few duplicate
--                              targets like AS/118, AS/125, SD/245, PoA/168,
--                              HU/489)
-- Verified pass: 167
-- Rejected (Arabic mismatch): 18
--
-- REJECTED MAPPINGS (do NOT apply):
-- bocp_045   -- SOT 'a'udhu min al-'ajz wal-kasal wal-jubn wal-haram wal-bukhl,
--               wa min 'adhab al-qabr, wa fitnat al-mahya wal-mamat'
--               vs SD/248 actual 'a'udhu min DIQ al-dunya wa diq yawm al-qiyamah'
--               -- different hadith. Closest LWA match would be SD/289.
-- bocp_081   -- SOT 'as'aluka al-jannata wa astajiru bika min an-nar'
--               vs SD/245 actual 'as'aluka al-FIRDAWS a'la al-jannah'
--               -- different specific Tirmidhi vs Abu-Dawud duas.
-- bocp_102   -- same firdaws/jannah mismatch (duplicate target of bocp_081).
-- bocp_122   -- SOT 'a'udhu bi-kalimat Allah at-tammat min sharri ma khalaq'
--               vs Ruq/142 actual 'min ghadabihi wa 'iqabihi'
--               -- swapped with bocp_191. Correct mapping = Ruq/139.
-- bocp_128   -- SOT 'as'aluka khayra hadha al-yawm: fathahu, nasrahu, nurahu,
--               barakatahu, hudahu' vs Morning/11 actual 'asbahna wa asbah
--               al-mulk lillah wa al-hamdu lillah' -- different dua. Correct
--               LWA mapping = Morning/13 ('Ask Allah to Bless Your Day').
-- bocp_131   -- SOT 'asbahtu ush-hiduka, ush-hidu hamalat 'arshik' vs
--               Morning/15 actual ''afini fi badani' -- different dua.
--               Correct LWA mapping = Morning/13 ('Get Yourself Freed from
--               the Hell-fire').
-- bocp_132   -- SOT 'as'aluka al-'afwa wal-'afiyah fi: dini, wa dunyay, wa
--               ahli, wa mali' vs Morning/16 actual 'Hasbiya Allah la ilaha
--               illa huwa' -- different dua. No corresponding LWA Morning
--               file with bocp_132's specific text was found.
-- bocp_134   -- SOT 'raditu billahi rabban' vs Morning/18 actual 'Bismillah
--               alladhi la yadurru ma'a ismihi' -- different dua. Correct
--               LWA mapping = Morning/17 ('Have the Prophet ﷺ Hold Your Hand').
-- bocp_136   -- SOT ''afini fi badani, 'afini fi sam'i, 'afini fi basari'
--               vs Morning/17 actual 'raditu billahi rabban' -- different
--               dua. Correct LWA mapping = Morning/15.
-- bocp_138   -- SOT 'subhan Allah wa bi-hamdihi LA QUWWATA ILLA BILLAH MA
--               SHAA'A ALLAH KANA WA MA LAM YASHA' LAM YAKUN, A'LAMU ANNA
--               ALLAHA 'ALA KULLI SHAY'IN QADIR' (long composite from
--               Abu-Dawud 5074-ish) vs Morning/19 actual short 'subhan
--               Allah wa bi-hamdihi (100x)' -- only the opening 5 words
--               overlap, the substance is a different hadith.
-- bocp_191   -- SOT 'a'udhu bi-kalimat Allah at-tammat min ghadabihi wa
--               alim 'iqabihi wa sharri 'ibadih' vs Ruq/139 actual 'min
--               sharri ma khalaq'. Correct LWA mapping = Ruq/142.
-- bocp_246   -- SOT 'subhan Allah wa bi-hamdihi 'adada khalqihi wa rida
--               nafsihi wa zinata 'arshihi wa midada kalimatih' (Muslim 2726
--               'Juwayriyya hadith') vs PoA/168 actual 'subhan Allah 'adada
--               ma khalaq, mil'a ma khalaq...' (Ahmad 22198) -- different
--               hadith. Correct LWA mapping = PoA/171 ('4 Phrases That
--               Outweigh All Other Dhikr').
-- bocp_247   -- SOT 'subhan Allah 'adada ma khalaqa fi as-sama'i wa 'adada
--               ma khalaqa fi al-ard wa subhan Allah 'adada ma bayna dhalik
--               ... mithla dhalik' (Muslim 2727) vs PoA/168 actual 'mil'a ma
--               khalaq' pattern -- adjacent-but-not-identical hadith.
-- bocp_249   -- SOT 'as'aluka al-jannata wa na'imaha wa istabraqaha, wa
--               a'udhu bika min an-nar wa salasiliha wa aghlaliha' vs SD/245
--               'as'aluka al-firdaws a'la al-jannah' -- different duas.
-- bocp_261   -- SOT 'Allahu Akbar la ilaha illa Allah' on 'Arafat vs HU/486
--               actual Quranic verse 'inna as-Safa wa al-Marwah min sha'a'ir
--               Allah' -- different content.
-- salah_after_014 -- SOT is Salawat Ibrahimiya ('Allahumma salli 'ala
--               Muhammad wa 'ala ali Muhammad kama sallayta 'ala Ibrahim
--               wa 'ala ali Ibrahim...') vs AS/128 actual 'Allahumma ajirni
--               min an-nar' -- entirely different dua. The correct LWA file
--               for salah_after_014 is Salawat/184.
-- daily_dua_024 -- SOT 'As'alu Allah al-'Azim, Rabb al-'arsh al-'azim, an
--               yashfiyak' (Abu Dawud 3106, 7x) vs Ruq/149 actual 'Adh'hib
--               al-ba's Rabb an-nas, ishfi anta ash-shafi' (Bukhari 5750)
--               -- different duas for visiting the sick.
-- daily_dua_034 -- SOT 'Hasbunallahu wa ni'mal wakeel' (Q3:173) vs Ruq/589
--               actual 'Hasbiya Allah la ilaha illa huwa, 'alayhi tawakkaltu
--               wa huwa Rabb al-'arsh al-'azim' (Hisn 84) -- different duas
--               despite the shared "Hasb-" opening word.
--
-- METHOD NOTES
-- ============
-- 1. LWA pages were fetched both via WebFetch (high-level summarisation) AND
--    via raw curl + Python HTML parsing (to extract the exact Arabic
--    associated with each /N.mp3 audio file). Where these disagreed the raw
--    HTML was treated as authoritative.
-- 2. The Morning page in particular has a non-position-based audio numbering:
--    audio file 12 and 21 are missing, audio 13 appears under two adjacent
--    sections, and the actual audio for several BoCP morning duas is on a
--    different file number from what the generator-agent assumed. The 6
--    rejected bocp_12x/13x mappings all stem from this confusion.
-- 3. Quran CDN URLs were validated by matching each surah:ayah in the URL
--    against the canonical Quran reference for that ayah in the SOT text.
--    All 9 Quran-CDN BoCP entries and all 40 Rabbana entries verified.
-- 4. quranicaudio.com full-surah URLs are trusted for entries that
--    explicitly call for the entire surah (Falaq, Nas, Sajdah, Mulk).
