-- Book of Complete Prayer — backfill benefits + source references.
-- One UPDATE per dua, keyed by ordinal id (`bocp_001` … `bocp_263`).

UPDATE azkar_items SET reward = 'Recited between the Yemeni Corner and the Black Stone during Tawaf.', reference = 'Qur’an 2:201' WHERE id = 'bocp_001';
UPDATE azkar_items SET reference = 'Qur’an 2:250' WHERE id = 'bocp_002';
UPDATE azkar_items SET reward = 'The closing verses of al-Baqarah; recited at night for protection.', reference = 'Qur’an 2:286' WHERE id = 'bocp_003';
UPDATE azkar_items SET reward = 'A prayer for the heart to stay firm upon guidance.', reference = 'Qur’an 3:8' WHERE id = 'bocp_004';
UPDATE azkar_items SET reference = 'Qur’an 3:16' WHERE id = 'bocp_005';
UPDATE azkar_items SET reference = 'Qur’an 3:26' WHERE id = 'bocp_006';
UPDATE azkar_items SET reward = 'The prayer of Zakariyya, longing for a child.', reference = 'Qur’an 3:38' WHERE id = 'bocp_007';
UPDATE azkar_items SET reference = 'Qur’an 3:53' WHERE id = 'bocp_008';
UPDATE azkar_items SET reference = 'Qur’an 3:147' WHERE id = 'bocp_009';
UPDATE azkar_items SET reward = 'From the closing verses of Aal ‘Imran, on the signs of creation.', reference = 'Qur’an 3:191-194' WHERE id = 'bocp_010';
UPDATE azkar_items SET reference = 'Qur’an 5:83' WHERE id = 'bocp_011';
UPDATE azkar_items SET reward = 'The words of Adam and his wife after their slip.', reference = 'Qur’an 7:23' WHERE id = 'bocp_012';
UPDATE azkar_items SET reference = 'Qur’an 7:47' WHERE id = 'bocp_013';
UPDATE azkar_items SET reward = 'The prayer of the believers among the people of Musa.', reference = 'Qur’an 10:85' WHERE id = 'bocp_014';
UPDATE azkar_items SET reward = 'The prayer of Nuh after the Flood.', reference = 'Qur’an 11:47' WHERE id = 'bocp_015';
UPDATE azkar_items SET reward = 'From the prayers of Ibrahim for Mecca and his descendants.', reference = 'Qur’an 14:35' WHERE id = 'bocp_016';
UPDATE azkar_items SET reference = 'Qur’an 14:40' WHERE id = 'bocp_017';
UPDATE azkar_items SET reference = 'Qur’an 14:41' WHERE id = 'bocp_018';
UPDATE azkar_items SET reward = 'The Qur’an’s prayer for one’s parents.', reference = 'Qur’an 17:24' WHERE id = 'bocp_019';
UPDATE azkar_items SET reference = 'Qur’an 17:80' WHERE id = 'bocp_020';
UPDATE azkar_items SET reward = 'The prayer of the young believers of the Cave.', reference = 'Qur’an 18:10' WHERE id = 'bocp_021';
UPDATE azkar_items SET reward = 'A prayer for increase in beneficial knowledge.', reference = 'Qur’an 20:114' WHERE id = 'bocp_022';
UPDATE azkar_items SET reward = 'The prayer of Yunus (Dhu’n-Nun) from within the whale.', reference = 'Qur’an 21:87' WHERE id = 'bocp_023';
UPDATE azkar_items SET reward = 'The prayer of Zakariyya for offspring.', reference = 'Qur’an 21:89' WHERE id = 'bocp_024';
UPDATE azkar_items SET reward = 'The prayer of Nuh on boarding the Ark.', reference = 'Qur’an 23:29' WHERE id = 'bocp_025';
UPDATE azkar_items SET reference = 'Qur’an 23:97-98' WHERE id = 'bocp_026';
UPDATE azkar_items SET reference = 'Qur’an 23:109' WHERE id = 'bocp_027';
UPDATE azkar_items SET reference = 'Qur’an 23:118' WHERE id = 'bocp_028';
UPDATE azkar_items SET reward = 'The prayer of Sulayman in gratitude.', reference = 'Qur’an 27:19' WHERE id = 'bocp_029';
UPDATE azkar_items SET reward = 'The prayer of Musa after his error in Egypt.', reference = 'Qur’an 28:16' WHERE id = 'bocp_030';
UPDATE azkar_items SET reference = 'Qur’an 28:17' WHERE id = 'bocp_031';
UPDATE azkar_items SET reference = 'Qur’an 28:21' WHERE id = 'bocp_032';
UPDATE azkar_items SET reward = 'The prayer of Musa, alone and in need in Madyan.', reference = 'Qur’an 28:24' WHERE id = 'bocp_033';
UPDATE azkar_items SET reference = 'Qur’an 29:30' WHERE id = 'bocp_034';
UPDATE azkar_items SET reference = 'Qur’an 25:65' WHERE id = 'bocp_035';
UPDATE azkar_items SET reward = 'The prayer of the servants of the Most Merciful.', reference = 'Qur’an 25:74' WHERE id = 'bocp_036';
UPDATE azkar_items SET reference = 'Qur’an 40:7-8' WHERE id = 'bocp_037';
UPDATE azkar_items SET reference = 'Qur’an 46:15' WHERE id = 'bocp_038';
UPDATE azkar_items SET reward = 'The prayer of Ibrahim for righteous offspring.', reference = 'Qur’an 37:100' WHERE id = 'bocp_039';
UPDATE azkar_items SET reference = 'Qur’an 59:10' WHERE id = 'bocp_040';
UPDATE azkar_items SET reference = 'Qur’an 60:4-5' WHERE id = 'bocp_041';
UPDATE azkar_items SET reward = 'The prayer of Nuh for the believers.', reference = 'Qur’an 71:28' WHERE id = 'bocp_042';
UPDATE azkar_items SET reference = 'al-Bukhari 6389, Muslim 2690 · Anas' WHERE id = 'bocp_043';
UPDATE azkar_items SET reference = 'al-Bukhari & Muslim 589 · ''Aisha' WHERE id = 'bocp_044';
UPDATE azkar_items SET reference = 'al-Bukhari 6367, Muslim 2706 · Anas' WHERE id = 'bocp_045';
UPDATE azkar_items SET reference = 'al-Bukhari 6347, Muslim 2707 · Abu Hurayrah' WHERE id = 'bocp_046';
UPDATE azkar_items SET reference = 'Muslim 2720 · Abu Hurayrah' WHERE id = 'bocp_047';
UPDATE azkar_items SET reference = 'Muslim 2721 · Ibn Mas''ud' WHERE id = 'bocp_048';
UPDATE azkar_items SET reference = 'Muslim 2722 · Zayd ibn Arqam' WHERE id = 'bocp_049';
UPDATE azkar_items SET reference = 'Muslim 2725 · Ali' WHERE id = 'bocp_050';
UPDATE azkar_items SET reference = 'Muslim 2739 · Ibn ''Umar' WHERE id = 'bocp_051';
UPDATE azkar_items SET reference = 'al-Bukhari 6379, Muslim 660 · Anas (adapted)' WHERE id = 'bocp_052';
UPDATE azkar_items SET reference = 'al-Bukhari 6346, Muslim 2730 · Ibn ''Abbas (du''a of distress)' WHERE id = 'bocp_053';
UPDATE azkar_items SET reference = 'Abu Dawud 5090 · Abu Bakrah · hasan' WHERE id = 'bocp_054';
UPDATE azkar_items SET reference = 'Tirmidhi 3505 · supplication of Dhun-Nun (Yunus); also Qur''an 21:87' WHERE id = 'bocp_055';
UPDATE azkar_items SET reference = 'Ahmad 3712 · Ibn Mas''ud · sahih (du''a for sadness)' WHERE id = 'bocp_056';
UPDATE azkar_items SET reference = 'Muslim 2654 · Abdullah ibn ''Amr' WHERE id = 'bocp_057';
UPDATE azkar_items SET reference = 'Tirmidhi 2140 · Anas · sahih' WHERE id = 'bocp_058';
UPDATE azkar_items SET reference = 'Ibn Majah / Abu Dawud · supplication for well-being (''afiyah) · hasan' WHERE id = 'bocp_059';
UPDATE azkar_items SET reference = 'Ahmad / Ibn Hibban · Busr ibn Abi Artat · sahih' WHERE id = 'bocp_060';
UPDATE azkar_items SET reference = 'Abu Dawud 1510, Tirmidhi 3551 · Ibn ''Abbas · sahih' WHERE id = 'bocp_061';
UPDATE azkar_items SET reference = 'Abu Dawud 1551, Tirmidhi 3492 · Shakal ibn Humayd · sahih' WHERE id = 'bocp_062';
UPDATE azkar_items SET reference = 'Tirmidhi 3513 · ''Aisha · Laylat al-Qadr du''a' WHERE id = 'bocp_063';
UPDATE azkar_items SET reference = 'Tirmidhi 3235 · Mu''adh · sahih (the dream hadith)' WHERE id = 'bocp_064';
UPDATE azkar_items SET reference = 'Ibn Majah 3846, Ahmad · ''Aisha · sahih' WHERE id = 'bocp_065';
UPDATE azkar_items SET reference = 'al-Hakim, al-Tabarani · Ibn ''Abbas · hasan' WHERE id = 'bocp_066';
UPDATE azkar_items SET reference = 'al-Bukhari 2822 · Sa''d ibn Abi Waqqas · sahih' WHERE id = 'bocp_067';
UPDATE azkar_items SET reference = 'al-Bukhari 6398, Muslim 2719 · Abu Musa al-Ash''ari · sahih' WHERE id = 'bocp_068';
UPDATE azkar_items SET reference = 'al-Bukhari 834, Muslim 2705 · Abu Bakr al-Siddiq · sahih' WHERE id = 'bocp_069';
UPDATE azkar_items SET reference = 'al-Bukhari 7383, Muslim 2717 · Ibn ''Abbas · sahih' WHERE id = 'bocp_070';
UPDATE azkar_items SET reference = 'al-Hakim, al-Tabarani · Ibn Mas''ud' WHERE id = 'bocp_071';
UPDATE azkar_items SET reference = 'Muslim 2716 · ''Aisha · sahih' WHERE id = 'bocp_072';
UPDATE azkar_items SET reference = 'al-Hakim, al-Bayhaqi · ''Aisha' WHERE id = 'bocp_073';
UPDATE azkar_items SET reference = 'al-Nasa''i (''Amal al-Yawm), Ahmad · Abu Musa · sahih' WHERE id = 'bocp_074';
UPDATE azkar_items SET reference = 'al-Tabarani, Ibn al-Sunni · Ibn Mas''ud' WHERE id = 'bocp_075';
UPDATE azkar_items SET reference = 'Abu Dawud 1552, al-Nasa''i 5531 · Abu Hurayrah · sahih' WHERE id = 'bocp_076';
UPDATE azkar_items SET reference = 'Abu Dawud 1554 & others · Anas · the disease portion is sahih' WHERE id = 'bocp_077';
UPDATE azkar_items SET reference = 'Abu Dawud 1544, al-Nasa''i · Abu Hurayrah · sahih' WHERE id = 'bocp_078';
UPDATE azkar_items SET reference = 'Tirmidhi 3482, al-Nasa''i · Abu Hurayrah · sahih' WHERE id = 'bocp_079';
UPDATE azkar_items SET reference = 'al-Tabarani · Uqbah ibn Amir' WHERE id = 'bocp_080';
UPDATE azkar_items SET reference = 'Abu Dawud 792, Ibn Majah · sahih' WHERE id = 'bocp_081';
UPDATE azkar_items SET reference = 'al-Bukhari 143 · Ibn ''Abbas (adapted)' WHERE id = 'bocp_082';
UPDATE azkar_items SET reference = 'Ahmad 19606 · Abu Musa · sahih' WHERE id = 'bocp_083';
UPDATE azkar_items SET reference = 'Ibn Majah 925 · Umm Salamah · sahih' WHERE id = 'bocp_084';
UPDATE azkar_items SET reference = 'Ibn Majah 3843 · Jabir · sahih' WHERE id = 'bocp_085';
UPDATE azkar_items SET reference = 'Abu Dawud 1493, Tirmidhi 3475 · Buraydah · sahih (the Greatest Name)' WHERE id = 'bocp_086';
UPDATE azkar_items SET reference = 'Muslim 2713 + al-Bukhari 6317/Muslim 771 · composite' WHERE id = 'bocp_087';
UPDATE azkar_items SET reference = 'Abu Dawud 1495, Tirmidhi 3544 · Anas · sahih (the Greatest Name)' WHERE id = 'bocp_088';
UPDATE azkar_items SET reference = 'Abu Dawud 1516, Tirmidhi 3434 · Ibn ''Umar · sahih' WHERE id = 'bocp_089';
UPDATE azkar_items SET reference = 'al-Nasa''i 1305 · ''Ammar ibn Yasir · sahih' WHERE id = 'bocp_090';
UPDATE azkar_items SET reference = 'al-Bukhari 744, Muslim 598 · adapted from the opening supplication' WHERE id = 'bocp_091';
UPDATE azkar_items SET reference = 'Muslim 770 · ''Aisha (opening) + addition' WHERE id = 'bocp_092';
UPDATE azkar_items SET reference = 'Tirmidhi 3483 · ''Imran ibn Husayn · sahih' WHERE id = 'bocp_093';
UPDATE azkar_items SET reference = 'Muslim 2713 · Abu Hurayrah · sahih (bedtime supplication)' WHERE id = 'bocp_094';
UPDATE azkar_items SET reference = 'Abu Dawud 969 · Ibn Mas''ud · sahih' WHERE id = 'bocp_095';
UPDATE azkar_items SET reference = 'Tirmidhi 3591 · Quṭbah ibn Malik · sahih' WHERE id = 'bocp_096';
UPDATE azkar_items SET reference = 'Ahmad · ''Aisha · sahih' WHERE id = 'bocp_097';
UPDATE azkar_items SET reference = 'Abu Dawud 1522, al-Nasa''i · Mu''adh ibn Jabal · sahih' WHERE id = 'bocp_098';
UPDATE azkar_items SET reference = 'Ahmad 17126 · hasan' WHERE id = 'bocp_099';
UPDATE azkar_items SET reference = 'al-Bazzar, al-Hakim · hasan' WHERE id = 'bocp_100';
UPDATE azkar_items SET reference = 'al-Nasa''i 5475 · Abdullah ibn ''Amr · sahih' WHERE id = 'bocp_101';
UPDATE azkar_items SET reference = 'Abu Dawud 792, Ibn Majah · sahih' WHERE id = 'bocp_102';
UPDATE azkar_items SET reference = 'Muslim 2697 · Tariq ibn Ashyam · sahih (core)' WHERE id = 'bocp_103';
UPDATE azkar_items SET reference = 'Tirmidhi 3502 · sahih' WHERE id = 'bocp_104';
UPDATE azkar_items SET reference = 'Abu Dawud 1495, al-Nasa''i · Anas · sahih (the Greatest Name)' WHERE id = 'bocp_105';
UPDATE azkar_items SET reference = 'al-Bukhari 1120, Muslim 769 · Ibn ''Abbas · sahih (tahajjud)' WHERE id = 'bocp_106';
UPDATE azkar_items SET reference = 'al-Bukhari 6317, Muslim 771 · Ibn ''Abbas · sahih (tahajjud)' WHERE id = 'bocp_107';
UPDATE azkar_items SET reference = 'Abu Dawud 1425, Tirmidhi 464 · al-Hasan ibn Ali · sahih (qunut)' WHERE id = 'bocp_108';
UPDATE azkar_items SET reference = 'al-Hakim · ''Aisha · sahih' WHERE id = 'bocp_109';
UPDATE azkar_items SET reference = 'al-Bukhari 6306 · Shaddad ibn Aws · sahih (Sayyid al-Istighfar)' WHERE id = 'bocp_110';
UPDATE azkar_items SET reference = 'Source uncertain' WHERE id = 'bocp_111';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_112';
UPDATE azkar_items SET reference = 'Muslim 483 · Abu Hurayrah · sahih' WHERE id = 'bocp_113';
UPDATE azkar_items SET reference = 'Composite (qunut nazilah, Abu Dawud 1442, & several supplications)' WHERE id = 'bocp_114';
UPDATE azkar_items SET reference = 'Abu Dawud 850, Tirmidhi 284 · Ibn ''Abbas · sahih' WHERE id = 'bocp_115';
UPDATE azkar_items SET reference = 'Tirmidhi 3173 · ''Umar ibn al-Khattab · hasan' WHERE id = 'bocp_116';
UPDATE azkar_items SET reference = 'Ahmad 3823 · Ibn Mas''ud · sahih' WHERE id = 'bocp_117';
UPDATE azkar_items SET reference = 'al-Bukhari 3036 · Jarir ibn Abdullah (adapted)' WHERE id = 'bocp_118';
UPDATE azkar_items SET reference = 'Derived from Qur''an 2:269' WHERE id = 'bocp_119';
UPDATE azkar_items SET reference = 'Abu Dawud 5088, Tirmidhi 3388 · Uthman ibn Affan · sahih' WHERE id = 'bocp_120';
UPDATE azkar_items SET reference = 'Source uncertain / weak' WHERE id = 'bocp_121';
UPDATE azkar_items SET reference = 'Muslim 2708 · Khawlah bint Hakim · sahih' WHERE id = 'bocp_122';
UPDATE azkar_items SET reference = 'Ahmad, al-Tabarani · hasan' WHERE id = 'bocp_123';
UPDATE azkar_items SET reference = 'Morning supplication' WHERE id = 'bocp_124';
UPDATE azkar_items SET reference = 'al-Bukhari 6403, Muslim 2691 · Abu Hurayrah · sahih' WHERE id = 'bocp_125';
UPDATE azkar_items SET reference = 'al-Bukhari & Muslim · sahih' WHERE id = 'bocp_126';
UPDATE azkar_items SET reference = 'Morning supplication' WHERE id = 'bocp_127';
UPDATE azkar_items SET reference = 'Abu Dawud 5084 · sahih' WHERE id = 'bocp_128';
UPDATE azkar_items SET reference = 'Abu Dawud 5068, Tirmidhi 3391 · sahih' WHERE id = 'bocp_129';
UPDATE azkar_items SET reference = 'Abu Dawud 5067, Tirmidhi 3392 · Abu Bakr · sahih' WHERE id = 'bocp_130';
UPDATE azkar_items SET reference = 'Abu Dawud 5069 · hasan' WHERE id = 'bocp_131';
UPDATE azkar_items SET reference = 'Abu Dawud 5074, Ibn Majah 3871 · Ibn ''Umar · sahih' WHERE id = 'bocp_132';
UPDATE azkar_items SET reference = 'Abu Dawud 5074, Ibn Majah · Ibn ''Umar · sahih' WHERE id = 'bocp_133';
UPDATE azkar_items SET reference = 'Abu Dawud 5072, Tirmidhi 3389 · sahih' WHERE id = 'bocp_134';
UPDATE azkar_items SET reference = 'Abu Dawud 5073 · Abdullah ibn Ghannam · hasan' WHERE id = 'bocp_135';
UPDATE azkar_items SET reference = 'Abu Dawud 5090 · Abu Bakrah · hasan' WHERE id = 'bocp_136';
UPDATE azkar_items SET reference = 'Abu Dawud 5090 · Abu Bakrah · hasan (said three times)' WHERE id = 'bocp_137';
UPDATE azkar_items SET reference = 'Morning supplication' WHERE id = 'bocp_138';
UPDATE azkar_items SET reference = 'Ahmad 15367 · sahih' WHERE id = 'bocp_139';
UPDATE azkar_items SET reference = 'al-Hakim, al-Nasa''i · Anas · hasan' WHERE id = 'bocp_140';
UPDATE azkar_items SET reference = 'al-Bukhari 6306 · Shaddad ibn Aws · sahih (Sayyid al-Istighfar)' WHERE id = 'bocp_141';
UPDATE azkar_items SET reference = 'al-Tabarani · grading weak/debated' WHERE id = 'bocp_142';
UPDATE azkar_items SET reference = 'Abu Dawud 5081 · hasan (also Qur''an 9:129; said seven times)' WHERE id = 'bocp_143';
UPDATE azkar_items SET reference = 'al-Bukhari 6369 · Anas · sahih' WHERE id = 'bocp_144';
UPDATE azkar_items SET reference = 'Morning supplication' WHERE id = 'bocp_145';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_146';
UPDATE azkar_items SET reference = 'al-Hakim, Ahmad · hasan (the covenant supplication)' WHERE id = 'bocp_147';
UPDATE azkar_items SET reference = 'al-Bukhari 2822 · Sa''d ibn Abi Waqqas · sahih' WHERE id = 'bocp_148';
UPDATE azkar_items SET reference = 'Muslim 771 · Ali · sahih (the opening supplication)' WHERE id = 'bocp_149';
UPDATE azkar_items SET reference = 'al-Nasa''i (''Amal al-Yawm), Ahmad · Abu Musa · sahih' WHERE id = 'bocp_150';
UPDATE azkar_items SET reference = 'al-Hakim, al-Bayhaqi · grading debated' WHERE id = 'bocp_151';
UPDATE azkar_items SET reference = 'Abu Dawud 1552, al-Nasa''i · Abu Hurayrah · sahih' WHERE id = 'bocp_152';
UPDATE azkar_items SET reference = 'Tirmidhi 3407, al-Nasa''i · Shaddad ibn Aws · hasan' WHERE id = 'bocp_153';
UPDATE azkar_items SET reference = 'Tirmidhi 3233 · Mu''adh · sahih (the dream hadith)' WHERE id = 'bocp_154';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_155';
UPDATE azkar_items SET reference = 'Tirmidhi · grading debated' WHERE id = 'bocp_156';
UPDATE azkar_items SET reference = 'al-Bayhaqi (Shu''ab al-Iman) · grading debated' WHERE id = 'bocp_157';
UPDATE azkar_items SET reference = 'al-Tabarani · grading debated' WHERE id = 'bocp_158';
UPDATE azkar_items SET reference = 'al-Bazzar, al-Hakim · grading debated' WHERE id = 'bocp_159';
UPDATE azkar_items SET reference = 'al-Hakim, al-Tabarani · grading debated' WHERE id = 'bocp_160';
UPDATE azkar_items SET reference = 'al-Hakim, Ibn Majah 3846 · part of a comprehensive supplication' WHERE id = 'bocp_161';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_162';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_163';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_164';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_165';
UPDATE azkar_items SET reference = 'Ibn Majah, al-Hakim · grading debated' WHERE id = 'bocp_166';
UPDATE azkar_items SET reference = 'Tirmidhi 3419 · Ibn ''Abbas · hasan' WHERE id = 'bocp_167';
UPDATE azkar_items SET reference = 'Tirmidhi 3419 · Ibn ''Abbas · hasan' WHERE id = 'bocp_168';
UPDATE azkar_items SET reference = 'Ahmad, al-Hakim · grading debated' WHERE id = 'bocp_169';
UPDATE azkar_items SET reference = 'al-Hakim · grading debated/weak' WHERE id = 'bocp_170';
UPDATE azkar_items SET reference = 'al-Hakim, al-Tabarani · grading debated' WHERE id = 'bocp_171';
UPDATE azkar_items SET reference = 'al-Tabarani · grading debated/weak' WHERE id = 'bocp_172';
UPDATE azkar_items SET reference = 'al-Tabarani, al-Hakim · grading debated' WHERE id = 'bocp_173';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_174';
UPDATE azkar_items SET reference = 'al-Tabarani · weak' WHERE id = 'bocp_175';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_176';
UPDATE azkar_items SET reference = 'al-Hakim, al-Tabarani · grading debated' WHERE id = 'bocp_177';
UPDATE azkar_items SET reference = 'Ahmad, Tirmidhi · sahih' WHERE id = 'bocp_178';
UPDATE azkar_items SET reference = 'al-Hakim, al-Tabarani · grading debated/weak' WHERE id = 'bocp_179';
UPDATE azkar_items SET reference = 'al-Tabarani / compilation · source uncertain' WHERE id = 'bocp_180';
UPDATE azkar_items SET reference = 'al-Tabarani · grading debated' WHERE id = 'bocp_181';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_182';
UPDATE azkar_items SET reference = 'Ibn Majah, al-Hakim · grading debated' WHERE id = 'bocp_183';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_184';
UPDATE azkar_items SET reference = 'al-Hakim · grading debated' WHERE id = 'bocp_185';
UPDATE azkar_items SET reference = 'al-Hakim / compilation · grading debated' WHERE id = 'bocp_186';
UPDATE azkar_items SET reference = 'Abu Dawud 1442 · sahih (the qunut nazilah)' WHERE id = 'bocp_187';
UPDATE azkar_items SET reference = 'Source/grading uncertain (with takbir)' WHERE id = 'bocp_188';
UPDATE azkar_items SET reference = 'Composite with Qur''anic verses (25:65, 7:23) · source uncertain' WHERE id = 'bocp_189';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_190';
UPDATE azkar_items SET reference = 'Abu Dawud 3893 · hasan' WHERE id = 'bocp_191';
UPDATE azkar_items SET reference = 'Source uncertain' WHERE id = 'bocp_192';
UPDATE azkar_items SET reference = 'Famous du''a of Ta''if; chain debated/weak' WHERE id = 'bocp_193';
UPDATE azkar_items SET reference = 'Tirmidhi 3599, Ibn Majah 251 · sahih' WHERE id = 'bocp_194';
UPDATE azkar_items SET reference = 'Source uncertain' WHERE id = 'bocp_195';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_196';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_197';
UPDATE azkar_items SET reference = 'Abu Dawud 1537 · hasan' WHERE id = 'bocp_198';
UPDATE azkar_items SET reference = 'Compilation (istighfar for parents and believers)' WHERE id = 'bocp_199';
UPDATE azkar_items SET reference = 'al-Khatib / compilation · weak' WHERE id = 'bocp_200';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_201';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_202';
UPDATE azkar_items SET reference = 'Ahmad · Ibn ''Abbas · hasan' WHERE id = 'bocp_203';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_204';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_205';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_206';
UPDATE azkar_items SET reference = 'Ibn Majah 3808 · grading debated' WHERE id = 'bocp_207';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_208';
UPDATE azkar_items SET reference = 'Munajat / compilation · not a sound marfu'' hadith' WHERE id = 'bocp_209';
UPDATE azkar_items SET reference = 'al-Hakim, al-Tabarani · grading debated/weak' WHERE id = 'bocp_210';
UPDATE azkar_items SET reference = 'al-Tabarani / compilation · grading debated' WHERE id = 'bocp_211';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_212';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_213';
UPDATE azkar_items SET reference = 'al-Tabarani · grading debated' WHERE id = 'bocp_214';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_215';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_216';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_217';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_218';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_219';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_220';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_221';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_222';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_223';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_224';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_225';
UPDATE azkar_items SET reference = 'Compilation of Qur''anic phrases (40:15, 40:3, 57:3) · not a transmitted supplication' WHERE id = 'bocp_226';
UPDATE azkar_items SET reference = 'al-Hakim / compilation · grading debated' WHERE id = 'bocp_227';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_228';
UPDATE azkar_items SET reference = 'Literary supplication · not a transmitted hadith' WHERE id = 'bocp_229';
UPDATE azkar_items SET reference = 'Literary supplication · not a transmitted hadith' WHERE id = 'bocp_230';
UPDATE azkar_items SET reference = 'Literary supplication · not a transmitted hadith' WHERE id = 'bocp_231';
UPDATE azkar_items SET reference = 'Literary / composite supplication · not a transmitted hadith' WHERE id = 'bocp_232';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_233';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_234';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_235';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_236';
UPDATE azkar_items SET reference = 'Travel du''a · core is Muslim 1343 (sahih), with additions' WHERE id = 'bocp_237';
UPDATE azkar_items SET reference = 'Literary / compilation supplication · not a transmitted hadith' WHERE id = 'bocp_238';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_239';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_240';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_241';
UPDATE azkar_items SET reference = 'al-Bayhaqi / Ibn Abi''d-Dunya · grading debated' WHERE id = 'bocp_242';
UPDATE azkar_items SET reference = 'al-Tabarani · grading debated' WHERE id = 'bocp_243';
UPDATE azkar_items SET reference = 'Source uncertain (compilation)' WHERE id = 'bocp_244';
UPDATE azkar_items SET reference = 'al-Hakim · grading debated' WHERE id = 'bocp_245';
UPDATE azkar_items SET reference = 'Muslim 2726 · Juwayriyah · sahih' WHERE id = 'bocp_246';
UPDATE azkar_items SET reference = 'al-Nasa''i (''Amal al-Yawm), Ahmad · hasan' WHERE id = 'bocp_247';
UPDATE azkar_items SET reference = 'al-Nasa''i (''Amal al-Yawm), Ahmad · hasan' WHERE id = 'bocp_248';
UPDATE azkar_items SET reference = 'Source uncertain (compilation) · core is authentic' WHERE id = 'bocp_249';
UPDATE azkar_items SET reference = 'al-Tabarani · grading debated' WHERE id = 'bocp_250';
UPDATE azkar_items SET reference = 'Framed from Qur''an 40:60' WHERE id = 'bocp_251';
UPDATE azkar_items SET reference = 'Closing supplication · compilation' WHERE id = 'bocp_252';
UPDATE azkar_items SET reference = 'al-Bukhari 3370, Muslim 406 · sahih (the closing Salat Ibrahimiyyah)' WHERE id = 'bocp_253';
UPDATE azkar_items SET reward = 'The Talbiyah — recited aloud and repeatedly from entering iḥrām until the stoning of the Jamrah on the day of ʿĪd.', reference = 'Bukhari & Muslim' WHERE id = 'bocp_254';
UPDATE azkar_items SET reward = 'Said on entering the mosque, stepping in with the right foot.', reference = 'Muslim' WHERE id = 'bocp_255';
UPDATE azkar_items SET reward = 'Said while facing or pointing to the Black Stone at the start of each of the seven circuits.', reference = 'Sunnah of the Prophet ﷺ (cf. Bukhari)' WHERE id = 'bocp_256';
UPDATE azkar_items SET reward = 'Recited in this stretch of each circuit (also dua 1 of this book).', reference = 'Qur’an 2:201; Abu Dawud' WHERE id = 'bocp_257';
UPDATE azkar_items SET reward = 'Recited on approaching the Maqām after Tawaf, before praying two rakʿahs behind it.', reference = 'Qur’an 2:125; Muslim' WHERE id = 'bocp_258';
UPDATE azkar_items SET reward = 'Recited facing the Kaaba on Safa and on Marwa, with personal supplication in between; preceded by Qur’an 2:158.', reference = 'Muslim' WHERE id = 'bocp_259';
UPDATE azkar_items SET reward = 'The Prophet ﷺ said the best supplication is that of the Day of Arafah, and the best he and the prophets before him said were these words. Spend the afternoon in earnest, repeated supplication.', reference = 'Tirmidhi' WHERE id = 'bocp_260';
UPDATE azkar_items SET reward = 'After Fajr, face the qiblah, raise the hands, and make takbīr, tahlīl, and supplication until just before sunrise.', reference = 'Muslim (the Prophet’s practice at al-Mashʿar al-Ḥarām)' WHERE id = 'bocp_261';
UPDATE azkar_items SET reward = 'Said with each of the seven pebbles cast at each pillar.', reference = 'Bukhari & Muslim' WHERE id = 'bocp_262';
UPDATE azkar_items SET reward = 'Drink facing the qiblah, in three breaths. The Prophet ﷺ said Zamzam is for whatever it is drunk for — so supplicate for your needs.', reference = 'Ibn Majah (chain discussed)' WHERE id = 'bocp_263';
