import 'dart:io';

void main() {
  final Map<String, Map<String, String>> fixes = {
    'lib/screens/dashboard_screen.dart': {
      "'RECITE MORE.'": "AppLocalizations.of(context)?.reciteMore ?? 'RECITE MORE.'",
      "'HELP REAL LIVES.'": "AppLocalizations.of(context)?.helpRealLives ?? 'HELP REAL LIVES.'",
      "'Your Noor Points fund these projects'": "AppLocalizations.of(context)?.yourNoorPointsFundProjects ?? 'Your Noor Points fund these projects'",
      "'\\\$amount'": "'\\\$amount'",
      "'You both earn 500 Noor Points!'": "AppLocalizations.of(context)?.youBothEarnPoints ?? 'You both earn 500 Noor Points!'",
      "'Reward'": "AppLocalizations.of(context)?.reward ?? 'Reward'",
      "'Have an invite code?'": "AppLocalizations.of(context)?.haveInviteCode ?? 'Have an invite code?'",
      "'Enter code…'": "AppLocalizations.of(context)?.enterCode ?? 'Enter code…'",
      "'Apply'": "AppLocalizations.of(context)?.apply ?? 'Apply'",
      "'PLANT GOOD DEEDS'": "AppLocalizations.of(context)?.plantGoodDeeds ?? 'PLANT GOOD DEEDS'",
      "'Support this Cause'": "AppLocalizations.of(context)?.supportThisCause ?? 'Support this Cause'",
      "'Available Balance:'": "AppLocalizations.of(context)?.availableBalance ?? 'Available Balance:'",
      "'Donation Amount'": "AppLocalizations.of(context)?.donationAmount ?? 'Donation Amount'",
      "Text('points'": "Text(AppLocalizations.of(context)?.points ?? 'points'",
      "'Donate & Earn Reward'": "AppLocalizations.of(context)?.donateEarnReward ?? 'Donate & Earn Reward'",
      "'MAX'": "AppLocalizations.of(context)?.max ?? 'MAX'",
      "'Leaderboard'": "AppLocalizations.of(context)?.leaderboard ?? 'Leaderboard'",
      "'Loading…'": "AppLocalizations.of(context)?.loadingDots ?? 'Loading…'",
      "'Top 10 Contributors'": "AppLocalizations.of(context)?.topTenContributors ?? 'Top 10 Contributors'",
      "'Our Causes'": "AppLocalizations.of(context)?.ourCauses ?? 'Our Causes'",
      "'Donate your Noor Points to support real-world projects'": "AppLocalizations.of(context)?.donatePointsToSupport ?? 'Donate your Noor Points to support real-world projects'",
      "'No active projects right now'": "AppLocalizations.of(context)?.noActiveProjects ?? 'No active projects right now'",
      "'Check back soon insha\\'Allah'": "AppLocalizations.of(context)?.checkBackSoon ?? 'Check back soon insha\\'Allah'",
      "'Message copied — share or paste in WhatsApp!'": "AppLocalizations.of(context)?.messageCopied ?? 'Message copied — share or paste in WhatsApp!'",
      "'Lvl'": "AppLocalizations.of(context)?.lvl ?? 'Lvl'",
    },
    'lib/screens/impact_report_screen.dart': {
      "'Akhirah Balance'": "AppLocalizations.of(context)?.akhirahBalance ?? 'Akhirah Balance'",
      "'Priceless'": "AppLocalizations.of(context)?.priceless ?? 'Priceless'",
      "'Beyond what the world can hold'": "AppLocalizations.of(context)?.beyondWorldCanHold ?? 'Beyond what the world can hold'",
      "'Donate More & Earn'": "AppLocalizations.of(context)?.donateMoreEarn ?? 'Donate More & Earn'",
      "'Your Holdings'": "AppLocalizations.of(context)?.yourHoldings ?? 'Your Holdings'",
      "'See All →'": "AppLocalizations.of(context)?.seeAll ?? 'See All →'",
      "'Hasanaat Earned'": "AppLocalizations.of(context)?.hasanaatEarned ?? 'Hasanaat Earned'",
      "'Recorded in your Book of Deeds'": "AppLocalizations.of(context)?.recordedInBookOfDeeds ?? 'Recorded in your Book of Deeds'",
      "'Trees in Jannah'": "AppLocalizations.of(context)?.treesInJannah ?? 'Trees in Jannah'",
      "'From SubhanAllah & Tasbih'": "AppLocalizations.of(context)?.fromTasbih ?? 'From SubhanAllah & Tasbih'",
      "'Sins Forgiven'": "AppLocalizations.of(context)?.sinsForgiven ?? 'Sins Forgiven'",
      "'Like the foam of the sea'": "AppLocalizations.of(context)?.likeTheFoamOfSea ?? 'Like the foam of the sea'",
      "'Palaces Built'": "AppLocalizations.of(context)?.palacesBuilt ?? 'Palaces Built'",
      "'Surah Ikhlas & Sunnahs'": "AppLocalizations.of(context)?.surahIkhlasAndSunnahs ?? 'Surah Ikhlas & Sunnahs'",
      "'Treasures of Jannah'": "AppLocalizations.of(context)?.treasuresOfJannah ?? 'Treasures of Jannah'",
      "'Slaves Freed'": "AppLocalizations.of(context)?.slavesFreedom ?? 'Slaves Freed'",
      "'Equivalent reward earned'": "AppLocalizations.of(context)?.equivalentReward ?? 'Equivalent reward earned'",
      "'Sadaqah Given'": "AppLocalizations.of(context)?.sadaqahGiven ?? 'Sadaqah Given'",
      "'Points donated to community'": "AppLocalizations.of(context)?.pointsDonatedToCommunity ?? 'Points donated to community'",
      "'All time'": "AppLocalizations.of(context)?.allTimeLabel ?? 'All time'",
      "'Worship Activity'": "AppLocalizations.of(context)?.worshipActivity ?? 'Worship Activity'",
      "'Time spent in remembrance'": "AppLocalizations.of(context)?.timeSpentInRemembrance ?? 'Time spent in remembrance'",
      "'Noor Points Summary'": "AppLocalizations.of(context)?.noorPointsSummary ?? 'Noor Points Summary'",
      "'Total Points'": "AppLocalizations.of(context)?.totalPoints ?? 'Total Points'",
      "'Title'": "AppLocalizations.of(context)?.title ?? 'Title'",
      "'Every deed is recorded. Keep going!'": "AppLocalizations.of(context)?.everyDeedRecorded ?? 'Every deed is recorded. Keep going!'",
      "'Loading your report…'": "AppLocalizations.of(context)?.loadingYourReport ?? 'Loading your report…'",
    },
    'lib/screens/quran_hub_screen.dart': {
      "'Choose Surah'": "AppLocalizations.of(context)?.chooseSurah ?? 'Choose Surah'",
      "'Choose Verse'": "AppLocalizations.of(context)?.chooseVerse ?? 'Choose Verse'",
      "'Favourites'": "AppLocalizations.of(context)?.favourites ?? 'Favourites'",
      "'Bookmarks'": "AppLocalizations.of(context)?.bookmarks ?? 'Bookmarks'",
      "'Random Verse'": "AppLocalizations.of(context)?.randomVerse ?? 'Random Verse'",
      "'Sunnah Friday'": "AppLocalizations.of(context)?.sunnahFriday ?? 'Sunnah Friday'",
      "'Resume'": "AppLocalizations.of(context)?.resume ?? 'Resume'",
    },
    'lib/screens/quran_screen.dart': {
      "'Loading Quran…'": "AppLocalizations.of(context)?.loadingQuran ?? 'Loading Quran…'",
      "'Earn +10 Noor Points per verse read'": "AppLocalizations.of(context)?.earnPointsPerVerse ?? 'Earn +10 Noor Points per verse read'",
      "'Reading Settings'": "AppLocalizations.of(context)?.readingSettings ?? 'Reading Settings'",
      "'TAFSIR SOURCE'": "AppLocalizations.of(context)?.tafsirSource ?? 'TAFSIR SOURCE'",
      "'RECITER'": "AppLocalizations.of(context)?.reciter ?? 'RECITER'",
      "'DISPLAY'": "AppLocalizations.of(context)?.display ?? 'DISPLAY'",
      "'Show Arabic Text'": "AppLocalizations.of(context)?.showArabicText ?? 'Show Arabic Text'",
      "'Dark Mode'": "AppLocalizations.of(context)?.darkMode ?? 'Dark Mode'",
      "'FONT SIZE'": "AppLocalizations.of(context)?.fontSize ?? 'FONT SIZE'",
      "'Arabic'": "AppLocalizations.of(context)?.arabic ?? 'Arabic'",
      "'Urdu'": "AppLocalizations.of(context)?.urdu ?? 'Urdu'",
      "'English'": "AppLocalizations.of(context)?.english ?? 'English'",
      "'Select Surah'": "AppLocalizations.of(context)?.selectSurah ?? 'Select Surah'",
      "'Audio URL not loaded yet. Please wait...'": "AppLocalizations.of(context)?.audioNotLoaded ?? 'Audio URL not loaded yet. Please wait...'",
      "'Audio unavailable — check internet connection.'": "AppLocalizations.of(context)?.audioUnavailable ?? 'Audio unavailable — check internet connection.'",
      "'Sign in to save favourites'": "AppLocalizations.of(context)?.signInToSaveFavourites ?? 'Sign in to save favourites'",
      "'Added to Favourites'": "AppLocalizations.of(context)?.addedToFavourites ?? 'Added to Favourites'",
      "'Removed from Favourites'": "AppLocalizations.of(context)?.removedFromFavourites ?? 'Removed from Favourites'",
      "'APPEARANCE'": "AppLocalizations.of(context)?.appearance ?? 'APPEARANCE'",
      "'Comfortable night-time reading'": "AppLocalizations.of(context)?.comfortableNightReading ?? 'Comfortable night-time reading'",
      "'Focus Mode (Full Screen)'": "AppLocalizations.of(context)?.focusMode ?? 'Focus Mode (Full Screen)'",
      "'Hide app bar & nav for distraction-free reading'": "AppLocalizations.of(context)?.focusModeDesc ?? 'Hide app bar & nav for distraction-free reading'",
      "'Text Size'": "AppLocalizations.of(context)?.textSize ?? 'Text Size'",
      "'Small'": "AppLocalizations.of(context)?.small ?? 'Small'",
      "'Large'": "AppLocalizations.of(context)?.large ?? 'Large'",
      "'Theme Colour'": "AppLocalizations.of(context)?.themeColour ?? 'Theme Colour'",
      "'QURAN SCRIPT'": "AppLocalizations.of(context)?.quranScript ?? 'QURAN SCRIPT'",
      "'Quran Script'": "AppLocalizations.of(context)?.quranScriptLabel ?? 'Quran Script'",
      "'READING LAYOUT'": "AppLocalizations.of(context)?.readingLayout ?? 'READING LAYOUT'",
      "'Show Translation'": "AppLocalizations.of(context)?.showTranslation ?? 'Show Translation'",
      "'Display meaning below each verse'": "AppLocalizations.of(context)?.displayMeaningBelow ?? 'Display meaning below each verse'",
      "'Show Daily Progress'": "AppLocalizations.of(context)?.showDailyProgress ?? 'Show Daily Progress'",
      "'Progress bar & ayah count card'": "AppLocalizations.of(context)?.progressBarAyahCount ?? 'Progress bar & ayah count card'",
      "'Show Points Banner'": "AppLocalizations.of(context)?.showPointsBanner ?? 'Show Points Banner'",
      "'+Noor Points notification strip'": "AppLocalizations.of(context)?.noorPointsNotificationStrip ?? '+Noor Points notification strip'",
      "'Show Surah Header'": "AppLocalizations.of(context)?.showSurahHeader ?? 'Show Surah Header'",
      "'Surah name banner at top of page'": "AppLocalizations.of(context)?.surahNameBanner ?? 'Surah name banner at top of page'",
      "'AUDIO & PLAYBACK'": "AppLocalizations.of(context)?.audioPlayback ?? 'AUDIO & PLAYBACK'",
      "'Auto-Advance'": "AppLocalizations.of(context)?.autoAdvance ?? 'Auto-Advance'",
      "'Move to next verse when audio ends'": "AppLocalizations.of(context)?.moveToNextVerse ?? 'Move to next verse when audio ends'",
      "'Repeat Current Verse'": "AppLocalizations.of(context)?.repeatCurrentVerse ?? 'Repeat Current Verse'",
      "'Loop this ayah audio on repeat'": "AppLocalizations.of(context)?.loopAyahAudio ?? 'Loop this ayah audio on repeat'",
      "'NOTIFICATIONS & ALERTS'": "AppLocalizations.of(context)?.notificationsAlerts ?? 'NOTIFICATIONS & ALERTS'",
      "'Daily Reading Reminder'": "AppLocalizations.of(context)?.dailyReadingReminder ?? 'Daily Reading Reminder'",
      "'Push reminder to read Quran each day'": "AppLocalizations.of(context)?.pushReminderReadQuran ?? 'Push reminder to read Quran each day'",
      "'Milestone Sound Alerts'": "AppLocalizations.of(context)?.milestoneSoundAlerts ?? 'Milestone Sound Alerts'",
      "'Chime when you reach 10, 25, 50 ayahs'": "AppLocalizations.of(context)?.chimeAtMilestones ?? 'Chime when you reach 10, 25, 50 ayahs'",
      "'ADVANCED'": "AppLocalizations.of(context)?.advanced ?? 'ADVANCED'",
      "'Word-by-Word Mode'": "AppLocalizations.of(context)?.wordByWordMode ?? 'Word-by-Word Mode'",
      "'Show each Arabic word with its English meaning'": "AppLocalizations.of(context)?.showWordMeaning ?? 'Show each Arabic word with its English meaning'",
      "'Translation Language'": "AppLocalizations.of(context)?.translationLanguage ?? 'Translation Language'",
      "'Reciter:'": "AppLocalizations.of(context)?.reciterLabel ?? 'Reciter:'",
      "'Playing'": "AppLocalizations.of(context)?.playing ?? 'Playing'",
      "'Favourite'": "AppLocalizations.of(context)?.favourite ?? 'Favourite'",
      "'Bookmark'": "AppLocalizations.of(context)?.bookmark ?? 'Bookmark'",
      "'Goal: 50 ayahs/day'": "AppLocalizations.of(context)?.goalAyahs ?? 'Goal: 50 ayahs/day'",
      "'Next Page'": "AppLocalizations.of(context)?.nextPage ?? 'Next Page'",
      "'Exit'": "AppLocalizations.of(context)?.exit ?? 'Exit'",
      "'Mushaf Settings'": "AppLocalizations.of(context)?.mushafSettings ?? 'Mushaf Settings'",
      "'READING MODE'": "AppLocalizations.of(context)?.readingMode ?? 'READING MODE'",
      "'Scroll'": "AppLocalizations.of(context)?.scroll ?? 'Scroll'",
      "'Page Flip'": "AppLocalizations.of(context)?.pageFlip ?? 'Page Flip'",
      "'TRANSLATION'": "AppLocalizations.of(context)?.translationLabel ?? 'TRANSLATION'",
      "'Off'": "AppLocalizations.of(context)?.off ?? 'Off'",
      "'Split View'": "AppLocalizations.of(context)?.splitView ?? 'Split View'",
      "'SCRIPT'": "AppLocalizations.of(context)?.script ?? 'SCRIPT'",
      "'ACTIONS'": "AppLocalizations.of(context)?.actionsLabel ?? 'ACTIONS'",
      "'Page bookmarked!'": "AppLocalizations.of(context)?.pageBookmarked ?? 'Page bookmarked!'",
    },
    'lib/screens/dhikr_screen.dart': {
      "'Dua & Azkar Settings'": "AppLocalizations.of(context)?.duaAzkarSettings ?? 'Dua & Azkar Settings'",
      "'Show Transliteration'": "AppLocalizations.of(context)?.showTransliteration ?? 'Show Transliteration'",
      "'Show Illustration'": "AppLocalizations.of(context)?.showIllustration ?? 'Show Illustration'",
      "'Hide the visual artwork area'": "AppLocalizations.of(context)?.hideIllustrationArea ?? 'Hide the visual artwork area'",
      "'Arabic Font Style'": "AppLocalizations.of(context)?.arabicFontStyle ?? 'Arabic Font Style'",
      "'Daily Azkar Complete!'": "AppLocalizations.of(context)?.dailyAzkarComplete ?? 'Daily Azkar Complete!'",
      "'Masha\\'Allah! You tracked your daily Azkar and earned a bonus +50 Noor Points.'": "AppLocalizations.of(context)?.dailyAzkarBonusMsg ?? 'Masha\\'Allah! You tracked your daily Azkar and earned a bonus +50 Noor Points.'",
      "'Awesome'": "AppLocalizations.of(context)?.awesome ?? 'Awesome'",
      "'Start Now'": "AppLocalizations.of(context)?.startNow ?? 'Start Now'",
      "'Mark as Done'": "AppLocalizations.of(context)?.markAsDone ?? 'Mark as Done'",
      "'Enter custom count'": "AppLocalizations.of(context)?.enterCustomCount ?? 'Enter custom count'",
      "'Reset to default'": "AppLocalizations.of(context)?.resetToDefault ?? 'Reset to default'",
      "'No Azkar found here.'": "AppLocalizations.of(context)?.noAzkarFound ?? 'No Azkar found here.'",
      "'Reference'": "AppLocalizations.of(context)?.reference ?? 'Reference'",
      "'Benefit'": "AppLocalizations.of(context)?.benefit ?? 'Benefit'",
      "'Between Subh-e-Sadiq to Sunrise'": "AppLocalizations.of(context)?.betweenSubhSunrise ?? 'Between Subh-e-Sadiq to Sunrise'",
      "'Between Asr and Maghrib'": "AppLocalizations.of(context)?.betweenAsrMaghrib ?? 'Between Asr and Maghrib'",
      "'Before Sleeping'": "AppLocalizations.of(context)?.beforeSleeping ?? 'Before Sleeping'",
      "'Upon Waking Up'": "AppLocalizations.of(context)?.uponWakingUp ?? 'Upon Waking Up'",
      "'After Each Prayer'": "AppLocalizations.of(context)?.afterEachPrayer ?? 'After Each Prayer'",
      "'Anytime — Especially After Prayer'": "AppLocalizations.of(context)?.anytimeEspeciallyAfterPrayer ?? 'Anytime — Especially After Prayer'",
      "'Anytime — Morning & Evening'": "AppLocalizations.of(context)?.anytimeMorningEvening ?? 'Anytime — Morning & Evening'",
      "'During the Night'": "AppLocalizations.of(context)?.duringTheNight ?? 'During the Night'",
      "'Anytime'": "AppLocalizations.of(context)?.anytime ?? 'Anytime'",
      "'As per Sunnah'": "AppLocalizations.of(context)?.asPerSunnah ?? 'As per Sunnah'",
      "'When Eating or Drinking'": "AppLocalizations.of(context)?.whenEatingDrinking ?? 'When Eating or Drinking'",
      "'Upon Entering / Leaving Home'": "AppLocalizations.of(context)?.enteringLeavingHome ?? 'Upon Entering / Leaving Home'",
      "'Before or After Wudu'": "AppLocalizations.of(context)?.beforeAfterWudu ?? 'Before or After Wudu'",
      "'When Getting Dressed'": "AppLocalizations.of(context)?.whenGettingDressed ?? 'When Getting Dressed'",
      "'Upon Having a Bad Dream'": "AppLocalizations.of(context)?.uponBadDream ?? 'Upon Having a Bad Dream'",
      "'For the Ummah — Anytime'": "AppLocalizations.of(context)?.forUmmahAnytime ?? 'For the Ummah — Anytime'",
    },
    'lib/screens/dhikr_hub_screen.dart': {
      "'Duas of Ummah'": "AppLocalizations.of(context)?.duasOfUmmah ?? 'Duas of Ummah'",
      "'Before Sleep'": "AppLocalizations.of(context)?.beforeSleepCat ?? 'Before Sleep'",
      "'Tahajjud'": "AppLocalizations.of(context)?.tahajjud ?? 'Tahajjud'",
      "'Salah'": "AppLocalizations.of(context)?.salah ?? 'Salah'",
      "'Salawat'": "AppLocalizations.of(context)?.salawat ?? 'Salawat'",
      "'Sunnah Duas'": "AppLocalizations.of(context)?.sunnahDuas ?? 'Sunnah Duas'",
      "'Quranic Duas'": "AppLocalizations.of(context)?.quranicDuas ?? 'Quranic Duas'",
      "'Istighfar'": "AppLocalizations.of(context)?.istighfar ?? 'Istighfar'",
      "'Dhikar All Times'": "AppLocalizations.of(context)?.dhikarAllTimes ?? 'Dhikar All Times'",
      "'Names of Allah'": "AppLocalizations.of(context)?.namesOfAllah ?? 'Names of Allah'",
      "'Nightmares'": "AppLocalizations.of(context)?.nightmares ?? 'Nightmares'",
      "'Waking up'": "AppLocalizations.of(context)?.wakingUp ?? 'Waking up'",
      "'Clothes'": "AppLocalizations.of(context)?.clothes ?? 'Clothes'",
      "'Wudu'": "AppLocalizations.of(context)?.wudu ?? 'Wudu'",
      "'Food & Drink'": "AppLocalizations.of(context)?.foodAndDrink ?? 'Food & Drink'",
      "'Home'": "AppLocalizations.of(context)?.home ?? 'Home'",
      "'Istikharah'": "AppLocalizations.of(context)?.istikharah ?? 'Istikharah'",
      "'Adaan & Masjid'": "AppLocalizations.of(context)?.adaanAndMasjid ?? 'Adaan & Masjid'",
      "'Diff & Happy'": "AppLocalizations.of(context)?.diffAndHappy ?? 'Diff & Happy'",
      "'Iman Protect'": "AppLocalizations.of(context)?.imanProtect ?? 'Iman Protect'",
      "'Travel'": "AppLocalizations.of(context)?.travel ?? 'Travel'",
      "'Shopping'": "AppLocalizations.of(context)?.shopping ?? 'Shopping'",
      "'Marriage'": "AppLocalizations.of(context)?.marriage ?? 'Marriage'",
      "'Social'": "AppLocalizations.of(context)?.social ?? 'Social'",
      "'Nature'": "AppLocalizations.of(context)?.nature ?? 'Nature'",
      "'Death'": "AppLocalizations.of(context)?.death ?? 'Death'",
      "'Gatherings'": "AppLocalizations.of(context)?.gatherings ?? 'Gatherings'",
      "'Hajj & Umrah'": "AppLocalizations.of(context)?.hajjAndUmrah ?? 'Hajj & Umrah'",
      "'Daily Essentials'": "AppLocalizations.of(context)?.dailyEssentials ?? 'Daily Essentials'",
    },
    'lib/screens/tafsir_screen.dart': {
      "'Read Tafsir'": "AppLocalizations.of(context)?.readTafsir ?? 'Read Tafsir'",
      "'Translation'": "AppLocalizations.of(context)?.translation ?? 'Translation'",
      "'Loading tafsir...'": "AppLocalizations.of(context)?.loadingTafsir ?? 'Loading tafsir...'",
      "'Tafsir not available for this ayah.'": "AppLocalizations.of(context)?.tafsirNotAvailable ?? 'Tafsir not available for this ayah.'",
      "'Arabic Scripture'": "AppLocalizations.of(context)?.arabicScripture ?? 'Arabic Scripture'",
      "'Urdu Scripture'": "AppLocalizations.of(context)?.urduScripture ?? 'Urdu Scripture'",
      "'English Commentary'": "AppLocalizations.of(context)?.englishCommentary ?? 'English Commentary'",
      "'Previous'": "AppLocalizations.of(context)?.previous ?? 'Previous'",
      "'Next Ayah'": "AppLocalizations.of(context)?.nextAyah ?? 'Next Ayah'",
    },
    'lib/screens/tafsir_hub_screen.dart': {
      "'Read & Listen Tafsir'": "AppLocalizations.of(context)?.readListenTafsir ?? 'Read & Listen Tafsir'",
      "'Deep understanding of the Holy Quran'": "AppLocalizations.of(context)?.deepUnderstanding ?? 'Deep understanding of the Holy Quran'",
      "'Earn points for every 10 min of Tafsir listening'": "AppLocalizations.of(context)?.earnPointsTafsir ?? 'Earn points for every 10 min of Tafsir listening'",
      "'Featured Surahs'": "AppLocalizations.of(context)?.featuredSurahs ?? 'Featured Surahs'",
      "'Browse All 114 Surahs'": "AppLocalizations.of(context)?.browseAll114 ?? 'Browse All 114 Surahs'",
    },
    'lib/screens/project_detail_screen.dart': {
      "'Fully Funded ✓'": "AppLocalizations.of(context)?.fullyFunded ?? 'Fully Funded ✓'",
      "'No Points Available'": "AppLocalizations.of(context)?.noPointsAvailable ?? 'No Points Available'",
      "'Community Progress'": "AppLocalizations.of(context)?.communityProgress ?? 'Community Progress'",
      "'pts raised'": "AppLocalizations.of(context)?.ptsRaised ?? 'pts raised'",
      "'days left'": "AppLocalizations.of(context)?.daysLeft ?? 'days left'",
      "'Last day!'": "AppLocalizations.of(context)?.lastDay ?? 'Last day!'",
      "'deadline'": "AppLocalizations.of(context)?.deadline ?? 'deadline'",
      "'Campaign Story'": "AppLocalizations.of(context)?.campaignStory ?? 'Campaign Story'",
      "'Campaign'": "AppLocalizations.of(context)?.campaign ?? 'Campaign'",
      "'No story added yet.'": "AppLocalizations.of(context)?.noStoryYet ?? 'No story added yet.'",
      "'Check the admin panel to add a campaign story.'": "AppLocalizations.of(context)?.checkAdminPanel ?? 'Check the admin panel to add a campaign story.'",
      "'No updates yet.'": "AppLocalizations.of(context)?.noUpdatesYet ?? 'No updates yet.'",
      "'Check back soon for campaign news.'": "AppLocalizations.of(context)?.checkBackForNews ?? 'Check back soon for campaign news.'",
      "'Yesterday'": "AppLocalizations.of(context)?.yesterday ?? 'Yesterday'",
      "'Share Campaign'": "AppLocalizations.of(context)?.shareCampaign ?? 'Share Campaign'",
      "'Spread the word and help this cause reach its goal.'": "AppLocalizations.of(context)?.spreadTheWord ?? 'Spread the word and help this cause reach its goal.'",
      "'Share via WhatsApp'": "AppLocalizations.of(context)?.shareViaWhatsApp ?? 'Share via WhatsApp'",
      "'More sharing options…'": "AppLocalizations.of(context)?.moreSharingOptions ?? 'More sharing options…'",
      "'Slide to adjust'": "AppLocalizations.of(context)?.slideToAdjust ?? 'Slide to adjust'",
      "'Balance'": "AppLocalizations.of(context)?.balance ?? 'Balance'",
    },
    'lib/screens/onboarding_screen.dart': {
      "'Peace Be\\nUpon You'": "AppLocalizations.of(context)?.onboarding1Title ?? 'Peace Be\\nUpon You'",
      "'Welcome to Noor Rewards — where every good deed is a step closer to Allah\\'s mercy and light.'": "AppLocalizations.of(context)?.onboarding1Subtitle ?? 'Welcome to Noor Rewards — where every good deed is a step closer to Allah\\'s mercy and light.'",
      "'Two Rewards.\\nOne Action.'": "AppLocalizations.of(context)?.onboarding2Title ?? 'Two Rewards.\\nOne Action.'",
      "'Every word you read earns you Sawab — a light in your Akhirah.\\nYour Noor Coins fund real causes that change real lives.'": "AppLocalizations.of(context)?.onboarding2Subtitle ?? 'Every word you read earns you Sawab — a light in your Akhirah.\\nYour Noor Coins fund real causes that change real lives.'",
      "'Remember\\nAllah Always'": "AppLocalizations.of(context)?.onboarding3Title ?? 'Remember\\nAllah Always'",
      "'A heart that remembers Allah finds peace in every breath. Track your daily zikr and let every bead count.'": "AppLocalizations.of(context)?.onboarding3Subtitle ?? 'A heart that remembers Allah finds peace in every breath. Track your daily zikr and let every bead count.'",
      "'Reflect &\\nGrow Daily'": "AppLocalizations.of(context)?.onboarding4Title ?? 'Reflect &\\nGrow Daily'",
      "'The Quran is a guide for all of mankind. Unlock verses, daily duas, and reflections tailored for your journey.'": "AppLocalizations.of(context)?.onboarding4Subtitle ?? 'The Quran is a guide for all of mankind. Unlock verses, daily duas, and reflections tailored for your journey.'",
      "'Give &\\nEarn Blessings'": "AppLocalizations.of(context)?.onboarding5Title ?? 'Give &\\nEarn Blessings'",
      "'Sadaqah extinguishes sin as water extinguishes fire. Earn rewards for every act of charity and kindness.'": "AppLocalizations.of(context)?.onboarding5Subtitle ?? 'Sadaqah extinguishes sin as water extinguishes fire. Earn rewards for every act of charity and kindness.'",
    },
    'lib/screens/start_journey_screen.dart': {
      "'Begin Your Journey'": "AppLocalizations.of(context)?.beginYourJourney ?? 'Begin Your Journey'",
      "'Enter the Garden'": "AppLocalizations.of(context)?.enterTheGarden ?? 'Enter the Garden'",
      "'By signing up, you agree to our Terms & Privacy Policy'": "AppLocalizations.of(context)?.bySigningUp ?? 'By signing up, you agree to our Terms & Privacy Policy'",
      "'LIGHT OF MERCY'": "AppLocalizations.of(context)?.lightOfMercy ?? 'LIGHT OF MERCY'",
      "'Noor Rewards'": "AppLocalizations.of(context)?.noorRewards ?? 'Noor Rewards'",
      "'Start Your Journey'": "AppLocalizations.of(context)?.startYourJourney ?? 'Start Your Journey'",
      "'Track your spiritual growth, join the community, and unlock exclusive rewards for every good deed.'": "AppLocalizations.of(context)?.trackSpiritualGrowth ?? 'Track your spiritual growth, join the community, and unlock exclusive rewards for every good deed.'",
      "'Continue with Google'": "AppLocalizations.of(context)?.continueWithGoogle ?? 'Continue with Google'",
      "'Continue with Quran.com'": "AppLocalizations.of(context)?.continueWithQuran ?? 'Continue with Quran.com'",
    }
  };

  for (final filePath in fixes.keys) {
    final file = File(filePath);
    if (!file.existsSync()) {
      print('File not found: \\\$filePath');
      continue;
    }
    
    String content = file.readAsStringSync();
    int replacements = 0;
    
    for (final key in fixes[filePath]!.keys) {
      final replacement = fixes[filePath]![key]!;
      if (content.contains(key)) {
        content = content.replaceAll(key, replacement);
        replacements++;
      }
    }
    
    if (replacements > 0) {
      file.writeAsStringSync(content);
      print('Updated \\\$replacements strings in \\\$filePath');
    }
  }
}
