// Merges Gemini's azkar translation batches into two Supabase migrations.
//
// Reads:
//   build/azkar_translation_batches/index.json           — id -> {arabic, en, category}
//   build/azkar_translation_batches/batch_NN_source.json
//   build/azkar_translation_batches/output/batch_NN_output.md
//
// Writes:
//   supabase/migrations/<YYYYMMDD>_010_azkar_translation_add_cols.sql
//     • ALTER TABLE azkar_items ADD COLUMN IF NOT EXISTS translation_<lang> text; (× 7)
//     • Populates translation_ur + translation_ar via CTE VALUES.
//   supabase/migrations/<YYYYMMDD>_020_azkar_translation_fr_id_ms_ru_tr.sql
//     • Populates the remaining 5 locales.
//
// Split matches the short_benefit pipeline so admins can review non-EN
// locales one script at a time.
//
// Usage:
//   dart run scripts/merge_azkar_translation_batches.dart

import 'dart:convert';
import 'dart:io';

const _batchDir = 'build/azkar_translation_batches';
const _outputDir = 'build/azkar_translation_batches/output';
const _migrationsDir = 'supabase/migrations';
const _locales = ['ur', 'ar', 'fr', 'id', 'ms', 'ru', 'tr'];

void main() {
  final indexFile = File('$_batchDir/index.json');
  if (!indexFile.existsSync()) {
    stderr.writeln('$_batchDir/index.json missing — run generator first.');
    exit(1);
  }
  final index = (jsonDecode(indexFile.readAsStringSync()) as Map)
      .cast<String, dynamic>();

  final sourceFiles = Directory(_batchDir)
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('_source.json'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final byLocale = <String, Map<String, String>>{
    for (final l in _locales) l: {},
  };
  final missing = <String>[];
  final errors = <String>[];

  for (final srcFile in sourceFiles) {
    final batchName = srcFile.uri.pathSegments.last
        .replaceFirst('_source.json', '');
    final outFile = File('$_outputDir/${batchName}_output.md');
    if (!outFile.existsSync()) {
      missing.add(batchName);
      continue;
    }
    final source = (jsonDecode(srcFile.readAsStringSync()) as Map)
        .cast<String, dynamic>();
    final parsed = _parseOutputBlocks(outFile.readAsStringSync());

    for (final loc in _locales) {
      final block = parsed[loc];
      if (block == null) {
        errors.add('$batchName.$loc: locale block missing');
        continue;
      }
      for (final id in source.keys) {
        final v = block[id];
        if (v is String && v.trim().isNotEmpty) {
          byLocale[loc]![id] = v.trim();
        } else {
          errors.add('$batchName.$loc.$id: missing or empty');
        }
      }
    }
  }

  // Coverage report.
  print('Coverage:');
  for (final loc in _locales) {
    print('  $loc: ${byLocale[loc]!.length} / ${index.length}');
  }
  if (missing.isNotEmpty) {
    print('');
    print('Missing batches: ${missing.join(", ")}');
  }
  if (errors.isNotEmpty) {
    print('');
    print('${errors.length} row-level validation errors (skipped).');
  }

  // ── Emit migrations ────────────────────────────────────────────────────
  final date = DateTime.now().toUtc();
  final stamp =
      '${date.year.toString().padLeft(4, '0')}${date.month.toString().padLeft(2, '0')}${date.day.toString().padLeft(2, '0')}';

  final stage2Path =
      '$_migrationsDir/${stamp}_010_azkar_translation_add_cols_ur_ar.sql';
  final stage3Path =
      '$_migrationsDir/${stamp}_020_azkar_translation_fr_id_ms_ru_tr.sql';

  Directory(_migrationsDir).createSync(recursive: true);
  File(stage2Path).writeAsStringSync(_stage2(byLocale, index));
  File(stage3Path).writeAsStringSync(_stage3(byLocale, index));

  print('');
  print('Wrote:');
  print('  $stage2Path');
  print('  $stage3Path');
}

String _stage2(
  Map<String, Map<String, String>> byLocale,
  Map<String, dynamic> index,
) {
  final buf = StringBuffer()
    ..writeln('-- Azkar translation: add locale columns + populate ur, ar.')
    ..writeln('--')
    ..writeln('-- Generated by scripts/merge_azkar_translation_batches.dart from Gemini output.')
    ..writeln('-- Source translations grounded in Hisnul Muslim / Fortress of the Muslim wording per locale.')
    ..writeln('--')
    ..writeln('-- Runtime lookup: lib/screens/dhikr_screen.dart::_Azkar.pick(\'translation\')')
    ..writeln('-- already reads translation_<locale> and falls back to English, so no client change needed.')
    ..writeln();
  for (final loc in _locales) {
    buf.writeln(
      'ALTER TABLE azkar_items ADD COLUMN IF NOT EXISTS translation_$loc text;',
    );
  }
  buf.writeln();
  _emitLocalePayload(buf, byLocale, index, ['ur', 'ar']);
  return buf.toString();
}

String _stage3(
  Map<String, Map<String, String>> byLocale,
  Map<String, dynamic> index,
) {
  final buf = StringBuffer()
    ..writeln('-- Azkar translation: populate fr, id, ms, ru, tr.')
    ..writeln('--')
    ..writeln('-- Ship after 010_ if you want to stage the rollout, or apply together.')
    ..writeln();
  _emitLocalePayload(buf, byLocale, index, ['fr', 'id', 'ms', 'ru', 'tr']);
  return buf.toString();
}

void _emitLocalePayload(
  StringBuffer buf,
  Map<String, Map<String, String>> byLocale,
  Map<String, dynamic> index,
  List<String> locales,
) {
  final colList = locales.map((l) => 'translation_$l').join(', ');
  final selectList = locales.map((l) => 'v.translation_$l').join(', ');
  final setList = locales
      .map((l) => 'translation_$l = v.translation_$l')
      .join(', ');

  buf.writeln('WITH v (id, ${locales.map((l) => 'translation_$l').join(', ')}) AS (');
  buf.writeln('VALUES');
  final lines = <String>[];
  for (final id in index.keys) {
    final rowValues = locales.map((l) => byLocale[l]?[id]).toList();
    if (rowValues.any((v) => v == null)) continue;
    final quoted = <String>['${_pgQuote(id)}::text'];
    for (var i = 0; i < locales.length; i++) {
      quoted.add('${_pgQuote(rowValues[i]!)}::text');
    }
    lines.add('  (${quoted.join(', ')})');
  }
  buf.writeln(lines.join(',\n'));
  buf.writeln(')');
  buf.writeln('UPDATE azkar_items a');
  buf.writeln('SET $setList');
  buf.writeln('FROM v');
  buf.writeln('WHERE a.id = v.id;');
  buf.writeln();
  // Emit the column list for reference / grep-friendliness.
  buf.writeln('-- Columns touched: $colList');
  buf.writeln('-- Referenced as:   $selectList');
}

// PostgreSQL dollar-quoted literal — safe for Arabic + Cyrillic + curly
// apostrophes without the quote-doubling gymnastics.
String _pgQuote(String s) {
  var tag = 'sb';
  while (s.contains('\$$tag\$')) {
    tag += 'x';
  }
  return '\$$tag\$$s\$$tag\$';
}

Map<String, Map<String, dynamic>> _parseOutputBlocks(String content) {
  final fencedContentRe = RegExp(
    r'```(?:json)?\s*\n([\s\S]*?)\n\s*```',
    multiLine: true,
  );
  final candidates = <String>[];
  for (final m in fencedContentRe.allMatches(content)) {
    candidates.add(m.group(1)!.trim());
  }
  candidates.add(content.trim());
  for (final candidate in candidates) {
    try {
      final decoded = jsonDecode(candidate);
      if (decoded is Map<String, dynamic>) {
        final localeKeys = decoded.keys.where(_locales.contains).toList();
        if (localeKeys.length >= 2) {
          final nested = <String, Map<String, dynamic>>{};
          for (final loc in localeKeys) {
            final v = decoded[loc];
            if (v is Map<String, dynamic>) nested[loc] = v;
          }
          if (nested.length >= 2) return nested;
        }
      }
    } catch (_) {/* try next */}
  }
  return <String, Map<String, dynamic>>{};
}
