// Merges Gemini's push-notification variant translations into a
// Supabase migration file that seeds `notification_variants` with one
// row per (notification_type, locale) for the 7 previously-untranslated
// push types.
//
// Reads:
//   build/notification_variant_batches/source.json    — canonical EN + routes
//   build/notification_variant_batches/output/output.md — Gemini response
//
// Writes:
//   supabase/migrations/<YYYYMMDD>_050_notification_variants_fallback_translations.sql
//
// Placeholder & length validation:
//   - Every `{name}` in the source title/body must survive in the translation.
//   - Empty or missing translations are skipped and reported at the end.
//
// Usage:
//   dart run scripts/merge_notification_variant_batches.dart

import 'dart:convert';
import 'dart:io';

const _batchDir = 'build/notification_variant_batches';
const _outputPath = 'build/notification_variant_batches/output/output.md';
const _migrationsDir = 'supabase/migrations';
const _locales = ['ur', 'ar', 'fr', 'id', 'ms', 'ru', 'tr'];
final _placeholderRe = RegExp(r'\{([a-zA-Z][a-zA-Z0-9_]*)\}');

void main() {
  final srcFile = File('$_batchDir/source.json');
  final outFile = File(_outputPath);
  if (!srcFile.existsSync()) {
    stderr.writeln('$_batchDir/source.json missing — run generator first.');
    exit(1);
  }
  if (!outFile.existsSync()) {
    stderr.writeln('$_outputPath missing — paste Gemini output there.');
    exit(1);
  }

  final source = (jsonDecode(srcFile.readAsStringSync()) as Map)
      .cast<String, dynamic>();
  final parsed = _parseOutputBlocks(outFile.readAsStringSync());

  final errors = <String>[];
  final rows = <_VariantRow>[];

  for (final locale in _locales) {
    final block = parsed[locale];
    if (block == null) {
      errors.add('$locale: locale block missing from Gemini output');
      continue;
    }
    for (final entry in source.entries) {
      final type = entry.key;
      final meta = (entry.value as Map).cast<String, dynamic>();
      final enTitle = meta['title'] as String;
      final enBody = meta['body'] as String?;
      final route = meta['route'] as String?;

      final trTitle = block['$type.title'];
      if (trTitle is! String || trTitle.trim().isEmpty) {
        errors.add('$locale.$type.title: missing or empty');
        continue;
      }
      if (!_placeholdersPreserved(enTitle, trTitle)) {
        errors.add('$locale.$type.title: placeholder(s) not preserved');
        continue;
      }

      String? trBody;
      if (enBody != null) {
        final b = block['$type.body'];
        if (b is! String || b.trim().isEmpty) {
          errors.add('$locale.$type.body: missing or empty');
          continue;
        }
        if (!_placeholdersPreserved(enBody, b)) {
          errors.add('$locale.$type.body: placeholder(s) not preserved');
          continue;
        }
        trBody = b;
      }

      rows.add(_VariantRow(
        type: type,
        locale: locale,
        title: trTitle,
        body: trBody ?? '',
        route: route,
      ));
    }
  }

  if (rows.isEmpty) {
    stderr.writeln('No valid rows produced. Errors:');
    for (final e in errors) {
      stderr.writeln('  $e');
    }
    exit(1);
  }

  // Emit migration.
  final date = DateTime.now().toUtc();
  final stamp =
      '${date.year.toString().padLeft(4, '0')}${date.month.toString().padLeft(2, '0')}${date.day.toString().padLeft(2, '0')}';
  final migrationName = '${stamp}_050_notification_variants_fallback_translations.sql';
  final outPath = '$_migrationsDir/$migrationName';

  final buf = StringBuffer();
  buf.writeln('-- Notification variants: fallback translations for 7 push types');
  buf.writeln('-- (akhirah_milestone, disengagement_pause, featured_dua,');
  buf.writeln('--  project_funded, streak_milestone, surah_kahf_friday, validate_seeds).');
  buf.writeln('--');
  buf.writeln('-- Generated by scripts/merge_notification_variant_batches.dart from');
  buf.writeln('-- Gemini output. Placeholder tokens ({milestone}, {streak}, {streakType},');
  buf.writeln('-- {projectName}) are preserved verbatim and substituted at send time by');
  buf.writeln('-- supabase/functions/_shared/variants.ts::fillTemplate.');
  buf.writeln('--');
  buf.writeln('-- Idempotency: one INSERT per (type, locale). Existing rows are left');
  buf.writeln('-- untouched.');
  buf.writeln();
  buf.writeln('INSERT INTO public.notification_variants (notification_type, locale, title, body, route) VALUES');
  final lines = <String>[];
  for (final r in rows) {
    lines.add(
      '  ('
      "${_sql(r.type)}, "
      "${_sql(r.locale)}, "
      "${_sql(r.title)}, "
      "${_sql(r.body)}, "
      "${r.route == null ? 'NULL' : _sql(r.route!)}"
      ')',
    );
  }
  buf.writeln('${lines.join(',\n')};');

  Directory(_migrationsDir).createSync(recursive: true);
  File(outPath).writeAsStringSync(buf.toString());

  print('Wrote $outPath');
  print('  ${rows.length} rows across ${_locales.length} locales.');
  if (errors.isNotEmpty) {
    print('');
    print('${errors.length} validation errors — those rows were skipped:');
    for (final e in errors) {
      print('  $e');
    }
  }
}

class _VariantRow {
  final String type;
  final String locale;
  final String title;
  final String body;
  final String? route;
  _VariantRow({
    required this.type,
    required this.locale,
    required this.title,
    required this.body,
    required this.route,
  });
}

bool _placeholdersPreserved(String enText, String trText) {
  final src = _placeholderRe
      .allMatches(enText)
      .map((m) => m.group(0)!)
      .toSet();
  final dst = _placeholderRe
      .allMatches(trText)
      .map((m) => m.group(0)!)
      .toSet();
  return src.difference(dst).isEmpty;
}

// Single-quote a SQL string; doubles internal quotes and preserves
// UTF-8. Uses Postgres dollar-quoting when the value already contains
// a single quote to keep the migration readable and unambiguous.
String _sql(String value) {
  if (!value.contains("'")) return "'$value'";
  var tag = 'sb';
  while (value.contains('\$$tag\$')) {
    tag += 'x';
  }
  return '\$$tag\$$value\$$tag\$';
}

Map<String, Map<String, dynamic>> _parseOutputBlocks(String content) {
  final fencedContentRe = RegExp(
    r'```(?:json)?\s*\n([\s\S]*?)\n\s*```',
    multiLine: true,
  );
  final candidates = <String>[];
  for (final m in fencedContentRe.allMatches(content)) {
    candidates.add(m.group(1)!.trim());
  }
  candidates.add(content.trim());
  for (final candidate in candidates) {
    try {
      final decoded = jsonDecode(candidate);
      if (decoded is Map<String, dynamic>) {
        final localeKeys = decoded.keys.where(_locales.contains).toList();
        if (localeKeys.length >= 2) {
          final nested = <String, Map<String, dynamic>>{};
          for (final loc in localeKeys) {
            final v = decoded[loc];
            if (v is Map<String, dynamic>) nested[loc] = v;
          }
          if (nested.length >= 2) return nested;
        }
      }
    } catch (_) {/* try next */}
  }
  return <String, Map<String, dynamic>>{};
}
