// Merges Gemini-produced tagline translation batches into a single
// Dart file used at runtime by `_pickTagline`.
//
// Reads:
//   build/tagline_batches/index.json           — synthetic-key -> EN
//   build/tagline_batches/batch_NN_source.json — batch slice
//   build/tagline_batches/output/batch_NN_output.md — LLM response
//
// Writes:
//   lib/data/tagline_translations.dart — const map keyed by locale, then
//   by the English tagline string. Runtime lookup is
//   `kTaglineTranslations[locale]?[english] ?? english`.
//
// The output parser supports the same three shapes as the .arb merger:
//   1. Nested {ur:{},ar:{},…} object (Gemini default with new prompt)
//   2. Per-locale fenced JSON blocks
//   3. Bare positional JSON objects
//
// Usage:
//   dart run scripts/merge_tagline_batches.dart

import 'dart:convert';
import 'dart:io';

const _batchDir = 'build/tagline_batches';
const _outputDir = 'build/tagline_batches/output';
const _outputFile = 'lib/data/tagline_translations.dart';
const _locales = ['ur', 'ar', 'fr', 'id', 'ms', 'ru', 'tr'];

void main() {
  final indexFile = File('$_batchDir/index.json');
  if (!indexFile.existsSync()) {
    stderr.writeln(
      'index.json missing. Run generate_tagline_batches.dart first.',
    );
    exit(1);
  }
  final index = (jsonDecode(indexFile.readAsStringSync()) as Map)
      .cast<String, String>();

  final outDir = Directory(_outputDir);
  if (!outDir.existsSync()) {
    stderr.writeln('$_outputDir missing.');
    exit(1);
  }

  final sourceFiles = Directory(_batchDir)
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('_source.json'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  // Per-locale map: { English string -> localized string }
  final byLocale = <String, Map<String, String>>{
    for (final l in _locales) l: {},
  };
  final missing = <String>[];
  var applied = 0;

  for (final srcFile in sourceFiles) {
    final batchName = srcFile.uri.pathSegments.last
        .replaceFirst('_source.json', '');
    final outFile = File('$_outputDir/${batchName}_output.md');
    if (!outFile.existsSync()) {
      missing.add(batchName);
      continue;
    }
    final source = (jsonDecode(srcFile.readAsStringSync()) as Map)
        .cast<String, String>();
    final parsed = _parseOutputBlocks(outFile.readAsStringSync());

    for (final loc in _locales) {
      final block = parsed[loc];
      if (block == null) continue;
      for (final entry in source.entries) {
        final synthKey = entry.key;
        final enText = entry.value;
        final translation = block[synthKey];
        if (translation is! String || translation.trim().isEmpty) continue;
        byLocale[loc]![enText] = translation;
        applied++;
      }
    }
  }

  // Emit Dart file.
  final buf = StringBuffer();
  buf.writeln('// GENERATED by scripts/merge_tagline_batches.dart — do not edit.');
  buf.writeln('//');
  buf.writeln('// Dhikr tagline translations. Runtime lookup:');
  buf.writeln('//   kTaglineTranslations[localeCode]?[englishTagline] ?? englishTagline');
  buf.writeln('//');
  buf.writeln('// Source: build/tagline_batches/index.json (${index.length} unique EN strings).');
  buf.writeln();
  buf.writeln('const kTaglineTranslations = <String, Map<String, String>>{');
  for (final loc in _locales) {
    final map = byLocale[loc]!;
    buf.writeln("  '$loc': <String, String>{");
    // Emit in the same order as index.json so diffs are stable.
    for (final entry in index.entries) {
      final en = entry.value;
      final tr = map[en];
      if (tr == null) continue;
      buf.writeln('    ${_dartString(en)}: ${_dartString(tr)},');
    }
    buf.writeln('  },');
  }
  buf.writeln('};');

  final target = File(_outputFile);
  target.parent.createSync(recursive: true);
  target.writeAsStringSync(buf.toString());

  print('Wrote $_outputFile');
  print('  $applied per-locale translations across ${_locales.length} locales.');
  for (final loc in _locales) {
    print('    $loc: ${byLocale[loc]!.length} / ${index.length}');
  }
  if (missing.isNotEmpty) {
    print('');
    print('Missing batches: ${missing.join(", ")}');
  }
}

String _dartString(String s) {
  // Dollar-safe raw single-quoted string, unless it contains `'` — then
  // fall back to double-quoted with escapes.
  if (!s.contains(r'$') && !s.contains(r'\') && !s.contains("'")) {
    return "'$s'";
  }
  final escaped = s
      .replaceAll(r'\', r'\\')
      .replaceAll(r'$', r'\$')
      .replaceAll('"', r'\"');
  return '"$escaped"';
}

Map<String, Map<String, dynamic>> _parseOutputBlocks(String content) {
  // 1. Nested single object with locale keys — Gemini default.
  final fencedContentRe = RegExp(
    r'```(?:json)?\s*\n([\s\S]*?)\n\s*```',
    multiLine: true,
  );
  final candidates = <String>[];
  for (final m in fencedContentRe.allMatches(content)) {
    candidates.add(m.group(1)!.trim());
  }
  candidates.add(content.trim());
  for (final candidate in candidates) {
    try {
      final decoded = jsonDecode(candidate);
      if (decoded is Map<String, dynamic>) {
        final localeKeys = decoded.keys.where(_locales.contains).toList();
        if (localeKeys.length >= 2) {
          final nested = <String, Map<String, dynamic>>{};
          for (final loc in localeKeys) {
            final v = decoded[loc];
            if (v is Map<String, dynamic>) nested[loc] = v;
          }
          if (nested.length >= 2) return nested;
        }
      }
    } catch (_) {/* keep trying */}
  }

  // 2. Fenced per-locale blocks (fallback).
  final fenced = <String, Map<String, dynamic>>{};
  final fenceRe = RegExp(
    r'(?:~~~|```)\s*([a-z]{2})\s*\n([\s\S]*?)\n\s*(?:~~~|```)',
    multiLine: true,
  );
  for (final m in fenceRe.allMatches(content)) {
    final loc = m.group(1)!;
    if (!_locales.contains(loc)) continue;
    final body = m.group(2)!.trim();
    try {
      final decoded = jsonDecode(body);
      if (decoded is Map<String, dynamic>) fenced[loc] = decoded;
    } catch (_) {/* skip */}
  }
  if (fenced.length == _locales.length) return fenced;

  // 3. Positional bare JSON.
  final blocks = _extractJsonObjects(content);
  final positional = <String, Map<String, dynamic>>{};
  for (var i = 0; i < blocks.length && i < _locales.length; i++) {
    try {
      final decoded = jsonDecode(blocks[i]);
      if (decoded is Map<String, dynamic>) {
        positional[_locales[i]] = decoded;
      }
    } catch (_) {/* skip */}
  }
  return positional.length > fenced.length ? positional : fenced;
}

List<String> _extractJsonObjects(String s) {
  final out = <String>[];
  var depth = 0;
  var startIdx = -1;
  var inString = false;
  var escape = false;
  for (var i = 0; i < s.length; i++) {
    final c = s[i];
    if (escape) {
      escape = false;
      continue;
    }
    if (inString) {
      if (c == r'\') {
        escape = true;
      } else if (c == '"') {
        inString = false;
      }
      continue;
    }
    if (c == '"') {
      inString = true;
      continue;
    }
    if (c == '{') {
      if (depth == 0) startIdx = i;
      depth++;
    } else if (c == '}') {
      depth--;
      if (depth == 0 && startIdx >= 0) {
        out.add(s.substring(startIdx, i + 1));
        startIdx = -1;
      }
    }
  }
  return out;
}
