-- Notification variants: fallback translations for 7 push types
-- (akhirah_milestone, disengagement_pause, featured_dua,
--  project_funded, streak_milestone, surah_kahf_friday, validate_seeds).
--
-- Generated by scripts/merge_notification_variant_batches.dart from
-- Gemini output. Placeholder tokens ({milestone}, {streak}, {streakType},
-- {projectName}) are preserved verbatim and substituted at send time by
-- supabase/functions/_shared/variants.ts::fillTemplate.
--
-- Idempotency: one INSERT per (type, locale). Existing rows are left
-- untouched.

INSERT INTO public.notification_variants (notification_type, locale, title, body, route) VALUES
  ('akhirah_milestone', 'ur', 'آپ کی آخرت کے لیے {milestone} XP', 'سبحان الله — آپ نے {milestone} XP کمالیے۔ ہر پوائنٹ آخرت کے لیے بویا گیا ایک عمل ہے۔ اسے جاری رکھیں۔', 'home'),
  ('disengagement_pause', 'ur', 'یاد دہانیاں روک دی گئیں', 'لگتا ہے آپ مصروف ہیں۔ ہم یاد دہانیاں روک رہے ہیں — جب دل چاہے Sabiq کھولیں، یہ خود بخود بحال ہو جائیں گی۔', 'home'),
  ('featured_dua', 'ur', 'آج کی ایک دعاء', '', 'dhikr'),
  ('project_funded', 'ur', 'آپ کا صدقہ اپنے ہدف تک پہنچ گیا', '"{projectName}" مکمل فنڈ ہو گیا ہے — حصہ بننے پر جزاك الله خيراً۔ فائدہ اٹھانے والے ہر شخص کے ساتھ آپ کا ثواب جاری ہے۔', 'home'),
  ('streak_milestone', 'ur', '{streakType} کے {streak} دن', 'ما شاء الله — لگاتار {streak} دن کی {streakType}۔ استقامت اللہ کو بہت پسند ہے۔ اس سلسلے کو قائم رکھیں۔', 'home'),
  ('surah_kahf_friday', 'ur', 'آج جمعہ ہے — سورة الكهف پڑھیں', 'جو شخص جمعہ کے دن سورة الكهف پڑھتا ہے، اس کے لیے دو جمعوں کے درمیان نور چمکتا ہے۔', 'quran'),
  ('validate_seeds', 'ur', 'آپ کے Seeds بڑھ رہے ہیں', 'حقیقی پروجیکٹس (یتیموں، مساجد، مفت کھانوں) میں Sabiq Seeds عطیہ کریں۔ ہر Seed ایک نیکی بوتا ہے۔', 'cause'),
  ('akhirah_milestone', 'ar', '{milestone} XP لآخرتك', 'سبحان الله — كسبت {milestone} XP. كل نقطة هي عمل صالح يُزرع لحياتك القادمة. استمر.', 'home'),
  ('disengagement_pause', 'ar', 'تم إيقاف التذكيرات', 'يبدو أن إشعاراتنا لا تصلك. سنوقفها حالياً — افتح Sabiq متى شئت وستعود للعمل تلقائياً.', 'home'),
  ('featured_dua', 'ar', 'دعاء اليوم', '', 'dhikr'),
  ('project_funded', 'ar', 'صدقتك حققت هدفها', 'تم تمويل "{projectName}" بالكامل — جزاك الله خيراً لمساهمتك. أجرك مستمر مع كل من ينتفع به.', 'home'),
  ('streak_milestone', 'ar', '{streak} أيام من {streakType}', 'ما شاء الله — {streak} يوماً متتالياً من {streakType}. أحب الأعمال إلى الله أدومها. حافظ على استمراريتك.', 'home'),
  ('surah_kahf_friday', 'ar', 'إنه الجمعة — اقرأ سورة الكهف', 'من قرأ سورة الكهف يوم الجمعة أضاء له من النور ما بين الجمعتين.', 'quran'),
  ('validate_seeds', 'ar', 'إن Seeds الخاصة بك تنمو', 'تبرع بـ Sabiq Seeds لتمويل مشاريع حقيقية — أيتام، مساجد، إطعام. كل Seed تزرع حسنة.', 'cause'),
  ('akhirah_milestone', 'fr', '{milestone} XP pour votre akhirah', $sb$Subhan Allah — vous avez gagné {milestone} XP. Chaque point est une bonne action pour l'au-delà. Continuez.$sb$, 'home'),
  ('disengagement_pause', 'fr', 'Rappels en pause', 'Il semble que nos rappels ne vous atteignent pas. Nous les mettons en pause — ouvrez Sabiq quand vous le souhaitez.', 'home'),
  ('featured_dua', 'fr', $sb$Une dua pour aujourd'hui$sb$, '', 'dhikr'),
  ('project_funded', 'fr', 'Votre sadaqah a atteint son but', '"{projectName}" est financé — jazak Allahu khayran pour votre aide. Votre récompense perdure avec chaque bénéficiaire.', 'home'),
  ('streak_milestone', 'fr', '{streak} jours de {streakType}', $sb$Ma sha Allah — {streak} jours de {streakType} de suite. La constance est ce qu'Allah aime le plus. Continuez !$sb$, 'home'),
  ('surah_kahf_friday', 'fr', $sb$C'est vendredi — lisez Sourate Al-Kahf$sb$, 'Quiconque lit la Sourate Al-Kahf le vendredi, une lumière brille pour lui entre les deux vendredis.', 'quran'),
  ('validate_seeds', 'fr', 'Vos Seeds grandissent', 'Donnez vos Sabiq Seeds pour financer de vrais projets (orphelins, mosquées, repas). Chaque Seed sème une bonne action.', 'cause'),
  ('akhirah_milestone', 'id', '{milestone} XP untuk akhirah Anda', 'Subhan Allah — Anda mendapat {milestone} XP. Setiap poin adalah amal untuk kehidupan kelak. Teruskan.', 'home'),
  ('disengagement_pause', 'id', 'Pengingat dijeda', 'Sepertinya pengingat kami tidak tersampaikan. Kami jeda sementara — buka Sabiq kapan pun dan pengingat akan aktif lagi.', 'home'),
  ('featured_dua', 'id', 'Doa untuk hari ini', '', 'dhikr'),
  ('project_funded', 'id', 'Sadaqah Anda mencapai targetnya', '"{projectName}" telah terdanai penuh — jazak Allahu khayran atas partisipasinya. Pahala Anda terus mengalir.', 'home'),
  ('streak_milestone', 'id', '{streak} hari {streakType}', 'Ma sha Allah — {streak} hari {streakType} berturut-turut. Konsistensi sangat dicintai Allah. Pertahankan streak Anda.', 'home'),
  ('surah_kahf_friday', 'id', 'Ini hari Jumat — baca Surah Al-Kahf', 'Barangsiapa membaca Surah Al-Kahf pada hari Jumat, cahaya akan meneranginya antara dua Jumat.', 'quran'),
  ('validate_seeds', 'id', 'Seeds Anda bertumbuh', 'Donasikan Sabiq Seeds Anda untuk mendanai proyek nyata — yatim, masjid, makanan gratis. Setiap Seed menanam amal.', 'cause'),
  ('akhirah_milestone', 'ms', '{milestone} XP untuk akhirah anda', 'Subhan Allah — anda meraih {milestone} XP. Setiap mata adalah amalan yang ditanam untuk akhirat. Teruskan usaha.', 'home'),
  ('disengagement_pause', 'ms', 'Peringatan dihentikan sementara', 'Nampaknya peringatan kami tidak sampai. Kami jeda buat masa ini — buka Sabiq bila-bila masa dan ia akan aktif semula.', 'home'),
  ('featured_dua', 'ms', 'Doa untuk hari ini', '', 'dhikr'),
  ('project_funded', 'ms', 'Sadaqah anda capai sasaran', '"{projectName}" dibiayai sepenuhnya — jazak Allahu khayran atas sokongan anda. Pahala anda mengalir buat setiap yang dibantu.', 'home'),
  ('streak_milestone', 'ms', '{streak} hari {streakType}', 'Ma sha Allah — {streak} hari {streakType} berturut-turut. Istiqamah amat dicintai Allah. Teruskan rentetan ini.', 'home'),
  ('surah_kahf_friday', 'ms', 'Hari ini Jumaat — baca Surah Al-Kahfi', 'Sesiapa membaca Surah Al-Kahfi pada hari Jumaat, cahaya akan meneranginya antara dua Jumaat.', 'quran'),
  ('validate_seeds', 'ms', 'Seeds anda semakin bertambah', 'Dermakan Sabiq Seeds anda untuk projek amal — anak yatim, masjid, makanan percuma. Setiap Seed menanam pahala.', 'cause'),
  ('akhirah_milestone', 'ru', '{milestone} XP для вашей ахиры', 'Субхан Аллах — вы получили {milestone} XP. Каждое очко — это благое дело для вечной жизни. Продолжайте.', 'home'),
  ('disengagement_pause', 'ru', 'Напоминания приостановлены', 'Кажется, наши уведомления вас не отвлекают. Мы их пока отключим — откройте Sabiq в любой момент, и они вернутся.', 'home'),
  ('featured_dua', 'ru', 'Дуа на сегодня', '', 'dhikr'),
  ('project_funded', 'ru', 'Ваша садака достигла цели', 'Проект «{projectName}» профинансирован — джазак Аллаху хайран за участие. Награда идет от каждого, кому он принесет пользу.', 'home'),
  ('streak_milestone', 'ru', '{streak} дней {streakType}', 'Ма ша Аллах — {streak} дней {streakType} подряд. Постоянство любимо Аллахом больше всего. Не прерывайте цепь.', 'home'),
  ('surah_kahf_friday', 'ru', 'Сегодня пятница — прочитайте суру Аль-Кахф', 'Того, кто прочитает суру Аль-Кахф в пятницу, будет освещать свет между двумя пятницами.', 'quran'),
  ('validate_seeds', 'ru', 'Ваши Seeds растут', 'Жертвуйте Sabiq Seeds на реальные проекты: сиротам, мечетям, на еду. Каждый Seed — это благое дело.', 'cause'),
  ('akhirah_milestone', 'tr', 'Ahiretiniz için {milestone} XP', 'Subhan Allah — {milestone} XP kazandınız. Her puan ahiret için ekilmiş bir tohumdur. Devam edin.', 'home'),
  ('disengagement_pause', 'tr', 'Hatırlatıcılar duraklatıldı', $sb$Görünüşe göre bildirimlerimiz size ulaşmıyor. Şimdilik sessize alıyoruz; Sabiq'i açtığınızda geri dönecekler.$sb$, 'home'),
  ('featured_dua', 'tr', 'Bugün için bir dua', '', 'dhikr'),
  ('project_funded', 'tr', 'Sadakanız hedefine ulaştı', '"{projectName}" tamamen fonlandı — destek olduğunuz için jazak Allahu khayran. Faydalandığı her canla ödülünüz devam eder.', 'home'),
  ('streak_milestone', 'tr', '{streak} gün {streakType}', $sb$Ma sha Allah — art arda {streak} gün {streakType}. İstikrar, Allah'ın en sevdiği şeydir. Zinciri kırmayın.$sb$, 'home'),
  ('surah_kahf_friday', 'tr', 'Bugün Cuma — Kehf Suresi okuyun', 'Kim Cuma günü Kehf Suresi okursa, iki Cuma arasında onun için bir nur parlar.', 'quran'),
  ('validate_seeds', 'tr', $sb$Seeds'leriniz büyüyor$sb$, 'Gerçek projeleri (yetimler, mescitler, ücretsiz yemekler) desteklemek için Sabiq Seeds bağışlayın. Her Seed bir iyiliktir.', 'cause');
